/*CORE*/
#ifdef USE_DYNAMIC_GL_CORE
DYNAMIC_GL_FEATURE(CORE)
DYNAMIC_GL_TYPEDEF(void,GLvoid)
DYNAMIC_GL_TYPEDEF(char,GLchar)
DYNAMIC_GL_TYPEDEF(unsigned int,GLenum)
DYNAMIC_GL_TYPEDEF(unsigned char,GLboolean)
DYNAMIC_GL_TYPEDEF(unsigned int,GLbitfield)
DYNAMIC_GL_TYPEDEF(khronos_int8_t,GLbyte)
DYNAMIC_GL_TYPEDEF(short,GLshort)
DYNAMIC_GL_TYPEDEF(int,GLint)
DYNAMIC_GL_TYPEDEF(int,GLsizei)
DYNAMIC_GL_TYPEDEF(khronos_uint8_t,GLubyte)
DYNAMIC_GL_TYPEDEF(unsigned short,GLushort)
DYNAMIC_GL_TYPEDEF(unsigned int,GLuint)
DYNAMIC_GL_TYPEDEF(khronos_float_t,GLfloat)
DYNAMIC_GL_TYPEDEF(khronos_float_t,GLclampf)
DYNAMIC_GL_TYPEDEF(khronos_int32_t,GLfixed)
DYNAMIC_GL_TYPEDEF(khronos_int32_t,GLclampx)
DYNAMIC_GL_TYPEDEF(khronos_intptr_t,GLintptr)
DYNAMIC_GL_TYPEDEF(khronos_ssize_t,GLsizeiptr)
DYNAMIC_GL_CONSTANT(GL_VERSION_ES_CM_1_0,1)
DYNAMIC_GL_CONSTANT(GL_VERSION_ES_CL_1_0,1)
DYNAMIC_GL_CONSTANT(GL_VERSION_ES_CM_1_1,1)
DYNAMIC_GL_CONSTANT(GL_VERSION_ES_CL_1_1,1)
DYNAMIC_GL_CONSTANT(GL_DEPTH_BUFFER_BIT,0x00000100)
DYNAMIC_GL_CONSTANT(GL_STENCIL_BUFFER_BIT,0x00000400)
DYNAMIC_GL_CONSTANT(GL_COLOR_BUFFER_BIT,0x00004000)
DYNAMIC_GL_CONSTANT(GL_FALSE,0)
DYNAMIC_GL_CONSTANT(GL_TRUE,1)
DYNAMIC_GL_CONSTANT(GL_POINTS,0x0000)
DYNAMIC_GL_CONSTANT(GL_LINES,0x0001)
DYNAMIC_GL_CONSTANT(GL_LINE_LOOP,0x0002)
DYNAMIC_GL_CONSTANT(GL_LINE_STRIP,0x0003)
DYNAMIC_GL_CONSTANT(GL_TRIANGLES,0x0004)
DYNAMIC_GL_CONSTANT(GL_TRIANGLE_STRIP,0x0005)
DYNAMIC_GL_CONSTANT(GL_TRIANGLE_FAN,0x0006)
DYNAMIC_GL_CONSTANT(GL_NEVER,0x0200)
DYNAMIC_GL_CONSTANT(GL_LESS,0x0201)
DYNAMIC_GL_CONSTANT(GL_EQUAL,0x0202)
DYNAMIC_GL_CONSTANT(GL_LEQUAL,0x0203)
DYNAMIC_GL_CONSTANT(GL_GREATER,0x0204)
DYNAMIC_GL_CONSTANT(GL_NOTEQUAL,0x0205)
DYNAMIC_GL_CONSTANT(GL_GEQUAL,0x0206)
DYNAMIC_GL_CONSTANT(GL_ALWAYS,0x0207)
DYNAMIC_GL_CONSTANT(GL_ZERO,0)
DYNAMIC_GL_CONSTANT(GL_ONE,1)
DYNAMIC_GL_CONSTANT(GL_SRC_COLOR,0x0300)
DYNAMIC_GL_CONSTANT(GL_ONE_MINUS_SRC_COLOR,0x0301)
DYNAMIC_GL_CONSTANT(GL_SRC_ALPHA,0x0302)
DYNAMIC_GL_CONSTANT(GL_ONE_MINUS_SRC_ALPHA,0x0303)
DYNAMIC_GL_CONSTANT(GL_DST_ALPHA,0x0304)
DYNAMIC_GL_CONSTANT(GL_ONE_MINUS_DST_ALPHA,0x0305)
DYNAMIC_GL_CONSTANT(GL_DST_COLOR,0x0306)
DYNAMIC_GL_CONSTANT(GL_ONE_MINUS_DST_COLOR,0x0307)
DYNAMIC_GL_CONSTANT(GL_SRC_ALPHA_SATURATE,0x0308)
DYNAMIC_GL_CONSTANT(GL_CLIP_PLANE0,0x3000)
DYNAMIC_GL_CONSTANT(GL_CLIP_PLANE1,0x3001)
DYNAMIC_GL_CONSTANT(GL_CLIP_PLANE2,0x3002)
DYNAMIC_GL_CONSTANT(GL_CLIP_PLANE3,0x3003)
DYNAMIC_GL_CONSTANT(GL_CLIP_PLANE4,0x3004)
DYNAMIC_GL_CONSTANT(GL_CLIP_PLANE5,0x3005)
DYNAMIC_GL_CONSTANT(GL_FRONT,0x0404)
DYNAMIC_GL_CONSTANT(GL_BACK,0x0405)
DYNAMIC_GL_CONSTANT(GL_FRONT_AND_BACK,0x0408)
DYNAMIC_GL_CONSTANT(GL_FOG,0x0B60)
DYNAMIC_GL_CONSTANT(GL_LIGHTING,0x0B50)
DYNAMIC_GL_CONSTANT(GL_TEXTURE_2D,0x0DE1)
DYNAMIC_GL_CONSTANT(GL_CULL_FACE,0x0B44)
DYNAMIC_GL_CONSTANT(GL_ALPHA_TEST,0x0BC0)
DYNAMIC_GL_CONSTANT(GL_BLEND,0x0BE2)
DYNAMIC_GL_CONSTANT(GL_COLOR_LOGIC_OP,0x0BF2)
DYNAMIC_GL_CONSTANT(GL_DITHER,0x0BD0)
DYNAMIC_GL_CONSTANT(GL_STENCIL_TEST,0x0B90)
DYNAMIC_GL_CONSTANT(GL_DEPTH_TEST,0x0B71)
DYNAMIC_GL_CONSTANT(GL_POINT_SMOOTH,0x0B10)
DYNAMIC_GL_CONSTANT(GL_LINE_SMOOTH,0x0B20)
DYNAMIC_GL_CONSTANT(GL_SCISSOR_TEST,0x0C11)
DYNAMIC_GL_CONSTANT(GL_COLOR_MATERIAL,0x0B57)
DYNAMIC_GL_CONSTANT(GL_NORMALIZE,0x0BA1)
DYNAMIC_GL_CONSTANT(GL_RESCALE_NORMAL,0x803A)
DYNAMIC_GL_CONSTANT(GL_POLYGON_OFFSET_FILL,0x8037)
DYNAMIC_GL_CONSTANT(GL_VERTEX_ARRAY,0x8074)
DYNAMIC_GL_CONSTANT(GL_NORMAL_ARRAY,0x8075)
DYNAMIC_GL_CONSTANT(GL_COLOR_ARRAY,0x8076)
DYNAMIC_GL_CONSTANT(GL_TEXTURE_COORD_ARRAY,0x8078)
DYNAMIC_GL_CONSTANT(GL_MULTISAMPLE,0x809D)
DYNAMIC_GL_CONSTANT(GL_SAMPLE_ALPHA_TO_COVERAGE,0x809E)
DYNAMIC_GL_CONSTANT(GL_SAMPLE_ALPHA_TO_ONE,0x809F)
DYNAMIC_GL_CONSTANT(GL_SAMPLE_COVERAGE,0x80A0)
DYNAMIC_GL_CONSTANT(GL_NO_ERROR,0)
DYNAMIC_GL_CONSTANT(GL_INVALID_ENUM,0x0500)
DYNAMIC_GL_CONSTANT(GL_INVALID_VALUE,0x0501)
DYNAMIC_GL_CONSTANT(GL_INVALID_OPERATION,0x0502)
DYNAMIC_GL_CONSTANT(GL_STACK_OVERFLOW,0x0503)
DYNAMIC_GL_CONSTANT(GL_STACK_UNDERFLOW,0x0504)
DYNAMIC_GL_CONSTANT(GL_OUT_OF_MEMORY,0x0505)
DYNAMIC_GL_CONSTANT(GL_EXP,0x0800)
DYNAMIC_GL_CONSTANT(GL_EXP2,0x0801)
DYNAMIC_GL_CONSTANT(GL_FOG_DENSITY,0x0B62)
DYNAMIC_GL_CONSTANT(GL_FOG_START,0x0B63)
DYNAMIC_GL_CONSTANT(GL_FOG_END,0x0B64)
DYNAMIC_GL_CONSTANT(GL_FOG_MODE,0x0B65)
DYNAMIC_GL_CONSTANT(GL_FOG_COLOR,0x0B66)
DYNAMIC_GL_CONSTANT(GL_CW,0x0900)
DYNAMIC_GL_CONSTANT(GL_CCW,0x0901)
DYNAMIC_GL_CONSTANT(GL_CURRENT_COLOR,0x0B00)
DYNAMIC_GL_CONSTANT(GL_CURRENT_NORMAL,0x0B02)
DYNAMIC_GL_CONSTANT(GL_CURRENT_TEXTURE_COORDS,0x0B03)
DYNAMIC_GL_CONSTANT(GL_POINT_SIZE,0x0B11)
DYNAMIC_GL_CONSTANT(GL_POINT_SIZE_MIN,0x8126)
DYNAMIC_GL_CONSTANT(GL_POINT_SIZE_MAX,0x8127)
DYNAMIC_GL_CONSTANT(GL_POINT_FADE_THRESHOLD_SIZE,0x8128)
DYNAMIC_GL_CONSTANT(GL_POINT_DISTANCE_ATTENUATION,0x8129)
DYNAMIC_GL_CONSTANT(GL_SMOOTH_POINT_SIZE_RANGE,0x0B12)
DYNAMIC_GL_CONSTANT(GL_LINE_WIDTH,0x0B21)
DYNAMIC_GL_CONSTANT(GL_SMOOTH_LINE_WIDTH_RANGE,0x0B22)
DYNAMIC_GL_CONSTANT(GL_ALIASED_POINT_SIZE_RANGE,0x846D)
DYNAMIC_GL_CONSTANT(GL_ALIASED_LINE_WIDTH_RANGE,0x846E)
DYNAMIC_GL_CONSTANT(GL_CULL_FACE_MODE,0x0B45)
DYNAMIC_GL_CONSTANT(GL_FRONT_FACE,0x0B46)
DYNAMIC_GL_CONSTANT(GL_SHADE_MODEL,0x0B54)
DYNAMIC_GL_CONSTANT(GL_DEPTH_RANGE,0x0B70)
DYNAMIC_GL_CONSTANT(GL_DEPTH_WRITEMASK,0x0B72)
DYNAMIC_GL_CONSTANT(GL_DEPTH_CLEAR_VALUE,0x0B73)
DYNAMIC_GL_CONSTANT(GL_DEPTH_FUNC,0x0B74)
DYNAMIC_GL_CONSTANT(GL_STENCIL_CLEAR_VALUE,0x0B91)
DYNAMIC_GL_CONSTANT(GL_STENCIL_FUNC,0x0B92)
DYNAMIC_GL_CONSTANT(GL_STENCIL_VALUE_MASK,0x0B93)
DYNAMIC_GL_CONSTANT(GL_STENCIL_FAIL,0x0B94)
DYNAMIC_GL_CONSTANT(GL_STENCIL_PASS_DEPTH_FAIL,0x0B95)
DYNAMIC_GL_CONSTANT(GL_STENCIL_PASS_DEPTH_PASS,0x0B96)
DYNAMIC_GL_CONSTANT(GL_STENCIL_REF,0x0B97)
DYNAMIC_GL_CONSTANT(GL_STENCIL_WRITEMASK,0x0B98)
DYNAMIC_GL_CONSTANT(GL_MATRIX_MODE,0x0BA0)
DYNAMIC_GL_CONSTANT(GL_VIEWPORT,0x0BA2)
DYNAMIC_GL_CONSTANT(GL_MODELVIEW_STACK_DEPTH,0x0BA3)
DYNAMIC_GL_CONSTANT(GL_PROJECTION_STACK_DEPTH,0x0BA4)
DYNAMIC_GL_CONSTANT(GL_TEXTURE_STACK_DEPTH,0x0BA5)
DYNAMIC_GL_CONSTANT(GL_MODELVIEW_MATRIX,0x0BA6)
DYNAMIC_GL_CONSTANT(GL_PROJECTION_MATRIX,0x0BA7)
DYNAMIC_GL_CONSTANT(GL_TEXTURE_MATRIX,0x0BA8)
DYNAMIC_GL_CONSTANT(GL_ALPHA_TEST_FUNC,0x0BC1)
DYNAMIC_GL_CONSTANT(GL_ALPHA_TEST_REF,0x0BC2)
DYNAMIC_GL_CONSTANT(GL_BLEND_DST,0x0BE0)
DYNAMIC_GL_CONSTANT(GL_BLEND_SRC,0x0BE1)
DYNAMIC_GL_CONSTANT(GL_LOGIC_OP_MODE,0x0BF0)
DYNAMIC_GL_CONSTANT(GL_SCISSOR_BOX,0x0C10)
DYNAMIC_GL_CONSTANT(GL_SCISSOR_TEST,0x0C11)
DYNAMIC_GL_CONSTANT(GL_COLOR_CLEAR_VALUE,0x0C22)
DYNAMIC_GL_CONSTANT(GL_COLOR_WRITEMASK,0x0C23)
DYNAMIC_GL_CONSTANT(GL_UNPACK_ALIGNMENT,0x0CF5)
DYNAMIC_GL_CONSTANT(GL_PACK_ALIGNMENT,0x0D05)
DYNAMIC_GL_CONSTANT(GL_MAX_LIGHTS,0x0D31)
DYNAMIC_GL_CONSTANT(GL_MAX_CLIP_PLANES,0x0D32)
DYNAMIC_GL_CONSTANT(GL_MAX_TEXTURE_SIZE,0x0D33)
DYNAMIC_GL_CONSTANT(GL_MAX_MODELVIEW_STACK_DEPTH,0x0D36)
DYNAMIC_GL_CONSTANT(GL_MAX_PROJECTION_STACK_DEPTH,0x0D38)
DYNAMIC_GL_CONSTANT(GL_MAX_TEXTURE_STACK_DEPTH,0x0D39)
DYNAMIC_GL_CONSTANT(GL_MAX_VIEWPORT_DIMS,0x0D3A)
DYNAMIC_GL_CONSTANT(GL_MAX_TEXTURE_UNITS,0x84E2)
DYNAMIC_GL_CONSTANT(GL_SUBPIXEL_BITS,0x0D50)
DYNAMIC_GL_CONSTANT(GL_RED_BITS,0x0D52)
DYNAMIC_GL_CONSTANT(GL_GREEN_BITS,0x0D53)
DYNAMIC_GL_CONSTANT(GL_BLUE_BITS,0x0D54)
DYNAMIC_GL_CONSTANT(GL_ALPHA_BITS,0x0D55)
DYNAMIC_GL_CONSTANT(GL_DEPTH_BITS,0x0D56)
DYNAMIC_GL_CONSTANT(GL_STENCIL_BITS,0x0D57)
DYNAMIC_GL_CONSTANT(GL_POLYGON_OFFSET_UNITS,0x2A00)
DYNAMIC_GL_CONSTANT(GL_POLYGON_OFFSET_FILL,0x8037)
DYNAMIC_GL_CONSTANT(GL_POLYGON_OFFSET_FACTOR,0x8038)
DYNAMIC_GL_CONSTANT(GL_TEXTURE_BINDING_2D,0x8069)
DYNAMIC_GL_CONSTANT(GL_VERTEX_ARRAY_SIZE,0x807A)
DYNAMIC_GL_CONSTANT(GL_VERTEX_ARRAY_TYPE,0x807B)
DYNAMIC_GL_CONSTANT(GL_VERTEX_ARRAY_STRIDE,0x807C)
DYNAMIC_GL_CONSTANT(GL_NORMAL_ARRAY_TYPE,0x807E)
DYNAMIC_GL_CONSTANT(GL_NORMAL_ARRAY_STRIDE,0x807F)
DYNAMIC_GL_CONSTANT(GL_COLOR_ARRAY_SIZE,0x8081)
DYNAMIC_GL_CONSTANT(GL_COLOR_ARRAY_TYPE,0x8082)
DYNAMIC_GL_CONSTANT(GL_COLOR_ARRAY_STRIDE,0x8083)
DYNAMIC_GL_CONSTANT(GL_TEXTURE_COORD_ARRAY_SIZE,0x8088)
DYNAMIC_GL_CONSTANT(GL_TEXTURE_COORD_ARRAY_TYPE,0x8089)
DYNAMIC_GL_CONSTANT(GL_TEXTURE_COORD_ARRAY_STRIDE,0x808A)
DYNAMIC_GL_CONSTANT(GL_VERTEX_ARRAY_POINTER,0x808E)
DYNAMIC_GL_CONSTANT(GL_NORMAL_ARRAY_POINTER,0x808F)
DYNAMIC_GL_CONSTANT(GL_COLOR_ARRAY_POINTER,0x8090)
DYNAMIC_GL_CONSTANT(GL_TEXTURE_COORD_ARRAY_POINTER,0x8092)
DYNAMIC_GL_CONSTANT(GL_SAMPLE_BUFFERS,0x80A8)
DYNAMIC_GL_CONSTANT(GL_SAMPLES,0x80A9)
DYNAMIC_GL_CONSTANT(GL_SAMPLE_COVERAGE_VALUE,0x80AA)
DYNAMIC_GL_CONSTANT(GL_SAMPLE_COVERAGE_INVERT,0x80AB)
DYNAMIC_GL_CONSTANT(GL_NUM_COMPRESSED_TEXTURE_FORMATS,0x86A2)
DYNAMIC_GL_CONSTANT(GL_COMPRESSED_TEXTURE_FORMATS,0x86A3)
DYNAMIC_GL_CONSTANT(GL_DONT_CARE,0x1100)
DYNAMIC_GL_CONSTANT(GL_FASTEST,0x1101)
DYNAMIC_GL_CONSTANT(GL_NICEST,0x1102)
DYNAMIC_GL_CONSTANT(GL_PERSPECTIVE_CORRECTION_HINT,0x0C50)
DYNAMIC_GL_CONSTANT(GL_POINT_SMOOTH_HINT,0x0C51)
DYNAMIC_GL_CONSTANT(GL_LINE_SMOOTH_HINT,0x0C52)
DYNAMIC_GL_CONSTANT(GL_FOG_HINT,0x0C54)
DYNAMIC_GL_CONSTANT(GL_GENERATE_MIPMAP_HINT,0x8192)
DYNAMIC_GL_CONSTANT(GL_LIGHT_MODEL_AMBIENT,0x0B53)
DYNAMIC_GL_CONSTANT(GL_LIGHT_MODEL_TWO_SIDE,0x0B52)
DYNAMIC_GL_CONSTANT(GL_AMBIENT,0x1200)
DYNAMIC_GL_CONSTANT(GL_DIFFUSE,0x1201)
DYNAMIC_GL_CONSTANT(GL_SPECULAR,0x1202)
DYNAMIC_GL_CONSTANT(GL_POSITION,0x1203)
DYNAMIC_GL_CONSTANT(GL_SPOT_DIRECTION,0x1204)
DYNAMIC_GL_CONSTANT(GL_SPOT_EXPONENT,0x1205)
DYNAMIC_GL_CONSTANT(GL_SPOT_CUTOFF,0x1206)
DYNAMIC_GL_CONSTANT(GL_CONSTANT_ATTENUATION,0x1207)
DYNAMIC_GL_CONSTANT(GL_LINEAR_ATTENUATION,0x1208)
DYNAMIC_GL_CONSTANT(GL_QUADRATIC_ATTENUATION,0x1209)
DYNAMIC_GL_CONSTANT(GL_BYTE,0x1400)
DYNAMIC_GL_CONSTANT(GL_UNSIGNED_BYTE,0x1401)
DYNAMIC_GL_CONSTANT(GL_SHORT,0x1402)
DYNAMIC_GL_CONSTANT(GL_UNSIGNED_SHORT,0x1403)
DYNAMIC_GL_CONSTANT(GL_FLOAT,0x1406)
DYNAMIC_GL_CONSTANT(GL_FIXED,0x140C)
DYNAMIC_GL_CONSTANT(GL_CLEAR,0x1500)
DYNAMIC_GL_CONSTANT(GL_AND,0x1501)
DYNAMIC_GL_CONSTANT(GL_AND_REVERSE,0x1502)
DYNAMIC_GL_CONSTANT(GL_COPY,0x1503)
DYNAMIC_GL_CONSTANT(GL_AND_INVERTED,0x1504)
DYNAMIC_GL_CONSTANT(GL_NOOP,0x1505)
DYNAMIC_GL_CONSTANT(GL_XOR,0x1506)
DYNAMIC_GL_CONSTANT(GL_OR,0x1507)
DYNAMIC_GL_CONSTANT(GL_NOR,0x1508)
DYNAMIC_GL_CONSTANT(GL_EQUIV,0x1509)
DYNAMIC_GL_CONSTANT(GL_INVERT,0x150A)
DYNAMIC_GL_CONSTANT(GL_OR_REVERSE,0x150B)
DYNAMIC_GL_CONSTANT(GL_COPY_INVERTED,0x150C)
DYNAMIC_GL_CONSTANT(GL_OR_INVERTED,0x150D)
DYNAMIC_GL_CONSTANT(GL_NAND,0x150E)
DYNAMIC_GL_CONSTANT(GL_SET,0x150F)
DYNAMIC_GL_CONSTANT(GL_EMISSION,0x1600)
DYNAMIC_GL_CONSTANT(GL_SHININESS,0x1601)
DYNAMIC_GL_CONSTANT(GL_AMBIENT_AND_DIFFUSE,0x1602)
DYNAMIC_GL_CONSTANT(GL_MODELVIEW,0x1700)
DYNAMIC_GL_CONSTANT(GL_PROJECTION,0x1701)
DYNAMIC_GL_CONSTANT(GL_TEXTURE,0x1702)
DYNAMIC_GL_CONSTANT(GL_ALPHA,0x1906)
DYNAMIC_GL_CONSTANT(GL_RGB,0x1907)
DYNAMIC_GL_CONSTANT(GL_RGBA,0x1908)
DYNAMIC_GL_CONSTANT(GL_LUMINANCE,0x1909)
DYNAMIC_GL_CONSTANT(GL_LUMINANCE_ALPHA,0x190A)
DYNAMIC_GL_CONSTANT(GL_UNPACK_ALIGNMENT,0x0CF5)
DYNAMIC_GL_CONSTANT(GL_PACK_ALIGNMENT,0x0D05)
DYNAMIC_GL_CONSTANT(GL_UNSIGNED_SHORT_4_4_4_4,0x8033)
DYNAMIC_GL_CONSTANT(GL_UNSIGNED_SHORT_5_5_5_1,0x8034)
DYNAMIC_GL_CONSTANT(GL_UNSIGNED_SHORT_5_6_5,0x8363)
DYNAMIC_GL_CONSTANT(GL_FLAT,0x1D00)
DYNAMIC_GL_CONSTANT(GL_SMOOTH,0x1D01)
DYNAMIC_GL_CONSTANT(GL_KEEP,0x1E00)
DYNAMIC_GL_CONSTANT(GL_REPLACE,0x1E01)
DYNAMIC_GL_CONSTANT(GL_INCR,0x1E02)
DYNAMIC_GL_CONSTANT(GL_DECR,0x1E03)
DYNAMIC_GL_CONSTANT(GL_VENDOR,0x1F00)
DYNAMIC_GL_CONSTANT(GL_RENDERER,0x1F01)
DYNAMIC_GL_CONSTANT(GL_VERSION,0x1F02)
DYNAMIC_GL_CONSTANT(GL_EXTENSIONS,0x1F03)
DYNAMIC_GL_CONSTANT(GL_MODULATE,0x2100)
DYNAMIC_GL_CONSTANT(GL_DECAL,0x2101)
DYNAMIC_GL_CONSTANT(GL_ADD,0x0104)
DYNAMIC_GL_CONSTANT(GL_TEXTURE_ENV_MODE,0x2200)
DYNAMIC_GL_CONSTANT(GL_TEXTURE_ENV_COLOR,0x2201)
DYNAMIC_GL_CONSTANT(GL_TEXTURE_ENV,0x2300)
DYNAMIC_GL_CONSTANT(GL_NEAREST,0x2600)
DYNAMIC_GL_CONSTANT(GL_LINEAR,0x2601)
DYNAMIC_GL_CONSTANT(GL_NEAREST_MIPMAP_NEAREST,0x2700)
DYNAMIC_GL_CONSTANT(GL_LINEAR_MIPMAP_NEAREST,0x2701)
DYNAMIC_GL_CONSTANT(GL_NEAREST_MIPMAP_LINEAR,0x2702)
DYNAMIC_GL_CONSTANT(GL_LINEAR_MIPMAP_LINEAR,0x2703)
DYNAMIC_GL_CONSTANT(GL_TEXTURE_MAG_FILTER,0x2800)
DYNAMIC_GL_CONSTANT(GL_TEXTURE_MIN_FILTER,0x2801)
DYNAMIC_GL_CONSTANT(GL_TEXTURE_WRAP_S,0x2802)
DYNAMIC_GL_CONSTANT(GL_TEXTURE_WRAP_T,0x2803)
DYNAMIC_GL_CONSTANT(GL_GENERATE_MIPMAP,0x8191)
DYNAMIC_GL_CONSTANT(GL_TEXTURE0,0x84C0)
DYNAMIC_GL_CONSTANT(GL_TEXTURE1,0x84C1)
DYNAMIC_GL_CONSTANT(GL_TEXTURE2,0x84C2)
DYNAMIC_GL_CONSTANT(GL_TEXTURE3,0x84C3)
DYNAMIC_GL_CONSTANT(GL_TEXTURE4,0x84C4)
DYNAMIC_GL_CONSTANT(GL_TEXTURE5,0x84C5)
DYNAMIC_GL_CONSTANT(GL_TEXTURE6,0x84C6)
DYNAMIC_GL_CONSTANT(GL_TEXTURE7,0x84C7)
DYNAMIC_GL_CONSTANT(GL_TEXTURE8,0x84C8)
DYNAMIC_GL_CONSTANT(GL_TEXTURE9,0x84C9)
DYNAMIC_GL_CONSTANT(GL_TEXTURE10,0x84CA)
DYNAMIC_GL_CONSTANT(GL_TEXTURE11,0x84CB)
DYNAMIC_GL_CONSTANT(GL_TEXTURE12,0x84CC)
DYNAMIC_GL_CONSTANT(GL_TEXTURE13,0x84CD)
DYNAMIC_GL_CONSTANT(GL_TEXTURE14,0x84CE)
DYNAMIC_GL_CONSTANT(GL_TEXTURE15,0x84CF)
DYNAMIC_GL_CONSTANT(GL_TEXTURE16,0x84D0)
DYNAMIC_GL_CONSTANT(GL_TEXTURE17,0x84D1)
DYNAMIC_GL_CONSTANT(GL_TEXTURE18,0x84D2)
DYNAMIC_GL_CONSTANT(GL_TEXTURE19,0x84D3)
DYNAMIC_GL_CONSTANT(GL_TEXTURE20,0x84D4)
DYNAMIC_GL_CONSTANT(GL_TEXTURE21,0x84D5)
DYNAMIC_GL_CONSTANT(GL_TEXTURE22,0x84D6)
DYNAMIC_GL_CONSTANT(GL_TEXTURE23,0x84D7)
DYNAMIC_GL_CONSTANT(GL_TEXTURE24,0x84D8)
DYNAMIC_GL_CONSTANT(GL_TEXTURE25,0x84D9)
DYNAMIC_GL_CONSTANT(GL_TEXTURE26,0x84DA)
DYNAMIC_GL_CONSTANT(GL_TEXTURE27,0x84DB)
DYNAMIC_GL_CONSTANT(GL_TEXTURE28,0x84DC)
DYNAMIC_GL_CONSTANT(GL_TEXTURE29,0x84DD)
DYNAMIC_GL_CONSTANT(GL_TEXTURE30,0x84DE)
DYNAMIC_GL_CONSTANT(GL_TEXTURE31,0x84DF)
DYNAMIC_GL_CONSTANT(GL_ACTIVE_TEXTURE,0x84E0)
DYNAMIC_GL_CONSTANT(GL_CLIENT_ACTIVE_TEXTURE,0x84E1)
DYNAMIC_GL_CONSTANT(GL_REPEAT,0x2901)
DYNAMIC_GL_CONSTANT(GL_CLAMP_TO_EDGE,0x812F)
DYNAMIC_GL_CONSTANT(GL_LIGHT0,0x4000)
DYNAMIC_GL_CONSTANT(GL_LIGHT1,0x4001)
DYNAMIC_GL_CONSTANT(GL_LIGHT2,0x4002)
DYNAMIC_GL_CONSTANT(GL_LIGHT3,0x4003)
DYNAMIC_GL_CONSTANT(GL_LIGHT4,0x4004)
DYNAMIC_GL_CONSTANT(GL_LIGHT5,0x4005)
DYNAMIC_GL_CONSTANT(GL_LIGHT6,0x4006)
DYNAMIC_GL_CONSTANT(GL_LIGHT7,0x4007)
DYNAMIC_GL_CONSTANT(GL_ARRAY_BUFFER,0x8892)
DYNAMIC_GL_CONSTANT(GL_ELEMENT_ARRAY_BUFFER,0x8893)
DYNAMIC_GL_CONSTANT(GL_ARRAY_BUFFER_BINDING,0x8894)
DYNAMIC_GL_CONSTANT(GL_ELEMENT_ARRAY_BUFFER_BINDING,0x8895)
DYNAMIC_GL_CONSTANT(GL_VERTEX_ARRAY_BUFFER_BINDING,0x8896)
DYNAMIC_GL_CONSTANT(GL_NORMAL_ARRAY_BUFFER_BINDING,0x8897)
DYNAMIC_GL_CONSTANT(GL_COLOR_ARRAY_BUFFER_BINDING,0x8898)
DYNAMIC_GL_CONSTANT(GL_TEXTURE_COORD_ARRAY_BUFFER_BINDING,0x889A)
DYNAMIC_GL_CONSTANT(GL_STATIC_DRAW,0x88E4)
DYNAMIC_GL_CONSTANT(GL_DYNAMIC_DRAW,0x88E8)
DYNAMIC_GL_CONSTANT(GL_BUFFER_SIZE,0x8764)
DYNAMIC_GL_CONSTANT(GL_BUFFER_USAGE,0x8765)
DYNAMIC_GL_CONSTANT(GL_SUBTRACT,0x84E7)
DYNAMIC_GL_CONSTANT(GL_COMBINE,0x8570)
DYNAMIC_GL_CONSTANT(GL_COMBINE_RGB,0x8571)
DYNAMIC_GL_CONSTANT(GL_COMBINE_ALPHA,0x8572)
DYNAMIC_GL_CONSTANT(GL_RGB_SCALE,0x8573)
DYNAMIC_GL_CONSTANT(GL_ADD_SIGNED,0x8574)
DYNAMIC_GL_CONSTANT(GL_INTERPOLATE,0x8575)
DYNAMIC_GL_CONSTANT(GL_CONSTANT,0x8576)
DYNAMIC_GL_CONSTANT(GL_PRIMARY_COLOR,0x8577)
DYNAMIC_GL_CONSTANT(GL_PREVIOUS,0x8578)
DYNAMIC_GL_CONSTANT(GL_OPERAND0_RGB,0x8590)
DYNAMIC_GL_CONSTANT(GL_OPERAND1_RGB,0x8591)
DYNAMIC_GL_CONSTANT(GL_OPERAND2_RGB,0x8592)
DYNAMIC_GL_CONSTANT(GL_OPERAND0_ALPHA,0x8598)
DYNAMIC_GL_CONSTANT(GL_OPERAND1_ALPHA,0x8599)
DYNAMIC_GL_CONSTANT(GL_OPERAND2_ALPHA,0x859A)
DYNAMIC_GL_CONSTANT(GL_ALPHA_SCALE,0x0D1C)
DYNAMIC_GL_CONSTANT(GL_SRC0_RGB,0x8580)
DYNAMIC_GL_CONSTANT(GL_SRC1_RGB,0x8581)
DYNAMIC_GL_CONSTANT(GL_SRC2_RGB,0x8582)
DYNAMIC_GL_CONSTANT(GL_SRC0_ALPHA,0x8588)
DYNAMIC_GL_CONSTANT(GL_SRC1_ALPHA,0x8589)
DYNAMIC_GL_CONSTANT(GL_SRC2_ALPHA,0x858A)
DYNAMIC_GL_CONSTANT(GL_DOT3_RGB,0x86AE)
DYNAMIC_GL_CONSTANT(GL_DOT3_RGBA,0x86AF)
DYNAMIC_GL_FUNCTION_V(AlphaFunc,(DYNAMIC_GL_TYPE(GLenum) func , DYNAMIC_GL_TYPE(GLclampf) ref),(func , ref))
DYNAMIC_GL_FUNCTION_V(ClearColor,(DYNAMIC_GL_TYPE(GLclampf) red , DYNAMIC_GL_TYPE(GLclampf) green , DYNAMIC_GL_TYPE(GLclampf) blue , DYNAMIC_GL_TYPE(GLclampf) alpha),(red , green , blue , alpha))
DYNAMIC_GL_FUNCTION_V(ClearDepthf,(DYNAMIC_GL_TYPE(GLclampf) depth),(depth))
DYNAMIC_GL_FUNCTION_V(ClipPlanef,(DYNAMIC_GL_TYPE(GLenum) plane , const DYNAMIC_GL_TYPE(GLfloat) * equation),(plane , equation))
DYNAMIC_GL_FUNCTION_V(Color4f,(DYNAMIC_GL_TYPE(GLfloat) red , DYNAMIC_GL_TYPE(GLfloat) green , DYNAMIC_GL_TYPE(GLfloat) blue , DYNAMIC_GL_TYPE(GLfloat) alpha),(red , green , blue , alpha))
DYNAMIC_GL_FUNCTION_V(DepthRangef,(DYNAMIC_GL_TYPE(GLclampf) zNear , DYNAMIC_GL_TYPE(GLclampf) zFar),(zNear , zFar))
DYNAMIC_GL_FUNCTION_V(Fogf,(DYNAMIC_GL_TYPE(GLenum) pname , DYNAMIC_GL_TYPE(GLfloat) param),(pname , param))
DYNAMIC_GL_FUNCTION_V(Fogfv,(DYNAMIC_GL_TYPE(GLenum) pname , const DYNAMIC_GL_TYPE(GLfloat) * params),(pname , params))
DYNAMIC_GL_FUNCTION_V(Frustumf,(DYNAMIC_GL_TYPE(GLfloat) left , DYNAMIC_GL_TYPE(GLfloat) right , DYNAMIC_GL_TYPE(GLfloat) bottom , DYNAMIC_GL_TYPE(GLfloat) top , DYNAMIC_GL_TYPE(GLfloat) zNear , DYNAMIC_GL_TYPE(GLfloat) zFar),(left , right , bottom , top , zNear , zFar))
DYNAMIC_GL_FUNCTION_V(GetFloatv,(DYNAMIC_GL_TYPE(GLenum) pname , DYNAMIC_GL_TYPE(GLfloat) * params),(pname , params))
DYNAMIC_GL_FUNCTION_V(GetLightfv,(DYNAMIC_GL_TYPE(GLenum) light , DYNAMIC_GL_TYPE(GLenum) pname , DYNAMIC_GL_TYPE(GLfloat) * params),(light , pname , params))
DYNAMIC_GL_FUNCTION_V(GetMaterialfv,(DYNAMIC_GL_TYPE(GLenum) face , DYNAMIC_GL_TYPE(GLenum) pname , DYNAMIC_GL_TYPE(GLfloat) * params),(face , pname , params))
DYNAMIC_GL_FUNCTION_V(GetTexEnvfv,(DYNAMIC_GL_TYPE(GLenum) env , DYNAMIC_GL_TYPE(GLenum) pname , DYNAMIC_GL_TYPE(GLfloat) * params),(env , pname , params))
DYNAMIC_GL_FUNCTION_V(GetTexParameterfv,(DYNAMIC_GL_TYPE(GLenum) target , DYNAMIC_GL_TYPE(GLenum) pname , DYNAMIC_GL_TYPE(GLfloat) * params),(target , pname , params))
DYNAMIC_GL_FUNCTION_V(LightModelf,(DYNAMIC_GL_TYPE(GLenum) pname , DYNAMIC_GL_TYPE(GLfloat) param),(pname , param))
DYNAMIC_GL_FUNCTION_V(LightModelfv,(DYNAMIC_GL_TYPE(GLenum) pname , const DYNAMIC_GL_TYPE(GLfloat) * params),(pname , params))
DYNAMIC_GL_FUNCTION_V(Lightf,(DYNAMIC_GL_TYPE(GLenum) light , DYNAMIC_GL_TYPE(GLenum) pname , DYNAMIC_GL_TYPE(GLfloat) param),(light , pname , param))
DYNAMIC_GL_FUNCTION_V(Lightfv,(DYNAMIC_GL_TYPE(GLenum) light , DYNAMIC_GL_TYPE(GLenum) pname , const DYNAMIC_GL_TYPE(GLfloat) * params),(light , pname , params))
DYNAMIC_GL_FUNCTION_V(LineWidth,(DYNAMIC_GL_TYPE(GLfloat) width),(width))
DYNAMIC_GL_FUNCTION_V(LoadMatrixf,(const DYNAMIC_GL_TYPE(GLfloat) * m),(m))
DYNAMIC_GL_FUNCTION_V(Materialf,(DYNAMIC_GL_TYPE(GLenum) face , DYNAMIC_GL_TYPE(GLenum) pname , DYNAMIC_GL_TYPE(GLfloat) param),(face , pname , param))
DYNAMIC_GL_FUNCTION_V(Materialfv,(DYNAMIC_GL_TYPE(GLenum) face , DYNAMIC_GL_TYPE(GLenum) pname , const DYNAMIC_GL_TYPE(GLfloat) * params),(face , pname , params))
DYNAMIC_GL_FUNCTION_V(MultMatrixf,(const DYNAMIC_GL_TYPE(GLfloat) * m),(m))
DYNAMIC_GL_FUNCTION_V(MultiTexCoord4f,(DYNAMIC_GL_TYPE(GLenum) target , DYNAMIC_GL_TYPE(GLfloat) s , DYNAMIC_GL_TYPE(GLfloat) t , DYNAMIC_GL_TYPE(GLfloat) r , DYNAMIC_GL_TYPE(GLfloat) q),(target , s , t , r , q))
DYNAMIC_GL_FUNCTION_V(Normal3f,(DYNAMIC_GL_TYPE(GLfloat) nx , DYNAMIC_GL_TYPE(GLfloat) ny , DYNAMIC_GL_TYPE(GLfloat) nz),(nx , ny , nz))
DYNAMIC_GL_FUNCTION_V(Orthof,(DYNAMIC_GL_TYPE(GLfloat) left , DYNAMIC_GL_TYPE(GLfloat) right , DYNAMIC_GL_TYPE(GLfloat) bottom , DYNAMIC_GL_TYPE(GLfloat) top , DYNAMIC_GL_TYPE(GLfloat) zNear , DYNAMIC_GL_TYPE(GLfloat) zFar),(left , right , bottom , top , zNear , zFar))
DYNAMIC_GL_FUNCTION_V(PointParameterf,(DYNAMIC_GL_TYPE(GLenum) pname , DYNAMIC_GL_TYPE(GLfloat) param),(pname , param))
DYNAMIC_GL_FUNCTION_V(PointParameterfv,(DYNAMIC_GL_TYPE(GLenum) pname , const DYNAMIC_GL_TYPE(GLfloat) * params),(pname , params))
DYNAMIC_GL_FUNCTION_V(PointSize,(DYNAMIC_GL_TYPE(GLfloat) size),(size))
DYNAMIC_GL_FUNCTION_V(PolygonOffset,(DYNAMIC_GL_TYPE(GLfloat) factor , DYNAMIC_GL_TYPE(GLfloat) units),(factor , units))
DYNAMIC_GL_FUNCTION_V(Rotatef,(DYNAMIC_GL_TYPE(GLfloat) angle , DYNAMIC_GL_TYPE(GLfloat) x , DYNAMIC_GL_TYPE(GLfloat) y , DYNAMIC_GL_TYPE(GLfloat) z),(angle , x , y , z))
DYNAMIC_GL_FUNCTION_V(Scalef,(DYNAMIC_GL_TYPE(GLfloat) x , DYNAMIC_GL_TYPE(GLfloat) y , DYNAMIC_GL_TYPE(GLfloat) z),(x , y , z))
DYNAMIC_GL_FUNCTION_V(TexEnvf,(DYNAMIC_GL_TYPE(GLenum) target , DYNAMIC_GL_TYPE(GLenum) pname , DYNAMIC_GL_TYPE(GLfloat) param),(target , pname , param))
DYNAMIC_GL_FUNCTION_V(TexEnvfv,(DYNAMIC_GL_TYPE(GLenum) target , DYNAMIC_GL_TYPE(GLenum) pname , const DYNAMIC_GL_TYPE(GLfloat) * params),(target , pname , params))
DYNAMIC_GL_FUNCTION_V(TexParameterf,(DYNAMIC_GL_TYPE(GLenum) target , DYNAMIC_GL_TYPE(GLenum) pname , DYNAMIC_GL_TYPE(GLfloat) param),(target , pname , param))
DYNAMIC_GL_FUNCTION_V(TexParameterfv,(DYNAMIC_GL_TYPE(GLenum) target , DYNAMIC_GL_TYPE(GLenum) pname , const DYNAMIC_GL_TYPE(GLfloat) * params),(target , pname , params))
DYNAMIC_GL_FUNCTION_V(Translatef,(DYNAMIC_GL_TYPE(GLfloat) x , DYNAMIC_GL_TYPE(GLfloat) y , DYNAMIC_GL_TYPE(GLfloat) z),(x , y , z))
DYNAMIC_GL_FUNCTION_V(ActiveTexture,(DYNAMIC_GL_TYPE(GLenum) texture),(texture))
DYNAMIC_GL_FUNCTION_V(AlphaFuncx,(DYNAMIC_GL_TYPE(GLenum) func , DYNAMIC_GL_TYPE(GLclampx) ref),(func , ref))
DYNAMIC_GL_FUNCTION_V(BindBuffer,(DYNAMIC_GL_TYPE(GLenum) target , DYNAMIC_GL_TYPE(GLuint) buffer),(target , buffer))
DYNAMIC_GL_FUNCTION_V(BindTexture,(DYNAMIC_GL_TYPE(GLenum) target , DYNAMIC_GL_TYPE(GLuint) texture),(target , texture))
DYNAMIC_GL_FUNCTION_V(BlendFunc,(DYNAMIC_GL_TYPE(GLenum) sfactor , DYNAMIC_GL_TYPE(GLenum) dfactor),(sfactor , dfactor))
DYNAMIC_GL_FUNCTION_V(BufferData,(DYNAMIC_GL_TYPE(GLenum) target , DYNAMIC_GL_TYPE(GLsizeiptr) size , const DYNAMIC_GL_TYPE(GLvoid) * data , DYNAMIC_GL_TYPE(GLenum) usage),(target , size , data , usage))
DYNAMIC_GL_FUNCTION_V(BufferSubData,(DYNAMIC_GL_TYPE(GLenum) target , DYNAMIC_GL_TYPE(GLintptr) offset , DYNAMIC_GL_TYPE(GLsizeiptr) size , const DYNAMIC_GL_TYPE(GLvoid) * data),(target , offset , size , data))
DYNAMIC_GL_FUNCTION_V(Clear,(DYNAMIC_GL_TYPE(GLbitfield) mask),(mask))
DYNAMIC_GL_FUNCTION_V(ClearColorx,(DYNAMIC_GL_TYPE(GLclampx) red , DYNAMIC_GL_TYPE(GLclampx) green , DYNAMIC_GL_TYPE(GLclampx) blue , DYNAMIC_GL_TYPE(GLclampx) alpha),(red , green , blue , alpha))
DYNAMIC_GL_FUNCTION_V(ClearDepthx,(DYNAMIC_GL_TYPE(GLclampx) depth),(depth))
DYNAMIC_GL_FUNCTION_V(ClearStencil,(DYNAMIC_GL_TYPE(GLint) s),(s))
DYNAMIC_GL_FUNCTION_V(ClientActiveTexture,(DYNAMIC_GL_TYPE(GLenum) texture),(texture))
DYNAMIC_GL_FUNCTION_V(ClipPlanex,(DYNAMIC_GL_TYPE(GLenum) plane , const DYNAMIC_GL_TYPE(GLfixed) * equation),(plane , equation))
DYNAMIC_GL_FUNCTION_V(Color4ub,(DYNAMIC_GL_TYPE(GLubyte) red , DYNAMIC_GL_TYPE(GLubyte) green , DYNAMIC_GL_TYPE(GLubyte) blue , DYNAMIC_GL_TYPE(GLubyte) alpha),(red , green , blue , alpha))
DYNAMIC_GL_FUNCTION_V(Color4x,(DYNAMIC_GL_TYPE(GLfixed) red , DYNAMIC_GL_TYPE(GLfixed) green , DYNAMIC_GL_TYPE(GLfixed) blue , DYNAMIC_GL_TYPE(GLfixed) alpha),(red , green , blue , alpha))
DYNAMIC_GL_FUNCTION_V(ColorMask,(DYNAMIC_GL_TYPE(GLboolean) red , DYNAMIC_GL_TYPE(GLboolean) green , DYNAMIC_GL_TYPE(GLboolean) blue , DYNAMIC_GL_TYPE(GLboolean) alpha),(red , green , blue , alpha))
DYNAMIC_GL_FUNCTION_V(ColorPointer,(DYNAMIC_GL_TYPE(GLint) size , DYNAMIC_GL_TYPE(GLenum) type , DYNAMIC_GL_TYPE(GLsizei) stride , const DYNAMIC_GL_TYPE(GLvoid) * pointer),(size , type , stride , pointer))
DYNAMIC_GL_FUNCTION_V(CompressedTexImage2D,(DYNAMIC_GL_TYPE(GLenum) target , DYNAMIC_GL_TYPE(GLint) level , DYNAMIC_GL_TYPE(GLenum) internalformat , DYNAMIC_GL_TYPE(GLsizei) width , DYNAMIC_GL_TYPE(GLsizei) height , DYNAMIC_GL_TYPE(GLint) border , DYNAMIC_GL_TYPE(GLsizei) imageSize , const DYNAMIC_GL_TYPE(GLvoid) * data),(target , level , internalformat , width , height , border , imageSize , data))
DYNAMIC_GL_FUNCTION_V(CompressedTexSubImage2D,(DYNAMIC_GL_TYPE(GLenum) target , DYNAMIC_GL_TYPE(GLint) level , DYNAMIC_GL_TYPE(GLint) xoffset , DYNAMIC_GL_TYPE(GLint) yoffset , DYNAMIC_GL_TYPE(GLsizei) width , DYNAMIC_GL_TYPE(GLsizei) height , DYNAMIC_GL_TYPE(GLenum) format , DYNAMIC_GL_TYPE(GLsizei) imageSize , const DYNAMIC_GL_TYPE(GLvoid) * data),(target , level , xoffset , yoffset , width , height , format , imageSize , data))
DYNAMIC_GL_FUNCTION_V(CopyTexImage2D,(DYNAMIC_GL_TYPE(GLenum) target , DYNAMIC_GL_TYPE(GLint) level , DYNAMIC_GL_TYPE(GLenum) internalformat , DYNAMIC_GL_TYPE(GLint) x , DYNAMIC_GL_TYPE(GLint) y , DYNAMIC_GL_TYPE(GLsizei) width , DYNAMIC_GL_TYPE(GLsizei) height , DYNAMIC_GL_TYPE(GLint) border),(target , level , internalformat , x , y , width , height , border))
DYNAMIC_GL_FUNCTION_V(CopyTexSubImage2D,(DYNAMIC_GL_TYPE(GLenum) target , DYNAMIC_GL_TYPE(GLint) level , DYNAMIC_GL_TYPE(GLint) xoffset , DYNAMIC_GL_TYPE(GLint) yoffset , DYNAMIC_GL_TYPE(GLint) x , DYNAMIC_GL_TYPE(GLint) y , DYNAMIC_GL_TYPE(GLsizei) width , DYNAMIC_GL_TYPE(GLsizei) height),(target , level , xoffset , yoffset , x , y , width , height))
DYNAMIC_GL_FUNCTION_V(CullFace,(DYNAMIC_GL_TYPE(GLenum) mode),(mode))
DYNAMIC_GL_FUNCTION_V(DeleteBuffers,(DYNAMIC_GL_TYPE(GLsizei) n , const DYNAMIC_GL_TYPE(GLuint) * buffers),(n , buffers))
DYNAMIC_GL_FUNCTION_V(DeleteTextures,(DYNAMIC_GL_TYPE(GLsizei) n , const DYNAMIC_GL_TYPE(GLuint) * textures),(n , textures))
DYNAMIC_GL_FUNCTION_V(DepthFunc,(DYNAMIC_GL_TYPE(GLenum) func),(func))
DYNAMIC_GL_FUNCTION_V(DepthMask,(DYNAMIC_GL_TYPE(GLboolean) flag),(flag))
DYNAMIC_GL_FUNCTION_V(DepthRangex,(DYNAMIC_GL_TYPE(GLclampx) zNear , DYNAMIC_GL_TYPE(GLclampx) zFar),(zNear , zFar))
DYNAMIC_GL_FUNCTION_V(Disable,(DYNAMIC_GL_TYPE(GLenum) cap),(cap))
DYNAMIC_GL_FUNCTION_V(DisableClientState,(DYNAMIC_GL_TYPE(GLenum) array),(array))
DYNAMIC_GL_FUNCTION_V(DrawArrays,(DYNAMIC_GL_TYPE(GLenum) mode , DYNAMIC_GL_TYPE(GLint) first , DYNAMIC_GL_TYPE(GLsizei) count),(mode , first , count))
DYNAMIC_GL_FUNCTION_V(DrawElements,(DYNAMIC_GL_TYPE(GLenum) mode , DYNAMIC_GL_TYPE(GLsizei) count , DYNAMIC_GL_TYPE(GLenum) type , const DYNAMIC_GL_TYPE(GLvoid) * indices),(mode , count , type , indices))
DYNAMIC_GL_FUNCTION_V(Enable,(DYNAMIC_GL_TYPE(GLenum) cap),(cap))
DYNAMIC_GL_FUNCTION_V(EnableClientState,(DYNAMIC_GL_TYPE(GLenum) array),(array))
DYNAMIC_GL_FUNCTION_V(Finish,(),())
DYNAMIC_GL_FUNCTION_V(Flush,(),())
DYNAMIC_GL_FUNCTION_V(Fogx,(DYNAMIC_GL_TYPE(GLenum) pname , DYNAMIC_GL_TYPE(GLfixed) param),(pname , param))
DYNAMIC_GL_FUNCTION_V(Fogxv,(DYNAMIC_GL_TYPE(GLenum) pname , const DYNAMIC_GL_TYPE(GLfixed) * params),(pname , params))
DYNAMIC_GL_FUNCTION_V(FrontFace,(DYNAMIC_GL_TYPE(GLenum) mode),(mode))
DYNAMIC_GL_FUNCTION_V(Frustumx,(DYNAMIC_GL_TYPE(GLfixed) left , DYNAMIC_GL_TYPE(GLfixed) right , DYNAMIC_GL_TYPE(GLfixed) bottom , DYNAMIC_GL_TYPE(GLfixed) top , DYNAMIC_GL_TYPE(GLfixed) zNear , DYNAMIC_GL_TYPE(GLfixed) zFar),(left , right , bottom , top , zNear , zFar))
DYNAMIC_GL_FUNCTION_V(GetBooleanv,(DYNAMIC_GL_TYPE(GLenum) pname , DYNAMIC_GL_TYPE(GLboolean) * params),(pname , params))
DYNAMIC_GL_FUNCTION_V(GetBufferParameteriv,(DYNAMIC_GL_TYPE(GLenum) target , DYNAMIC_GL_TYPE(GLenum) pname , DYNAMIC_GL_TYPE(GLint) * params),(target , pname , params))
DYNAMIC_GL_FUNCTION_V(GenBuffers,(DYNAMIC_GL_TYPE(GLsizei) n , DYNAMIC_GL_TYPE(GLuint) * buffers),(n , buffers))
DYNAMIC_GL_FUNCTION_V(GenTextures,(DYNAMIC_GL_TYPE(GLsizei) n , DYNAMIC_GL_TYPE(GLuint) * textures),(n , textures))
DYNAMIC_GL_FUNCTION(DYNAMIC_GL_TYPE(GLenum),GetError,(),())
DYNAMIC_GL_FUNCTION_V(GetFixedv,(DYNAMIC_GL_TYPE(GLenum) pname , DYNAMIC_GL_TYPE(GLfixed) * params),(pname , params))
DYNAMIC_GL_FUNCTION_V(GetIntegerv,(DYNAMIC_GL_TYPE(GLenum) pname , DYNAMIC_GL_TYPE(GLint) * params),(pname , params))
DYNAMIC_GL_FUNCTION_V(GetLightxv,(DYNAMIC_GL_TYPE(GLenum) light , DYNAMIC_GL_TYPE(GLenum) pname , DYNAMIC_GL_TYPE(GLfixed) * params),(light , pname , params))
DYNAMIC_GL_FUNCTION_V(GetMaterialxv,(DYNAMIC_GL_TYPE(GLenum) face , DYNAMIC_GL_TYPE(GLenum) pname , DYNAMIC_GL_TYPE(GLfixed) * params),(face , pname , params))
DYNAMIC_GL_FUNCTION_V(GetPointerv,(DYNAMIC_GL_TYPE(GLenum) pname , DYNAMIC_GL_TYPE(GLvoid) * p1),(pname , p1))
DYNAMIC_GL_FUNCTION(DYNAMIC_GL_TYPE(GLubyte*),GetString,(DYNAMIC_GL_TYPE(GLenum) name),(name))
DYNAMIC_GL_FUNCTION_V(GetTexEnviv,(DYNAMIC_GL_TYPE(GLenum) env , DYNAMIC_GL_TYPE(GLenum) pname , DYNAMIC_GL_TYPE(GLint) * params),(env , pname , params))
DYNAMIC_GL_FUNCTION_V(GetTexEnvxv,(DYNAMIC_GL_TYPE(GLenum) env , DYNAMIC_GL_TYPE(GLenum) pname , DYNAMIC_GL_TYPE(GLfixed) * params),(env , pname , params))
DYNAMIC_GL_FUNCTION_V(GetTexParameteriv,(DYNAMIC_GL_TYPE(GLenum) target , DYNAMIC_GL_TYPE(GLenum) pname , DYNAMIC_GL_TYPE(GLint) * params),(target , pname , params))
DYNAMIC_GL_FUNCTION_V(GetTexParameterxv,(DYNAMIC_GL_TYPE(GLenum) target , DYNAMIC_GL_TYPE(GLenum) pname , DYNAMIC_GL_TYPE(GLfixed) * params),(target , pname , params))
DYNAMIC_GL_FUNCTION_V(Hint,(DYNAMIC_GL_TYPE(GLenum) target , DYNAMIC_GL_TYPE(GLenum) mode),(target , mode))
DYNAMIC_GL_FUNCTION(DYNAMIC_GL_TYPE(GLboolean),IsBuffer,(DYNAMIC_GL_TYPE(GLuint) buffer),(buffer))
DYNAMIC_GL_FUNCTION(DYNAMIC_GL_TYPE(GLboolean),IsEnabled,(DYNAMIC_GL_TYPE(GLenum) cap),(cap))
DYNAMIC_GL_FUNCTION(DYNAMIC_GL_TYPE(GLboolean),IsTexture,(DYNAMIC_GL_TYPE(GLuint) texture),(texture))
DYNAMIC_GL_FUNCTION_V(LightModelx,(DYNAMIC_GL_TYPE(GLenum) pname , DYNAMIC_GL_TYPE(GLfixed) param),(pname , param))
DYNAMIC_GL_FUNCTION_V(LightModelxv,(DYNAMIC_GL_TYPE(GLenum) pname , const DYNAMIC_GL_TYPE(GLfixed) * params),(pname , params))
DYNAMIC_GL_FUNCTION_V(Lightx,(DYNAMIC_GL_TYPE(GLenum) light , DYNAMIC_GL_TYPE(GLenum) pname , DYNAMIC_GL_TYPE(GLfixed) param),(light , pname , param))
DYNAMIC_GL_FUNCTION_V(Lightxv,(DYNAMIC_GL_TYPE(GLenum) light , DYNAMIC_GL_TYPE(GLenum) pname , const DYNAMIC_GL_TYPE(GLfixed) * params),(light , pname , params))
DYNAMIC_GL_FUNCTION_V(LineWidthx,(DYNAMIC_GL_TYPE(GLfixed) width),(width))
DYNAMIC_GL_FUNCTION_V(LoadIdentity,(),())
DYNAMIC_GL_FUNCTION_V(LoadMatrixx,(const DYNAMIC_GL_TYPE(GLfixed) * m),(m))
DYNAMIC_GL_FUNCTION_V(LogicOp,(DYNAMIC_GL_TYPE(GLenum) opcode),(opcode))
DYNAMIC_GL_FUNCTION_V(Materialx,(DYNAMIC_GL_TYPE(GLenum) face , DYNAMIC_GL_TYPE(GLenum) pname , DYNAMIC_GL_TYPE(GLfixed) param),(face , pname , param))
DYNAMIC_GL_FUNCTION_V(Materialxv,(DYNAMIC_GL_TYPE(GLenum) face , DYNAMIC_GL_TYPE(GLenum) pname , const DYNAMIC_GL_TYPE(GLfixed) * params),(face , pname , params))
DYNAMIC_GL_FUNCTION_V(MatrixMode,(DYNAMIC_GL_TYPE(GLenum) mode),(mode))
DYNAMIC_GL_FUNCTION_V(MultMatrixx,(const DYNAMIC_GL_TYPE(GLfixed) * m),(m))
DYNAMIC_GL_FUNCTION_V(MultiTexCoord4x,(DYNAMIC_GL_TYPE(GLenum) target , DYNAMIC_GL_TYPE(GLfixed) s , DYNAMIC_GL_TYPE(GLfixed) t , DYNAMIC_GL_TYPE(GLfixed) r , DYNAMIC_GL_TYPE(GLfixed) q),(target , s , t , r , q))
DYNAMIC_GL_FUNCTION_V(Normal3x,(DYNAMIC_GL_TYPE(GLfixed) nx , DYNAMIC_GL_TYPE(GLfixed) ny , DYNAMIC_GL_TYPE(GLfixed) nz),(nx , ny , nz))
DYNAMIC_GL_FUNCTION_V(NormalPointer,(DYNAMIC_GL_TYPE(GLenum) type , DYNAMIC_GL_TYPE(GLsizei) stride , const DYNAMIC_GL_TYPE(GLvoid) * pointer),(type , stride , pointer))
DYNAMIC_GL_FUNCTION_V(Orthox,(DYNAMIC_GL_TYPE(GLfixed) left , DYNAMIC_GL_TYPE(GLfixed) right , DYNAMIC_GL_TYPE(GLfixed) bottom , DYNAMIC_GL_TYPE(GLfixed) top , DYNAMIC_GL_TYPE(GLfixed) zNear , DYNAMIC_GL_TYPE(GLfixed) zFar),(left , right , bottom , top , zNear , zFar))
DYNAMIC_GL_FUNCTION_V(PixelStorei,(DYNAMIC_GL_TYPE(GLenum) pname , DYNAMIC_GL_TYPE(GLint) param),(pname , param))
DYNAMIC_GL_FUNCTION_V(PointParameterx,(DYNAMIC_GL_TYPE(GLenum) pname , DYNAMIC_GL_TYPE(GLfixed) param),(pname , param))
DYNAMIC_GL_FUNCTION_V(PointParameterxv,(DYNAMIC_GL_TYPE(GLenum) pname , const DYNAMIC_GL_TYPE(GLfixed) * params),(pname , params))
DYNAMIC_GL_FUNCTION_V(PointSizex,(DYNAMIC_GL_TYPE(GLfixed) size),(size))
DYNAMIC_GL_FUNCTION_V(PolygonOffsetx,(DYNAMIC_GL_TYPE(GLfixed) factor , DYNAMIC_GL_TYPE(GLfixed) units),(factor , units))
DYNAMIC_GL_FUNCTION_V(PopMatrix,(),())
DYNAMIC_GL_FUNCTION_V(PushMatrix,(),())
DYNAMIC_GL_FUNCTION_V(ReadPixels,(DYNAMIC_GL_TYPE(GLint) x , DYNAMIC_GL_TYPE(GLint) y , DYNAMIC_GL_TYPE(GLsizei) width , DYNAMIC_GL_TYPE(GLsizei) height , DYNAMIC_GL_TYPE(GLenum) format , DYNAMIC_GL_TYPE(GLenum) type , DYNAMIC_GL_TYPE(GLvoid) * pixels),(x , y , width , height , format , type , pixels))
DYNAMIC_GL_FUNCTION_V(Rotatex,(DYNAMIC_GL_TYPE(GLfixed) angle , DYNAMIC_GL_TYPE(GLfixed) x , DYNAMIC_GL_TYPE(GLfixed) y , DYNAMIC_GL_TYPE(GLfixed) z),(angle , x , y , z))
DYNAMIC_GL_FUNCTION_V(SampleCoverage,(DYNAMIC_GL_TYPE(GLclampf) value , DYNAMIC_GL_TYPE(GLboolean) invert),(value , invert))
DYNAMIC_GL_FUNCTION_V(SampleCoveragex,(DYNAMIC_GL_TYPE(GLclampx) value , DYNAMIC_GL_TYPE(GLboolean) invert),(value , invert))
DYNAMIC_GL_FUNCTION_V(Scalex,(DYNAMIC_GL_TYPE(GLfixed) x , DYNAMIC_GL_TYPE(GLfixed) y , DYNAMIC_GL_TYPE(GLfixed) z),(x , y , z))
DYNAMIC_GL_FUNCTION_V(Scissor,(DYNAMIC_GL_TYPE(GLint) x , DYNAMIC_GL_TYPE(GLint) y , DYNAMIC_GL_TYPE(GLsizei) width , DYNAMIC_GL_TYPE(GLsizei) height),(x , y , width , height))
DYNAMIC_GL_FUNCTION_V(ShadeModel,(DYNAMIC_GL_TYPE(GLenum) mode),(mode))
DYNAMIC_GL_FUNCTION_V(StencilFunc,(DYNAMIC_GL_TYPE(GLenum) func , DYNAMIC_GL_TYPE(GLint) ref , DYNAMIC_GL_TYPE(GLuint) mask),(func , ref , mask))
DYNAMIC_GL_FUNCTION_V(StencilMask,(DYNAMIC_GL_TYPE(GLuint) mask),(mask))
DYNAMIC_GL_FUNCTION_V(StencilOp,(DYNAMIC_GL_TYPE(GLenum) fail , DYNAMIC_GL_TYPE(GLenum) zfail , DYNAMIC_GL_TYPE(GLenum) zpass),(fail , zfail , zpass))
DYNAMIC_GL_FUNCTION_V(TexCoordPointer,(DYNAMIC_GL_TYPE(GLint) size , DYNAMIC_GL_TYPE(GLenum) type , DYNAMIC_GL_TYPE(GLsizei) stride , const DYNAMIC_GL_TYPE(GLvoid) * pointer),(size , type , stride , pointer))
DYNAMIC_GL_FUNCTION_V(TexEnvi,(DYNAMIC_GL_TYPE(GLenum) target , DYNAMIC_GL_TYPE(GLenum) pname , DYNAMIC_GL_TYPE(GLint) param),(target , pname , param))
DYNAMIC_GL_FUNCTION_V(TexEnvx,(DYNAMIC_GL_TYPE(GLenum) target , DYNAMIC_GL_TYPE(GLenum) pname , DYNAMIC_GL_TYPE(GLfixed) param),(target , pname , param))
DYNAMIC_GL_FUNCTION_V(TexEnviv,(DYNAMIC_GL_TYPE(GLenum) target , DYNAMIC_GL_TYPE(GLenum) pname , const DYNAMIC_GL_TYPE(GLint) * params),(target , pname , params))
DYNAMIC_GL_FUNCTION_V(TexEnvxv,(DYNAMIC_GL_TYPE(GLenum) target , DYNAMIC_GL_TYPE(GLenum) pname , const DYNAMIC_GL_TYPE(GLfixed) * params),(target , pname , params))
DYNAMIC_GL_FUNCTION_V(TexImage2D,(DYNAMIC_GL_TYPE(GLenum) target , DYNAMIC_GL_TYPE(GLint) level , DYNAMIC_GL_TYPE(GLint) internalformat , DYNAMIC_GL_TYPE(GLsizei) width , DYNAMIC_GL_TYPE(GLsizei) height , DYNAMIC_GL_TYPE(GLint) border , DYNAMIC_GL_TYPE(GLenum) format , DYNAMIC_GL_TYPE(GLenum) type , const DYNAMIC_GL_TYPE(GLvoid) * pixels),(target , level , internalformat , width , height , border , format , type , pixels))
DYNAMIC_GL_FUNCTION_V(TexParameteri,(DYNAMIC_GL_TYPE(GLenum) target , DYNAMIC_GL_TYPE(GLenum) pname , DYNAMIC_GL_TYPE(GLint) param),(target , pname , param))
DYNAMIC_GL_FUNCTION_V(TexParameterx,(DYNAMIC_GL_TYPE(GLenum) target , DYNAMIC_GL_TYPE(GLenum) pname , DYNAMIC_GL_TYPE(GLfixed) param),(target , pname , param))
DYNAMIC_GL_FUNCTION_V(TexParameteriv,(DYNAMIC_GL_TYPE(GLenum) target , DYNAMIC_GL_TYPE(GLenum) pname , const DYNAMIC_GL_TYPE(GLint) * params),(target , pname , params))
DYNAMIC_GL_FUNCTION_V(TexParameterxv,(DYNAMIC_GL_TYPE(GLenum) target , DYNAMIC_GL_TYPE(GLenum) pname , const DYNAMIC_GL_TYPE(GLfixed) * params),(target , pname , params))
DYNAMIC_GL_FUNCTION_V(TexSubImage2D,(DYNAMIC_GL_TYPE(GLenum) target , DYNAMIC_GL_TYPE(GLint) level , DYNAMIC_GL_TYPE(GLint) xoffset , DYNAMIC_GL_TYPE(GLint) yoffset , DYNAMIC_GL_TYPE(GLsizei) width , DYNAMIC_GL_TYPE(GLsizei) height , DYNAMIC_GL_TYPE(GLenum) format , DYNAMIC_GL_TYPE(GLenum) type , const DYNAMIC_GL_TYPE(GLvoid) * pixels),(target , level , xoffset , yoffset , width , height , format , type , pixels))
DYNAMIC_GL_FUNCTION_V(Translatex,(DYNAMIC_GL_TYPE(GLfixed) x , DYNAMIC_GL_TYPE(GLfixed) y , DYNAMIC_GL_TYPE(GLfixed) z),(x , y , z))
DYNAMIC_GL_FUNCTION_V(VertexPointer,(DYNAMIC_GL_TYPE(GLint) size , DYNAMIC_GL_TYPE(GLenum) type , DYNAMIC_GL_TYPE(GLsizei) stride , const DYNAMIC_GL_TYPE(GLvoid) * pointer),(size , type , stride , pointer))
DYNAMIC_GL_FUNCTION_V(Viewport,(DYNAMIC_GL_TYPE(GLint) x , DYNAMIC_GL_TYPE(GLint) y , DYNAMIC_GL_TYPE(GLsizei) width , DYNAMIC_GL_TYPE(GLsizei) height),(x , y , width , height))
#endif /*USE_DYNAMIC_GL_CORE*/

/*OES_query_matrix*/
#ifdef USE_DYNAMIC_GL_OES_query_matrix
DYNAMIC_GL_FEATURE(OES_query_matrix)
#endif /*USE_DYNAMIC_GL_OES_query_matrix*/

/*APIENTRYP*/
#ifdef USE_DYNAMIC_GL_APIENTRYP
DYNAMIC_GL_FEATURE(APIENTRYP)
#endif /*USE_DYNAMIC_GL_APIENTRYP*/

/*OES_stencil_wrap*/
#ifdef USE_DYNAMIC_GL_OES_stencil_wrap
DYNAMIC_GL_FEATURE(OES_stencil_wrap)
DYNAMIC_GL_CONSTANT(GL_INCR_WRAP_OES,0x8507)
DYNAMIC_GL_CONSTANT(GL_DECR_WRAP_OES,0x8508)
#endif /*USE_DYNAMIC_GL_OES_stencil_wrap*/

/*EXT_texture_format_BGRA8888*/
#ifdef USE_DYNAMIC_GL_EXT_texture_format_BGRA8888
DYNAMIC_GL_FEATURE(EXT_texture_format_BGRA8888)
DYNAMIC_GL_CONSTANT(GL_BGRA_EXT,0x80E1)
#endif /*USE_DYNAMIC_GL_EXT_texture_format_BGRA8888*/

/*OES_fbo_render_mipmap*/
#ifdef USE_DYNAMIC_GL_OES_fbo_render_mipmap
DYNAMIC_GL_FEATURE(OES_fbo_render_mipmap)
#endif /*USE_DYNAMIC_GL_OES_fbo_render_mipmap*/

/*IMG_multisampled_render_to_texture*/
#ifdef USE_DYNAMIC_GL_IMG_multisampled_render_to_texture
DYNAMIC_GL_FEATURE(IMG_multisampled_render_to_texture)
DYNAMIC_GL_CONSTANT(GL_RENDERBUFFER_SAMPLES_IMG,0x9133)
DYNAMIC_GL_CONSTANT(GL_FRAMEBUFFER_INCOMPLETE_MULTISAMPLE_IMG,0x9134)
DYNAMIC_GL_CONSTANT(GL_MAX_SAMPLES_IMG,0x9135)
DYNAMIC_GL_CONSTANT(GL_TEXTURE_SAMPLES_IMG,0x9136)
DYNAMIC_GL_FUNCTION_V(RenderbufferStorageMultisampleIMG,(DYNAMIC_GL_TYPE(GLenum) target , DYNAMIC_GL_TYPE(GLsizei) samples , DYNAMIC_GL_TYPE(GLenum) internalformat , DYNAMIC_GL_TYPE(GLsizei) width , DYNAMIC_GL_TYPE(GLsizei) height),(target , samples , internalformat , width , height))
DYNAMIC_GL_FUNCTION_V(FramebufferTexture2DMultisampleIMG,(DYNAMIC_GL_TYPE(GLenum) target , DYNAMIC_GL_TYPE(GLenum) attachment , DYNAMIC_GL_TYPE(GLenum) textarget , DYNAMIC_GL_TYPE(GLuint) texture , DYNAMIC_GL_TYPE(GLint) level , DYNAMIC_GL_TYPE(GLsizei) samples),(target , attachment , textarget , texture , level , samples))
#endif /*USE_DYNAMIC_GL_IMG_multisampled_render_to_texture*/

/*EXT_map_buffer_range*/
#ifdef USE_DYNAMIC_GL_EXT_map_buffer_range
DYNAMIC_GL_FEATURE(EXT_map_buffer_range)
DYNAMIC_GL_CONSTANT(GL_MAP_READ_BIT_EXT,0x0001)
DYNAMIC_GL_CONSTANT(GL_MAP_WRITE_BIT_EXT,0x0002)
DYNAMIC_GL_CONSTANT(GL_MAP_INVALIDATE_RANGE_BIT_EXT,0x0004)
DYNAMIC_GL_CONSTANT(GL_MAP_INVALIDATE_BUFFER_BIT_EXT,0x0008)
DYNAMIC_GL_CONSTANT(GL_MAP_FLUSH_EXPLICIT_BIT_EXT,0x0010)
DYNAMIC_GL_CONSTANT(GL_MAP_UNSYNCHRONIZED_BIT_EXT,0x0020)
DYNAMIC_GL_FUNCTION_V(FlushMappedBufferRangeEXT,(DYNAMIC_GL_TYPE(GLenum) target , DYNAMIC_GL_TYPE(GLintptr) offset , DYNAMIC_GL_TYPE(GLsizeiptr) length),(target , offset , length))
#endif /*USE_DYNAMIC_GL_EXT_map_buffer_range*/

/*EXT_texture_lod_bias*/
#ifdef USE_DYNAMIC_GL_EXT_texture_lod_bias
DYNAMIC_GL_FEATURE(EXT_texture_lod_bias)
DYNAMIC_GL_CONSTANT(GL_MAX_TEXTURE_LOD_BIAS_EXT,0x84FD)
DYNAMIC_GL_CONSTANT(GL_TEXTURE_FILTER_CONTROL_EXT,0x8500)
DYNAMIC_GL_CONSTANT(GL_TEXTURE_LOD_BIAS_EXT,0x8501)
#endif /*USE_DYNAMIC_GL_EXT_texture_lod_bias*/

/*EXT_texture_compression_dxt1*/
#ifdef USE_DYNAMIC_GL_EXT_texture_compression_dxt1
DYNAMIC_GL_FEATURE(EXT_texture_compression_dxt1)
DYNAMIC_GL_CONSTANT(GL_COMPRESSED_RGB_S3TC_DXT1_EXT,0x83F0)
DYNAMIC_GL_CONSTANT(GL_COMPRESSED_RGBA_S3TC_DXT1_EXT,0x83F1)
#endif /*USE_DYNAMIC_GL_EXT_texture_compression_dxt1*/

/*OES_blend_equation_separate*/
#ifdef USE_DYNAMIC_GL_OES_blend_equation_separate
DYNAMIC_GL_FEATURE(OES_blend_equation_separate)
DYNAMIC_GL_CONSTANT(GL_BLEND_EQUATION_RGB_OES,0x8009)
DYNAMIC_GL_CONSTANT(GL_BLEND_EQUATION_ALPHA_OES,0x883D)
DYNAMIC_GL_FUNCTION_V(BlendEquationSeparateOES,(DYNAMIC_GL_TYPE(GLenum) modeRGB , DYNAMIC_GL_TYPE(GLenum) modeAlpha),(modeRGB , modeAlpha))
#endif /*USE_DYNAMIC_GL_OES_blend_equation_separate*/

/*OES_texture_mirrored_repeat*/
#ifdef USE_DYNAMIC_GL_OES_texture_mirrored_repeat
DYNAMIC_GL_FEATURE(OES_texture_mirrored_repeat)
DYNAMIC_GL_CONSTANT(GL_MIRRORED_REPEAT_OES,0x8370)
#endif /*USE_DYNAMIC_GL_OES_texture_mirrored_repeat*/

/*OES_framebuffer_object*/
#ifdef USE_DYNAMIC_GL_OES_framebuffer_object
DYNAMIC_GL_FEATURE(OES_framebuffer_object)
DYNAMIC_GL_CONSTANT(GL_FRAMEBUFFER_OES,0x8D40)
DYNAMIC_GL_CONSTANT(GL_RENDERBUFFER_OES,0x8D41)
DYNAMIC_GL_CONSTANT(GL_RGBA4_OES,0x8056)
DYNAMIC_GL_CONSTANT(GL_RGB5_A1_OES,0x8057)
DYNAMIC_GL_CONSTANT(GL_RGB565_OES,0x8D62)
DYNAMIC_GL_CONSTANT(GL_DEPTH_COMPONENT16_OES,0x81A5)
DYNAMIC_GL_CONSTANT(GL_RENDERBUFFER_WIDTH_OES,0x8D42)
DYNAMIC_GL_CONSTANT(GL_RENDERBUFFER_HEIGHT_OES,0x8D43)
DYNAMIC_GL_CONSTANT(GL_RENDERBUFFER_INTERNAL_FORMAT_OES,0x8D44)
DYNAMIC_GL_CONSTANT(GL_RENDERBUFFER_RED_SIZE_OES,0x8D50)
DYNAMIC_GL_CONSTANT(GL_RENDERBUFFER_GREEN_SIZE_OES,0x8D51)
DYNAMIC_GL_CONSTANT(GL_RENDERBUFFER_BLUE_SIZE_OES,0x8D52)
DYNAMIC_GL_CONSTANT(GL_RENDERBUFFER_ALPHA_SIZE_OES,0x8D53)
DYNAMIC_GL_CONSTANT(GL_RENDERBUFFER_DEPTH_SIZE_OES,0x8D54)
DYNAMIC_GL_CONSTANT(GL_RENDERBUFFER_STENCIL_SIZE_OES,0x8D55)
DYNAMIC_GL_CONSTANT(GL_FRAMEBUFFER_ATTACHMENT_OBJECT_TYPE_OES,0x8CD0)
DYNAMIC_GL_CONSTANT(GL_FRAMEBUFFER_ATTACHMENT_OBJECT_NAME_OES,0x8CD1)
DYNAMIC_GL_CONSTANT(GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_LEVEL_OES,0x8CD2)
DYNAMIC_GL_CONSTANT(GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_CUBE_MAP_FACE_OES,0x8CD3)
DYNAMIC_GL_CONSTANT(GL_COLOR_ATTACHMENT0_OES,0x8CE0)
DYNAMIC_GL_CONSTANT(GL_DEPTH_ATTACHMENT_OES,0x8D00)
DYNAMIC_GL_CONSTANT(GL_STENCIL_ATTACHMENT_OES,0x8D20)
DYNAMIC_GL_CONSTANT(GL_FRAMEBUFFER_COMPLETE_OES,0x8CD5)
DYNAMIC_GL_CONSTANT(GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT_OES,0x8CD6)
DYNAMIC_GL_CONSTANT(GL_FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT_OES,0x8CD7)
DYNAMIC_GL_CONSTANT(GL_FRAMEBUFFER_INCOMPLETE_DIMENSIONS_OES,0x8CD9)
DYNAMIC_GL_CONSTANT(GL_FRAMEBUFFER_INCOMPLETE_FORMATS_OES,0x8CDA)
DYNAMIC_GL_CONSTANT(GL_FRAMEBUFFER_UNSUPPORTED_OES,0x8CDD)
DYNAMIC_GL_CONSTANT(GL_FRAMEBUFFER_BINDING_OES,0x8CA6)
DYNAMIC_GL_CONSTANT(GL_RENDERBUFFER_BINDING_OES,0x8CA7)
DYNAMIC_GL_CONSTANT(GL_MAX_RENDERBUFFER_SIZE_OES,0x84E8)
DYNAMIC_GL_CONSTANT(GL_INVALID_FRAMEBUFFER_OPERATION_OES,0x0506)
DYNAMIC_GL_FUNCTION(DYNAMIC_GL_TYPE(GLboolean),IsRenderbufferOES,(DYNAMIC_GL_TYPE(GLuint) renderbuffer),(renderbuffer))
DYNAMIC_GL_FUNCTION_V(BindRenderbufferOES,(DYNAMIC_GL_TYPE(GLenum) target , DYNAMIC_GL_TYPE(GLuint) renderbuffer),(target , renderbuffer))
DYNAMIC_GL_FUNCTION_V(DeleteRenderbuffersOES,(DYNAMIC_GL_TYPE(GLsizei) n , const DYNAMIC_GL_TYPE(GLuint) * renderbuffers),(n , renderbuffers))
DYNAMIC_GL_FUNCTION_V(GenRenderbuffersOES,(DYNAMIC_GL_TYPE(GLsizei) n , DYNAMIC_GL_TYPE(GLuint) * renderbuffers),(n , renderbuffers))
DYNAMIC_GL_FUNCTION_V(RenderbufferStorageOES,(DYNAMIC_GL_TYPE(GLenum) target , DYNAMIC_GL_TYPE(GLenum) internalformat , DYNAMIC_GL_TYPE(GLsizei) width , DYNAMIC_GL_TYPE(GLsizei) height),(target , internalformat , width , height))
DYNAMIC_GL_FUNCTION_V(GetRenderbufferParameterivOES,(DYNAMIC_GL_TYPE(GLenum) target , DYNAMIC_GL_TYPE(GLenum) pname , DYNAMIC_GL_TYPE(GLint) * params),(target , pname , params))
DYNAMIC_GL_FUNCTION(DYNAMIC_GL_TYPE(GLboolean),IsFramebufferOES,(DYNAMIC_GL_TYPE(GLuint) framebuffer),(framebuffer))
DYNAMIC_GL_FUNCTION_V(BindFramebufferOES,(DYNAMIC_GL_TYPE(GLenum) target , DYNAMIC_GL_TYPE(GLuint) framebuffer),(target , framebuffer))
DYNAMIC_GL_FUNCTION_V(DeleteFramebuffersOES,(DYNAMIC_GL_TYPE(GLsizei) n , const DYNAMIC_GL_TYPE(GLuint) * framebuffers),(n , framebuffers))
DYNAMIC_GL_FUNCTION_V(GenFramebuffersOES,(DYNAMIC_GL_TYPE(GLsizei) n , DYNAMIC_GL_TYPE(GLuint) * framebuffers),(n , framebuffers))
DYNAMIC_GL_FUNCTION(DYNAMIC_GL_TYPE(GLenum),CheckFramebufferStatusOES,(DYNAMIC_GL_TYPE(GLenum) target),(target))
DYNAMIC_GL_FUNCTION_V(FramebufferRenderbufferOES,(DYNAMIC_GL_TYPE(GLenum) target , DYNAMIC_GL_TYPE(GLenum) attachment , DYNAMIC_GL_TYPE(GLenum) renderbuffertarget , DYNAMIC_GL_TYPE(GLuint) renderbuffer),(target , attachment , renderbuffertarget , renderbuffer))
DYNAMIC_GL_FUNCTION_V(FramebufferTexture2DOES,(DYNAMIC_GL_TYPE(GLenum) target , DYNAMIC_GL_TYPE(GLenum) attachment , DYNAMIC_GL_TYPE(GLenum) textarget , DYNAMIC_GL_TYPE(GLuint) texture , DYNAMIC_GL_TYPE(GLint) level),(target , attachment , textarget , texture , level))
DYNAMIC_GL_FUNCTION_V(GetFramebufferAttachmentParameterivOES,(DYNAMIC_GL_TYPE(GLenum) target , DYNAMIC_GL_TYPE(GLenum) attachment , DYNAMIC_GL_TYPE(GLenum) pname , DYNAMIC_GL_TYPE(GLint) * params),(target , attachment , pname , params))
DYNAMIC_GL_FUNCTION_V(GenerateMipmapOES,(DYNAMIC_GL_TYPE(GLenum) target),(target))
#endif /*USE_DYNAMIC_GL_OES_framebuffer_object*/

/*APPLE_copy_texture_levels*/
#ifdef USE_DYNAMIC_GL_APPLE_copy_texture_levels
DYNAMIC_GL_FEATURE(APPLE_copy_texture_levels)
DYNAMIC_GL_FUNCTION_V(CopyTextureLevelsAPPLE,(DYNAMIC_GL_TYPE(GLuint) destinationTexture , DYNAMIC_GL_TYPE(GLuint) sourceTexture , DYNAMIC_GL_TYPE(GLint) sourceBaseLevel , DYNAMIC_GL_TYPE(GLsizei) sourceLevelCount),(destinationTexture , sourceTexture , sourceBaseLevel , sourceLevelCount))
#endif /*USE_DYNAMIC_GL_APPLE_copy_texture_levels*/

/*AMD_compressed_3DC_texture*/
#ifdef USE_DYNAMIC_GL_AMD_compressed_3DC_texture
DYNAMIC_GL_FEATURE(AMD_compressed_3DC_texture)
DYNAMIC_GL_CONSTANT(GL_3DC_X_AMD,0x87F9)
DYNAMIC_GL_CONSTANT(GL_3DC_XY_AMD,0x87FA)
#endif /*USE_DYNAMIC_GL_AMD_compressed_3DC_texture*/

/*IMG_read_format*/
#ifdef USE_DYNAMIC_GL_IMG_read_format
DYNAMIC_GL_FEATURE(IMG_read_format)
DYNAMIC_GL_CONSTANT(GL_BGRA_IMG,0x80E1)
DYNAMIC_GL_CONSTANT(GL_UNSIGNED_SHORT_4_4_4_4_REV_IMG,0x8365)
#endif /*USE_DYNAMIC_GL_IMG_read_format*/

/*OES_EGL_image_external*/
#ifdef USE_DYNAMIC_GL_OES_EGL_image_external
DYNAMIC_GL_FEATURE(OES_EGL_image_external)
DYNAMIC_GL_CONSTANT(GL_TEXTURE_EXTERNAL_OES,0x8D65)
DYNAMIC_GL_CONSTANT(GL_TEXTURE_BINDING_EXTERNAL_OES,0x8D67)
DYNAMIC_GL_CONSTANT(GL_REQUIRED_TEXTURE_IMAGE_UNITS_OES,0x8D68)
#endif /*USE_DYNAMIC_GL_OES_EGL_image_external*/

/*OES_compressed_ETC1_RGB8_texture*/
#ifdef USE_DYNAMIC_GL_OES_compressed_ETC1_RGB8_texture
DYNAMIC_GL_FEATURE(OES_compressed_ETC1_RGB8_texture)
DYNAMIC_GL_CONSTANT(GL_ETC1_RGB8_OES,0x8D64)
#endif /*USE_DYNAMIC_GL_OES_compressed_ETC1_RGB8_texture*/

/*OES_depth24*/
#ifdef USE_DYNAMIC_GL_OES_depth24
DYNAMIC_GL_FEATURE(OES_depth24)
DYNAMIC_GL_CONSTANT(GL_DEPTH_COMPONENT24_OES,0x81A6)
#endif /*USE_DYNAMIC_GL_OES_depth24*/

/*IMG_texture_env_enhanced_fixed_function*/
#ifdef USE_DYNAMIC_GL_IMG_texture_env_enhanced_fixed_function
DYNAMIC_GL_FEATURE(IMG_texture_env_enhanced_fixed_function)
DYNAMIC_GL_CONSTANT(GL_MODULATE_COLOR_IMG,0x8C04)
DYNAMIC_GL_CONSTANT(GL_RECIP_ADD_SIGNED_ALPHA_IMG,0x8C05)
DYNAMIC_GL_CONSTANT(GL_TEXTURE_ALPHA_MODULATE_IMG,0x8C06)
DYNAMIC_GL_CONSTANT(GL_FACTOR_ALPHA_MODULATE_IMG,0x8C07)
DYNAMIC_GL_CONSTANT(GL_FRAGMENT_ALPHA_MODULATE_IMG,0x8C08)
DYNAMIC_GL_CONSTANT(GL_ADD_BLEND_IMG,0x8C09)
DYNAMIC_GL_CONSTANT(GL_DOT3_RGBA_IMG,0x86AF)
#endif /*USE_DYNAMIC_GL_IMG_texture_env_enhanced_fixed_function*/

/*OES_element_index_uint*/
#ifdef USE_DYNAMIC_GL_OES_element_index_uint
DYNAMIC_GL_FEATURE(OES_element_index_uint)
DYNAMIC_GL_CONSTANT(GL_UNSIGNED_INT,0x1405)
#endif /*USE_DYNAMIC_GL_OES_element_index_uint*/

/*QCOM_writeonly_rendering*/
#ifdef USE_DYNAMIC_GL_QCOM_writeonly_rendering
DYNAMIC_GL_FEATURE(QCOM_writeonly_rendering)
DYNAMIC_GL_CONSTANT(GL_WRITEONLY_RENDERING_QCOM,0x8823)
#endif /*USE_DYNAMIC_GL_QCOM_writeonly_rendering*/

/*ARM_rgba8*/
#ifdef USE_DYNAMIC_GL_ARM_rgba8
DYNAMIC_GL_FEATURE(ARM_rgba8)
#endif /*USE_DYNAMIC_GL_ARM_rgba8*/

/*QCOM_tiled_rendering*/
#ifdef USE_DYNAMIC_GL_QCOM_tiled_rendering
DYNAMIC_GL_FEATURE(QCOM_tiled_rendering)
DYNAMIC_GL_CONSTANT(GL_COLOR_BUFFER_BIT0_QCOM,0x00000001)
DYNAMIC_GL_CONSTANT(GL_COLOR_BUFFER_BIT1_QCOM,0x00000002)
DYNAMIC_GL_CONSTANT(GL_COLOR_BUFFER_BIT2_QCOM,0x00000004)
DYNAMIC_GL_CONSTANT(GL_COLOR_BUFFER_BIT3_QCOM,0x00000008)
DYNAMIC_GL_CONSTANT(GL_COLOR_BUFFER_BIT4_QCOM,0x00000010)
DYNAMIC_GL_CONSTANT(GL_COLOR_BUFFER_BIT5_QCOM,0x00000020)
DYNAMIC_GL_CONSTANT(GL_COLOR_BUFFER_BIT6_QCOM,0x00000040)
DYNAMIC_GL_CONSTANT(GL_COLOR_BUFFER_BIT7_QCOM,0x00000080)
DYNAMIC_GL_CONSTANT(GL_DEPTH_BUFFER_BIT0_QCOM,0x00000100)
DYNAMIC_GL_CONSTANT(GL_DEPTH_BUFFER_BIT1_QCOM,0x00000200)
DYNAMIC_GL_CONSTANT(GL_DEPTH_BUFFER_BIT2_QCOM,0x00000400)
DYNAMIC_GL_CONSTANT(GL_DEPTH_BUFFER_BIT3_QCOM,0x00000800)
DYNAMIC_GL_CONSTANT(GL_DEPTH_BUFFER_BIT4_QCOM,0x00001000)
DYNAMIC_GL_CONSTANT(GL_DEPTH_BUFFER_BIT5_QCOM,0x00002000)
DYNAMIC_GL_CONSTANT(GL_DEPTH_BUFFER_BIT6_QCOM,0x00004000)
DYNAMIC_GL_CONSTANT(GL_DEPTH_BUFFER_BIT7_QCOM,0x00008000)
DYNAMIC_GL_CONSTANT(GL_STENCIL_BUFFER_BIT0_QCOM,0x00010000)
DYNAMIC_GL_CONSTANT(GL_STENCIL_BUFFER_BIT1_QCOM,0x00020000)
DYNAMIC_GL_CONSTANT(GL_STENCIL_BUFFER_BIT2_QCOM,0x00040000)
DYNAMIC_GL_CONSTANT(GL_STENCIL_BUFFER_BIT3_QCOM,0x00080000)
DYNAMIC_GL_CONSTANT(GL_STENCIL_BUFFER_BIT4_QCOM,0x00100000)
DYNAMIC_GL_CONSTANT(GL_STENCIL_BUFFER_BIT5_QCOM,0x00200000)
DYNAMIC_GL_CONSTANT(GL_STENCIL_BUFFER_BIT6_QCOM,0x00400000)
DYNAMIC_GL_CONSTANT(GL_STENCIL_BUFFER_BIT7_QCOM,0x00800000)
DYNAMIC_GL_CONSTANT(GL_MULTISAMPLE_BUFFER_BIT0_QCOM,0x01000000)
DYNAMIC_GL_CONSTANT(GL_MULTISAMPLE_BUFFER_BIT1_QCOM,0x02000000)
DYNAMIC_GL_CONSTANT(GL_MULTISAMPLE_BUFFER_BIT2_QCOM,0x04000000)
DYNAMIC_GL_CONSTANT(GL_MULTISAMPLE_BUFFER_BIT3_QCOM,0x08000000)
DYNAMIC_GL_CONSTANT(GL_MULTISAMPLE_BUFFER_BIT4_QCOM,0x10000000)
DYNAMIC_GL_CONSTANT(GL_MULTISAMPLE_BUFFER_BIT5_QCOM,0x20000000)
DYNAMIC_GL_CONSTANT(GL_MULTISAMPLE_BUFFER_BIT6_QCOM,0x40000000)
DYNAMIC_GL_CONSTANT(GL_MULTISAMPLE_BUFFER_BIT7_QCOM,0x80000000)
DYNAMIC_GL_FUNCTION_V(StartTilingQCOM,(DYNAMIC_GL_TYPE(GLuint) x , DYNAMIC_GL_TYPE(GLuint) y , DYNAMIC_GL_TYPE(GLuint) width , DYNAMIC_GL_TYPE(GLuint) height , DYNAMIC_GL_TYPE(GLbitfield) preserveMask),(x , y , width , height , preserveMask))
DYNAMIC_GL_FUNCTION_V(EndTilingQCOM,(DYNAMIC_GL_TYPE(GLbitfield) preserveMask),(preserveMask))
#endif /*USE_DYNAMIC_GL_QCOM_tiled_rendering*/

/*OES_rgb8_rgba8*/
#ifdef USE_DYNAMIC_GL_OES_rgb8_rgba8
DYNAMIC_GL_FEATURE(OES_rgb8_rgba8)
DYNAMIC_GL_CONSTANT(GL_RGB8_OES,0x8051)
DYNAMIC_GL_CONSTANT(GL_RGBA8_OES,0x8058)
#endif /*USE_DYNAMIC_GL_OES_rgb8_rgba8*/

/*OES_texture_cube_map*/
#ifdef USE_DYNAMIC_GL_OES_texture_cube_map
DYNAMIC_GL_FEATURE(OES_texture_cube_map)
DYNAMIC_GL_CONSTANT(GL_NORMAL_MAP_OES,0x8511)
DYNAMIC_GL_CONSTANT(GL_REFLECTION_MAP_OES,0x8512)
DYNAMIC_GL_CONSTANT(GL_TEXTURE_CUBE_MAP_OES,0x8513)
DYNAMIC_GL_CONSTANT(GL_TEXTURE_BINDING_CUBE_MAP_OES,0x8514)
DYNAMIC_GL_CONSTANT(GL_TEXTURE_CUBE_MAP_POSITIVE_X_OES,0x8515)
DYNAMIC_GL_CONSTANT(GL_TEXTURE_CUBE_MAP_NEGATIVE_X_OES,0x8516)
DYNAMIC_GL_CONSTANT(GL_TEXTURE_CUBE_MAP_POSITIVE_Y_OES,0x8517)
DYNAMIC_GL_CONSTANT(GL_TEXTURE_CUBE_MAP_NEGATIVE_Y_OES,0x8518)
DYNAMIC_GL_CONSTANT(GL_TEXTURE_CUBE_MAP_POSITIVE_Z_OES,0x8519)
DYNAMIC_GL_CONSTANT(GL_TEXTURE_CUBE_MAP_NEGATIVE_Z_OES,0x851A)
DYNAMIC_GL_CONSTANT(GL_MAX_CUBE_MAP_TEXTURE_SIZE_OES,0x851C)
DYNAMIC_GL_CONSTANT(GL_TEXTURE_GEN_MODE_OES,0x2500)
DYNAMIC_GL_CONSTANT(GL_TEXTURE_GEN_STR_OES,0x8D60)
DYNAMIC_GL_FUNCTION_V(TexGenfOES,(DYNAMIC_GL_TYPE(GLenum) coord , DYNAMIC_GL_TYPE(GLenum) pname , DYNAMIC_GL_TYPE(GLfloat) param),(coord , pname , param))
DYNAMIC_GL_FUNCTION_V(TexGenfvOES,(DYNAMIC_GL_TYPE(GLenum) coord , DYNAMIC_GL_TYPE(GLenum) pname , const DYNAMIC_GL_TYPE(GLfloat) * params),(coord , pname , params))
DYNAMIC_GL_FUNCTION_V(TexGeniOES,(DYNAMIC_GL_TYPE(GLenum) coord , DYNAMIC_GL_TYPE(GLenum) pname , DYNAMIC_GL_TYPE(GLint) param),(coord , pname , param))
DYNAMIC_GL_FUNCTION_V(TexGenivOES,(DYNAMIC_GL_TYPE(GLenum) coord , DYNAMIC_GL_TYPE(GLenum) pname , const DYNAMIC_GL_TYPE(GLint) * params),(coord , pname , params))
DYNAMIC_GL_FUNCTION_V(TexGenxOES,(DYNAMIC_GL_TYPE(GLenum) coord , DYNAMIC_GL_TYPE(GLenum) pname , DYNAMIC_GL_TYPE(GLfixed) param),(coord , pname , param))
DYNAMIC_GL_FUNCTION_V(TexGenxvOES,(DYNAMIC_GL_TYPE(GLenum) coord , DYNAMIC_GL_TYPE(GLenum) pname , const DYNAMIC_GL_TYPE(GLfixed) * params),(coord , pname , params))
DYNAMIC_GL_FUNCTION_V(GetTexGenfvOES,(DYNAMIC_GL_TYPE(GLenum) coord , DYNAMIC_GL_TYPE(GLenum) pname , DYNAMIC_GL_TYPE(GLfloat) * params),(coord , pname , params))
DYNAMIC_GL_FUNCTION_V(GetTexGenivOES,(DYNAMIC_GL_TYPE(GLenum) coord , DYNAMIC_GL_TYPE(GLenum) pname , DYNAMIC_GL_TYPE(GLint) * params),(coord , pname , params))
DYNAMIC_GL_FUNCTION_V(GetTexGenxvOES,(DYNAMIC_GL_TYPE(GLenum) coord , DYNAMIC_GL_TYPE(GLenum) pname , DYNAMIC_GL_TYPE(GLfixed) * params),(coord , pname , params))
#endif /*USE_DYNAMIC_GL_OES_texture_cube_map*/

/*AMD_compressed_ATC_texture*/
#ifdef USE_DYNAMIC_GL_AMD_compressed_ATC_texture
DYNAMIC_GL_FEATURE(AMD_compressed_ATC_texture)
DYNAMIC_GL_CONSTANT(GL_ATC_RGB_AMD,0x8C92)
DYNAMIC_GL_CONSTANT(GL_ATC_RGBA_EXPLICIT_ALPHA_AMD,0x8C93)
DYNAMIC_GL_CONSTANT(GL_ATC_RGBA_INTERPOLATED_ALPHA_AMD,0x87EE)
#endif /*USE_DYNAMIC_GL_AMD_compressed_ATC_texture*/

/*OES_blend_func_separate*/
#ifdef USE_DYNAMIC_GL_OES_blend_func_separate
DYNAMIC_GL_FEATURE(OES_blend_func_separate)
DYNAMIC_GL_CONSTANT(GL_BLEND_DST_RGB_OES,0x80C8)
DYNAMIC_GL_CONSTANT(GL_BLEND_SRC_RGB_OES,0x80C9)
DYNAMIC_GL_CONSTANT(GL_BLEND_DST_ALPHA_OES,0x80CA)
DYNAMIC_GL_CONSTANT(GL_BLEND_SRC_ALPHA_OES,0x80CB)
DYNAMIC_GL_FUNCTION_V(BlendFuncSeparateOES,(DYNAMIC_GL_TYPE(GLenum) srcRGB , DYNAMIC_GL_TYPE(GLenum) dstRGB , DYNAMIC_GL_TYPE(GLenum) srcAlpha , DYNAMIC_GL_TYPE(GLenum) dstAlpha),(srcRGB , dstRGB , srcAlpha , dstAlpha))
#endif /*USE_DYNAMIC_GL_OES_blend_func_separate*/

/*QCOM_driver_control*/
#ifdef USE_DYNAMIC_GL_QCOM_driver_control
DYNAMIC_GL_FEATURE(QCOM_driver_control)
DYNAMIC_GL_FUNCTION_V(GetDriverControlsQCOM,(DYNAMIC_GL_TYPE(GLint) * num , DYNAMIC_GL_TYPE(GLsizei) size , DYNAMIC_GL_TYPE(GLuint) * driverControls),(num , size , driverControls))
DYNAMIC_GL_FUNCTION_V(GetDriverControlStringQCOM,(DYNAMIC_GL_TYPE(GLuint) driverControl , DYNAMIC_GL_TYPE(GLsizei) bufSize , DYNAMIC_GL_TYPE(GLsizei) * length , DYNAMIC_GL_TYPE(GLchar) * driverControlString),(driverControl , bufSize , length , driverControlString))
DYNAMIC_GL_FUNCTION_V(EnableDriverControlQCOM,(DYNAMIC_GL_TYPE(GLuint) driverControl),(driverControl))
DYNAMIC_GL_FUNCTION_V(DisableDriverControlQCOM,(DYNAMIC_GL_TYPE(GLuint) driverControl),(driverControl))
#endif /*USE_DYNAMIC_GL_QCOM_driver_control*/

/*EXT_multisampled_render_to_texture*/
#ifdef USE_DYNAMIC_GL_EXT_multisampled_render_to_texture
DYNAMIC_GL_FEATURE(EXT_multisampled_render_to_texture)
DYNAMIC_GL_CONSTANT(GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_SAMPLES_EXT,0x8D6C)
DYNAMIC_GL_CONSTANT(GL_RENDERBUFFER_SAMPLES_EXT,0x8CAB)
DYNAMIC_GL_CONSTANT(GL_FRAMEBUFFER_INCOMPLETE_MULTISAMPLE_EXT,0x8D56)
DYNAMIC_GL_CONSTANT(GL_MAX_SAMPLES_EXT,0x8D57)
DYNAMIC_GL_FUNCTION_V(RenderbufferStorageMultisampleEXT,(DYNAMIC_GL_TYPE(GLenum) target , DYNAMIC_GL_TYPE(GLsizei) samples , DYNAMIC_GL_TYPE(GLenum) internalformat , DYNAMIC_GL_TYPE(GLsizei) width , DYNAMIC_GL_TYPE(GLsizei) height),(target , samples , internalformat , width , height))
DYNAMIC_GL_FUNCTION_V(FramebufferTexture2DMultisampleEXT,(DYNAMIC_GL_TYPE(GLenum) target , DYNAMIC_GL_TYPE(GLenum) attachment , DYNAMIC_GL_TYPE(GLenum) textarget , DYNAMIC_GL_TYPE(GLuint) texture , DYNAMIC_GL_TYPE(GLint) level , DYNAMIC_GL_TYPE(GLsizei) samples),(target , attachment , textarget , texture , level , samples))
#endif /*USE_DYNAMIC_GL_EXT_multisampled_render_to_texture*/

/*EXT_texture_storage*/
#ifdef USE_DYNAMIC_GL_EXT_texture_storage
DYNAMIC_GL_FEATURE(EXT_texture_storage)
DYNAMIC_GL_CONSTANT(GL_TEXTURE_IMMUTABLE_FORMAT_EXT,0x912F)
DYNAMIC_GL_CONSTANT(GL_ALPHA8_EXT,0x803C)
DYNAMIC_GL_CONSTANT(GL_LUMINANCE8_EXT,0x8040)
DYNAMIC_GL_CONSTANT(GL_LUMINANCE8_ALPHA8_EXT,0x8045)
DYNAMIC_GL_CONSTANT(GL_RGBA32F_EXT,0x8814)
DYNAMIC_GL_CONSTANT(GL_RGB32F_EXT,0x8815)
DYNAMIC_GL_CONSTANT(GL_ALPHA32F_EXT,0x8816)
DYNAMIC_GL_CONSTANT(GL_LUMINANCE32F_EXT,0x8818)
DYNAMIC_GL_CONSTANT(GL_LUMINANCE_ALPHA32F_EXT,0x8819)
DYNAMIC_GL_CONSTANT(GL_RGB16F_EXT,0x881B)
DYNAMIC_GL_CONSTANT(GL_ALPHA16F_EXT,0x881C)
DYNAMIC_GL_CONSTANT(GL_LUMINANCE16F_EXT,0x881E)
DYNAMIC_GL_CONSTANT(GL_LUMINANCE_ALPHA16F_EXT,0x881F)
DYNAMIC_GL_CONSTANT(GL_RGB10_A2_EXT,0x8059)
DYNAMIC_GL_CONSTANT(GL_RGB10_EXT,0x8052)
DYNAMIC_GL_CONSTANT(GL_BGRA8_EXT,0x93A1)
DYNAMIC_GL_FUNCTION_V(TexStorage1DEXT,(DYNAMIC_GL_TYPE(GLenum) target , DYNAMIC_GL_TYPE(GLsizei) levels , DYNAMIC_GL_TYPE(GLenum) internalformat , DYNAMIC_GL_TYPE(GLsizei) width),(target , levels , internalformat , width))
DYNAMIC_GL_FUNCTION_V(TexStorage2DEXT,(DYNAMIC_GL_TYPE(GLenum) target , DYNAMIC_GL_TYPE(GLsizei) levels , DYNAMIC_GL_TYPE(GLenum) internalformat , DYNAMIC_GL_TYPE(GLsizei) width , DYNAMIC_GL_TYPE(GLsizei) height),(target , levels , internalformat , width , height))
DYNAMIC_GL_FUNCTION_V(TexStorage3DEXT,(DYNAMIC_GL_TYPE(GLenum) target , DYNAMIC_GL_TYPE(GLsizei) levels , DYNAMIC_GL_TYPE(GLenum) internalformat , DYNAMIC_GL_TYPE(GLsizei) width , DYNAMIC_GL_TYPE(GLsizei) height , DYNAMIC_GL_TYPE(GLsizei) depth),(target , levels , internalformat , width , height , depth))
DYNAMIC_GL_FUNCTION_V(TextureStorage1DEXT,(DYNAMIC_GL_TYPE(GLuint) texture , DYNAMIC_GL_TYPE(GLenum) target , DYNAMIC_GL_TYPE(GLsizei) levels , DYNAMIC_GL_TYPE(GLenum) internalformat , DYNAMIC_GL_TYPE(GLsizei) width),(texture , target , levels , internalformat , width))
DYNAMIC_GL_FUNCTION_V(TextureStorage2DEXT,(DYNAMIC_GL_TYPE(GLuint) texture , DYNAMIC_GL_TYPE(GLenum) target , DYNAMIC_GL_TYPE(GLsizei) levels , DYNAMIC_GL_TYPE(GLenum) internalformat , DYNAMIC_GL_TYPE(GLsizei) width , DYNAMIC_GL_TYPE(GLsizei) height),(texture , target , levels , internalformat , width , height))
DYNAMIC_GL_FUNCTION_V(TextureStorage3DEXT,(DYNAMIC_GL_TYPE(GLuint) texture , DYNAMIC_GL_TYPE(GLenum) target , DYNAMIC_GL_TYPE(GLsizei) levels , DYNAMIC_GL_TYPE(GLenum) internalformat , DYNAMIC_GL_TYPE(GLsizei) width , DYNAMIC_GL_TYPE(GLsizei) height , DYNAMIC_GL_TYPE(GLsizei) depth),(texture , target , levels , internalformat , width , height , depth))
#endif /*USE_DYNAMIC_GL_EXT_texture_storage*/

/*OES_stencil8*/
#ifdef USE_DYNAMIC_GL_OES_stencil8
DYNAMIC_GL_FEATURE(OES_stencil8)
DYNAMIC_GL_CONSTANT(GL_STENCIL_INDEX8_OES,0x8D48)
#endif /*USE_DYNAMIC_GL_OES_stencil8*/

/*APPLE_framebuffer_multisample*/
#ifdef USE_DYNAMIC_GL_APPLE_framebuffer_multisample
DYNAMIC_GL_FEATURE(APPLE_framebuffer_multisample)
DYNAMIC_GL_CONSTANT(GL_RENDERBUFFER_SAMPLES_APPLE,0x8CAB)
DYNAMIC_GL_CONSTANT(GL_FRAMEBUFFER_INCOMPLETE_MULTISAMPLE_APPLE,0x8D56)
DYNAMIC_GL_CONSTANT(GL_MAX_SAMPLES_APPLE,0x8D57)
DYNAMIC_GL_CONSTANT(GL_READ_FRAMEBUFFER_APPLE,0x8CA8)
DYNAMIC_GL_CONSTANT(GL_DRAW_FRAMEBUFFER_APPLE,0x8CA9)
DYNAMIC_GL_CONSTANT(GL_DRAW_FRAMEBUFFER_BINDING_APPLE,0x8CA6)
DYNAMIC_GL_CONSTANT(GL_READ_FRAMEBUFFER_BINDING_APPLE,0x8CAA)
DYNAMIC_GL_FUNCTION_V(RenderbufferStorageMultisampleAPPLE,(DYNAMIC_GL_TYPE(GLenum) target , DYNAMIC_GL_TYPE(GLsizei) samples , DYNAMIC_GL_TYPE(GLenum) internalformat , DYNAMIC_GL_TYPE(GLsizei) width , DYNAMIC_GL_TYPE(GLsizei) height),(target , samples , internalformat , width , height))
DYNAMIC_GL_FUNCTION_V(ResolveMultisampleFramebufferAPPLE,(),())
#endif /*USE_DYNAMIC_GL_APPLE_framebuffer_multisample*/

/*OES_extended_matrix_palette*/
#ifdef USE_DYNAMIC_GL_OES_extended_matrix_palette
DYNAMIC_GL_FEATURE(OES_extended_matrix_palette)
#endif /*USE_DYNAMIC_GL_OES_extended_matrix_palette*/

/*APPLE_texture_format_BGRA8888*/
#ifdef USE_DYNAMIC_GL_APPLE_texture_format_BGRA8888
DYNAMIC_GL_FEATURE(APPLE_texture_format_BGRA8888)
DYNAMIC_GL_CONSTANT(GL_BGRA_EXT,0x80E1)
#endif /*USE_DYNAMIC_GL_APPLE_texture_format_BGRA8888*/

/*IMG_user_clip_plane*/
#ifdef USE_DYNAMIC_GL_IMG_user_clip_plane
DYNAMIC_GL_FEATURE(IMG_user_clip_plane)
DYNAMIC_GL_CONSTANT(GL_CLIP_PLANE0_IMG,0x3000)
DYNAMIC_GL_CONSTANT(GL_CLIP_PLANE1_IMG,0x3001)
DYNAMIC_GL_CONSTANT(GL_CLIP_PLANE2_IMG,0x3002)
DYNAMIC_GL_CONSTANT(GL_CLIP_PLANE3_IMG,0x3003)
DYNAMIC_GL_CONSTANT(GL_CLIP_PLANE4_IMG,0x3004)
DYNAMIC_GL_CONSTANT(GL_CLIP_PLANE5_IMG,0x3005)
DYNAMIC_GL_CONSTANT(GL_MAX_CLIP_PLANES_IMG,0x0D32)
DYNAMIC_GL_FUNCTION_V(ClipPlanefIMG,(DYNAMIC_GL_TYPE(GLenum) p , const DYNAMIC_GL_TYPE(GLfloat) * eqn),(p , eqn))
DYNAMIC_GL_FUNCTION_V(ClipPlanexIMG,(DYNAMIC_GL_TYPE(GLenum) p , const DYNAMIC_GL_TYPE(GLfixed) * eqn),(p , eqn))
#endif /*USE_DYNAMIC_GL_IMG_user_clip_plane*/

/*QCOM_perfmon_global_mode*/
#ifdef USE_DYNAMIC_GL_QCOM_perfmon_global_mode
DYNAMIC_GL_FEATURE(QCOM_perfmon_global_mode)
DYNAMIC_GL_CONSTANT(GL_PERFMON_GLOBAL_MODE_QCOM,0x8FA0)
#endif /*USE_DYNAMIC_GL_QCOM_perfmon_global_mode*/

/*APPLE_texture_2D_limited_npot*/
#ifdef USE_DYNAMIC_GL_APPLE_texture_2D_limited_npot
DYNAMIC_GL_FEATURE(APPLE_texture_2D_limited_npot)
#endif /*USE_DYNAMIC_GL_APPLE_texture_2D_limited_npot*/

/*OES_depth32*/
#ifdef USE_DYNAMIC_GL_OES_depth32
DYNAMIC_GL_FEATURE(OES_depth32)
DYNAMIC_GL_CONSTANT(GL_DEPTH_COMPONENT32_OES,0x81A7)
#endif /*USE_DYNAMIC_GL_OES_depth32*/

/*IMG_texture_compression_pvrtc*/
#ifdef USE_DYNAMIC_GL_IMG_texture_compression_pvrtc
DYNAMIC_GL_FEATURE(IMG_texture_compression_pvrtc)
DYNAMIC_GL_CONSTANT(GL_COMPRESSED_RGB_PVRTC_4BPPV1_IMG,0x8C00)
DYNAMIC_GL_CONSTANT(GL_COMPRESSED_RGB_PVRTC_2BPPV1_IMG,0x8C01)
DYNAMIC_GL_CONSTANT(GL_COMPRESSED_RGBA_PVRTC_4BPPV1_IMG,0x8C02)
DYNAMIC_GL_CONSTANT(GL_COMPRESSED_RGBA_PVRTC_2BPPV1_IMG,0x8C03)
#endif /*USE_DYNAMIC_GL_IMG_texture_compression_pvrtc*/

/*OES_single_precision*/
#ifdef USE_DYNAMIC_GL_OES_single_precision
DYNAMIC_GL_FEATURE(OES_single_precision)
DYNAMIC_GL_FUNCTION_V(DepthRangefOES,(DYNAMIC_GL_TYPE(GLclampf) zNear , DYNAMIC_GL_TYPE(GLclampf) zFar),(zNear , zFar))
DYNAMIC_GL_FUNCTION_V(FrustumfOES,(DYNAMIC_GL_TYPE(GLfloat) left , DYNAMIC_GL_TYPE(GLfloat) right , DYNAMIC_GL_TYPE(GLfloat) bottom , DYNAMIC_GL_TYPE(GLfloat) top , DYNAMIC_GL_TYPE(GLfloat) zNear , DYNAMIC_GL_TYPE(GLfloat) zFar),(left , right , bottom , top , zNear , zFar))
DYNAMIC_GL_FUNCTION_V(OrthofOES,(DYNAMIC_GL_TYPE(GLfloat) left , DYNAMIC_GL_TYPE(GLfloat) right , DYNAMIC_GL_TYPE(GLfloat) bottom , DYNAMIC_GL_TYPE(GLfloat) top , DYNAMIC_GL_TYPE(GLfloat) zNear , DYNAMIC_GL_TYPE(GLfloat) zFar),(left , right , bottom , top , zNear , zFar))
DYNAMIC_GL_FUNCTION_V(ClipPlanefOES,(DYNAMIC_GL_TYPE(GLenum) plane , const DYNAMIC_GL_TYPE(GLfloat) * equation),(plane , equation))
DYNAMIC_GL_FUNCTION_V(ClearDepthfOES,(DYNAMIC_GL_TYPE(GLclampf) depth),(depth))
#endif /*USE_DYNAMIC_GL_OES_single_precision*/

/*OES_packed_depth_stencil*/
#ifdef USE_DYNAMIC_GL_OES_packed_depth_stencil
DYNAMIC_GL_FEATURE(OES_packed_depth_stencil)
DYNAMIC_GL_CONSTANT(GL_DEPTH_STENCIL_OES,0x84F9)
DYNAMIC_GL_CONSTANT(GL_UNSIGNED_INT_24_8_OES,0x84FA)
DYNAMIC_GL_CONSTANT(GL_DEPTH24_STENCIL8_OES,0x88F0)
#endif /*USE_DYNAMIC_GL_OES_packed_depth_stencil*/

/*EXT_discard_framebuffer*/
#ifdef USE_DYNAMIC_GL_EXT_discard_framebuffer
DYNAMIC_GL_FEATURE(EXT_discard_framebuffer)
DYNAMIC_GL_CONSTANT(GL_COLOR_EXT,0x1800)
DYNAMIC_GL_CONSTANT(GL_DEPTH_EXT,0x1801)
DYNAMIC_GL_CONSTANT(GL_STENCIL_EXT,0x1802)
DYNAMIC_GL_FUNCTION_V(DiscardFramebufferEXT,(DYNAMIC_GL_TYPE(GLenum) target , DYNAMIC_GL_TYPE(GLsizei) numAttachments , const DYNAMIC_GL_TYPE(GLenum) * attachments),(target , numAttachments , attachments))
#endif /*USE_DYNAMIC_GL_EXT_discard_framebuffer*/

/*OES_EGL_image*/
#ifdef USE_DYNAMIC_GL_OES_EGL_image
DYNAMIC_GL_FEATURE(OES_EGL_image)
DYNAMIC_GL_FUNCTION_V(EGLImageTargetTexture2DOES,(DYNAMIC_GL_TYPE(GLenum) target , DYNAMIC_GL_TYPE(GLeglImageOES) image),(target , image))
DYNAMIC_GL_FUNCTION_V(EGLImageTargetRenderbufferStorageOES,(DYNAMIC_GL_TYPE(GLenum) target , DYNAMIC_GL_TYPE(GLeglImageOES) image),(target , image))
#endif /*USE_DYNAMIC_GL_OES_EGL_image*/

/*APPLE_sync*/
#ifdef USE_DYNAMIC_GL_APPLE_sync
DYNAMIC_GL_FEATURE(APPLE_sync)
DYNAMIC_GL_TYPEDEF(khronos_int64_t,GLint64)
DYNAMIC_GL_TYPEDEF(khronos_uint64_t,GLuint64)
DYNAMIC_GL_CONSTANT(GL_SYNC_OBJECT_APPLE,0x8A53)
DYNAMIC_GL_CONSTANT(GL_MAX_SERVER_WAIT_TIMEOUT_APPLE,0x9111)
DYNAMIC_GL_CONSTANT(GL_OBJECT_TYPE_APPLE,0x9112)
DYNAMIC_GL_CONSTANT(GL_SYNC_CONDITION_APPLE,0x9113)
DYNAMIC_GL_CONSTANT(GL_SYNC_STATUS_APPLE,0x9114)
DYNAMIC_GL_CONSTANT(GL_SYNC_FLAGS_APPLE,0x9115)
DYNAMIC_GL_CONSTANT(GL_SYNC_FENCE_APPLE,0x9116)
DYNAMIC_GL_CONSTANT(GL_SYNC_GPU_COMMANDS_COMPLETE_APPLE,0x9117)
DYNAMIC_GL_CONSTANT(GL_UNSIGNALED_APPLE,0x9118)
DYNAMIC_GL_CONSTANT(GL_SIGNALED_APPLE,0x9119)
DYNAMIC_GL_CONSTANT(GL_ALREADY_SIGNALED_APPLE,0x911A)
DYNAMIC_GL_CONSTANT(GL_TIMEOUT_EXPIRED_APPLE,0x911B)
DYNAMIC_GL_CONSTANT(GL_CONDITION_SATISFIED_APPLE,0x911C)
DYNAMIC_GL_CONSTANT(GL_WAIT_FAILED_APPLE,0x911D)
DYNAMIC_GL_CONSTANT(GL_SYNC_FLUSH_COMMANDS_BIT_APPLE,0x00000001)
DYNAMIC_GL_CONSTANT(GL_TIMEOUT_IGNORED_APPLE,0xFFFFFFFFFFFFFFFF)
DYNAMIC_GL_FUNCTION(DYNAMIC_GL_TYPE(GLsync),FenceSyncAPPLE,(DYNAMIC_GL_TYPE(GLenum) condition , DYNAMIC_GL_TYPE(GLbitfield) flags),(condition , flags))
DYNAMIC_GL_FUNCTION(DYNAMIC_GL_TYPE(GLboolean),IsSyncAPPLE,(DYNAMIC_GL_TYPE(GLsync) sync),(sync))
DYNAMIC_GL_FUNCTION_V(DeleteSyncAPPLE,(DYNAMIC_GL_TYPE(GLsync) sync),(sync))
DYNAMIC_GL_FUNCTION(DYNAMIC_GL_TYPE(GLenum),ClientWaitSyncAPPLE,(DYNAMIC_GL_TYPE(GLsync) sync , DYNAMIC_GL_TYPE(GLbitfield) flags , DYNAMIC_GL_TYPE(GLuint64) timeout),(sync , flags , timeout))
DYNAMIC_GL_FUNCTION_V(WaitSyncAPPLE,(DYNAMIC_GL_TYPE(GLsync) sync , DYNAMIC_GL_TYPE(GLbitfield) flags , DYNAMIC_GL_TYPE(GLuint64) timeout),(sync , flags , timeout))
DYNAMIC_GL_FUNCTION_V(GetInteger64vAPPLE,(DYNAMIC_GL_TYPE(GLenum) pname , DYNAMIC_GL_TYPE(GLint64) * params),(pname , params))
DYNAMIC_GL_FUNCTION_V(GetSyncivAPPLE,(DYNAMIC_GL_TYPE(GLsync) sync , DYNAMIC_GL_TYPE(GLenum) pname , DYNAMIC_GL_TYPE(GLsizei) bufSize , DYNAMIC_GL_TYPE(GLsizei) * length , DYNAMIC_GL_TYPE(GLint) * values),(sync , pname , bufSize , length , values))
#endif /*USE_DYNAMIC_GL_APPLE_sync*/

/*EXT_sRGB*/
#ifdef USE_DYNAMIC_GL_EXT_sRGB
DYNAMIC_GL_FEATURE(EXT_sRGB)
DYNAMIC_GL_CONSTANT(GL_SRGB_EXT,0x8C40)
DYNAMIC_GL_CONSTANT(GL_SRGB_ALPHA_EXT,0x8C42)
DYNAMIC_GL_CONSTANT(GL_SRGB8_ALPHA8_EXT,0x8C43)
DYNAMIC_GL_CONSTANT(GL_FRAMEBUFFER_ATTACHMENT_COLOR_ENCODING_EXT,0x8210)
#endif /*USE_DYNAMIC_GL_EXT_sRGB*/

/*EXT_texture_filter_anisotropic*/
#ifdef USE_DYNAMIC_GL_EXT_texture_filter_anisotropic
DYNAMIC_GL_FEATURE(EXT_texture_filter_anisotropic)
DYNAMIC_GL_CONSTANT(GL_TEXTURE_MAX_ANISOTROPY_EXT,0x84FE)
DYNAMIC_GL_CONSTANT(GL_MAX_TEXTURE_MAX_ANISOTROPY_EXT,0x84FF)
#endif /*USE_DYNAMIC_GL_EXT_texture_filter_anisotropic*/

/*NV_fence*/
#ifdef USE_DYNAMIC_GL_NV_fence
DYNAMIC_GL_FEATURE(NV_fence)
DYNAMIC_GL_CONSTANT(GL_ALL_COMPLETED_NV,0x84F2)
DYNAMIC_GL_CONSTANT(GL_FENCE_STATUS_NV,0x84F3)
DYNAMIC_GL_CONSTANT(GL_FENCE_CONDITION_NV,0x84F4)
DYNAMIC_GL_FUNCTION_V(DeleteFencesNV,(DYNAMIC_GL_TYPE(GLsizei) n , const DYNAMIC_GL_TYPE(GLuint) * fences),(n , fences))
DYNAMIC_GL_FUNCTION_V(GenFencesNV,(DYNAMIC_GL_TYPE(GLsizei) n , DYNAMIC_GL_TYPE(GLuint) * fences),(n , fences))
DYNAMIC_GL_FUNCTION(DYNAMIC_GL_TYPE(GLboolean),IsFenceNV,(DYNAMIC_GL_TYPE(GLuint) fence),(fence))
DYNAMIC_GL_FUNCTION(DYNAMIC_GL_TYPE(GLboolean),TestFenceNV,(DYNAMIC_GL_TYPE(GLuint) fence),(fence))
DYNAMIC_GL_FUNCTION_V(GetFenceivNV,(DYNAMIC_GL_TYPE(GLuint) fence , DYNAMIC_GL_TYPE(GLenum) pname , DYNAMIC_GL_TYPE(GLint) * params),(fence , pname , params))
DYNAMIC_GL_FUNCTION_V(FinishFenceNV,(DYNAMIC_GL_TYPE(GLuint) fence),(fence))
DYNAMIC_GL_FUNCTION_V(SetFenceNV,(DYNAMIC_GL_TYPE(GLuint) fence , DYNAMIC_GL_TYPE(GLenum) condition),(fence , condition))
#endif /*USE_DYNAMIC_GL_NV_fence*/

/*OES_matrix_get*/
#ifdef USE_DYNAMIC_GL_OES_matrix_get
DYNAMIC_GL_FEATURE(OES_matrix_get)
DYNAMIC_GL_CONSTANT(GL_MODELVIEW_MATRIX_FLOAT_AS_INT_BITS_OES,0x898D)
DYNAMIC_GL_CONSTANT(GL_PROJECTION_MATRIX_FLOAT_AS_INT_BITS_OES,0x898E)
DYNAMIC_GL_CONSTANT(GL_TEXTURE_MATRIX_FLOAT_AS_INT_BITS_OES,0x898F)
#endif /*USE_DYNAMIC_GL_OES_matrix_get*/

/*OES_draw_texture*/
#ifdef USE_DYNAMIC_GL_OES_draw_texture
DYNAMIC_GL_FEATURE(OES_draw_texture)
DYNAMIC_GL_CONSTANT(GL_TEXTURE_CROP_RECT_OES,0x8B9D)
DYNAMIC_GL_FUNCTION_V(DrawTexsOES,(DYNAMIC_GL_TYPE(GLshort) x , DYNAMIC_GL_TYPE(GLshort) y , DYNAMIC_GL_TYPE(GLshort) z , DYNAMIC_GL_TYPE(GLshort) width , DYNAMIC_GL_TYPE(GLshort) height),(x , y , z , width , height))
DYNAMIC_GL_FUNCTION_V(DrawTexiOES,(DYNAMIC_GL_TYPE(GLint) x , DYNAMIC_GL_TYPE(GLint) y , DYNAMIC_GL_TYPE(GLint) z , DYNAMIC_GL_TYPE(GLint) width , DYNAMIC_GL_TYPE(GLint) height),(x , y , z , width , height))
DYNAMIC_GL_FUNCTION_V(DrawTexxOES,(DYNAMIC_GL_TYPE(GLfixed) x , DYNAMIC_GL_TYPE(GLfixed) y , DYNAMIC_GL_TYPE(GLfixed) z , DYNAMIC_GL_TYPE(GLfixed) width , DYNAMIC_GL_TYPE(GLfixed) height),(x , y , z , width , height))
DYNAMIC_GL_FUNCTION_V(DrawTexsvOES,(const DYNAMIC_GL_TYPE(GLshort) * coords),(coords))
DYNAMIC_GL_FUNCTION_V(DrawTexivOES,(const DYNAMIC_GL_TYPE(GLint) * coords),(coords))
DYNAMIC_GL_FUNCTION_V(DrawTexxvOES,(const DYNAMIC_GL_TYPE(GLfixed) * coords),(coords))
DYNAMIC_GL_FUNCTION_V(DrawTexfOES,(DYNAMIC_GL_TYPE(GLfloat) x , DYNAMIC_GL_TYPE(GLfloat) y , DYNAMIC_GL_TYPE(GLfloat) z , DYNAMIC_GL_TYPE(GLfloat) width , DYNAMIC_GL_TYPE(GLfloat) height),(x , y , z , width , height))
DYNAMIC_GL_FUNCTION_V(DrawTexfvOES,(const DYNAMIC_GL_TYPE(GLfloat) * coords),(coords))
#endif /*USE_DYNAMIC_GL_OES_draw_texture*/

/*EXT_robustness*/
#ifdef USE_DYNAMIC_GL_EXT_robustness
DYNAMIC_GL_FEATURE(EXT_robustness)
DYNAMIC_GL_CONSTANT(GL_GUILTY_CONTEXT_RESET_EXT,0x8253)
DYNAMIC_GL_CONSTANT(GL_INNOCENT_CONTEXT_RESET_EXT,0x8254)
DYNAMIC_GL_CONSTANT(GL_UNKNOWN_CONTEXT_RESET_EXT,0x8255)
DYNAMIC_GL_CONSTANT(GL_CONTEXT_ROBUST_ACCESS_EXT,0x90F3)
DYNAMIC_GL_CONSTANT(GL_RESET_NOTIFICATION_STRATEGY_EXT,0x8256)
DYNAMIC_GL_CONSTANT(GL_LOSE_CONTEXT_ON_RESET_EXT,0x8252)
DYNAMIC_GL_CONSTANT(GL_NO_RESET_NOTIFICATION_EXT,0x8261)
DYNAMIC_GL_FUNCTION(DYNAMIC_GL_TYPE(GLenum),GetGraphicsResetStatusEXT,(),())
DYNAMIC_GL_FUNCTION_V(ReadnPixelsEXT,(DYNAMIC_GL_TYPE(GLint) x , DYNAMIC_GL_TYPE(GLint) y , DYNAMIC_GL_TYPE(GLsizei) width , DYNAMIC_GL_TYPE(GLsizei) height , DYNAMIC_GL_TYPE(GLenum) format , DYNAMIC_GL_TYPE(GLenum) type , DYNAMIC_GL_TYPE(GLsizei) bufSize , DYNAMIC_GL_TYPE(GLvoid) * data),(x , y , width , height , format , type , bufSize , data))
DYNAMIC_GL_FUNCTION_V(GetnUniformfvEXT,(DYNAMIC_GL_TYPE(GLuint) program , DYNAMIC_GL_TYPE(GLint) location , DYNAMIC_GL_TYPE(GLsizei) bufSize , DYNAMIC_GL_TYPE(GLfloat) * params),(program , location , bufSize , params))
DYNAMIC_GL_FUNCTION_V(GetnUniformivEXT,(DYNAMIC_GL_TYPE(GLuint) program , DYNAMIC_GL_TYPE(GLint) location , DYNAMIC_GL_TYPE(GLsizei) bufSize , DYNAMIC_GL_TYPE(GLint) * params),(program , location , bufSize , params))
#endif /*USE_DYNAMIC_GL_EXT_robustness*/

/*OES_byte_coordinates*/
#ifdef USE_DYNAMIC_GL_OES_byte_coordinates
DYNAMIC_GL_FEATURE(OES_byte_coordinates)
#endif /*USE_DYNAMIC_GL_OES_byte_coordinates*/

/*QCOM_extended_get2*/
#ifdef USE_DYNAMIC_GL_QCOM_extended_get2
DYNAMIC_GL_FEATURE(QCOM_extended_get2)
DYNAMIC_GL_FUNCTION_V(ExtGetShadersQCOM,(DYNAMIC_GL_TYPE(GLuint) * shaders , DYNAMIC_GL_TYPE(GLint) maxShaders , DYNAMIC_GL_TYPE(GLint) * numShaders),(shaders , maxShaders , numShaders))
DYNAMIC_GL_FUNCTION_V(ExtGetProgramsQCOM,(DYNAMIC_GL_TYPE(GLuint) * programs , DYNAMIC_GL_TYPE(GLint) maxPrograms , DYNAMIC_GL_TYPE(GLint) * numPrograms),(programs , maxPrograms , numPrograms))
DYNAMIC_GL_FUNCTION(DYNAMIC_GL_TYPE(GLboolean),ExtIsProgramBinaryQCOM,(DYNAMIC_GL_TYPE(GLuint) program),(program))
DYNAMIC_GL_FUNCTION_V(ExtGetProgramBinarySourceQCOM,(DYNAMIC_GL_TYPE(GLuint) program , DYNAMIC_GL_TYPE(GLenum) shadertype , DYNAMIC_GL_TYPE(GLchar) * source , DYNAMIC_GL_TYPE(GLint) * length),(program , shadertype , source , length))
#endif /*USE_DYNAMIC_GL_QCOM_extended_get2*/

/*OES_stencil4*/
#ifdef USE_DYNAMIC_GL_OES_stencil4
DYNAMIC_GL_FEATURE(OES_stencil4)
DYNAMIC_GL_CONSTANT(GL_STENCIL_INDEX4_OES,0x8D47)
#endif /*USE_DYNAMIC_GL_OES_stencil4*/

/*OES_matrix_palette*/
#ifdef USE_DYNAMIC_GL_OES_matrix_palette
DYNAMIC_GL_FEATURE(OES_matrix_palette)
DYNAMIC_GL_CONSTANT(GL_MAX_VERTEX_UNITS_OES,0x86A4)
DYNAMIC_GL_CONSTANT(GL_MAX_PALETTE_MATRICES_OES,0x8842)
DYNAMIC_GL_CONSTANT(GL_MATRIX_PALETTE_OES,0x8840)
DYNAMIC_GL_CONSTANT(GL_MATRIX_INDEX_ARRAY_OES,0x8844)
DYNAMIC_GL_CONSTANT(GL_WEIGHT_ARRAY_OES,0x86AD)
DYNAMIC_GL_CONSTANT(GL_CURRENT_PALETTE_MATRIX_OES,0x8843)
DYNAMIC_GL_CONSTANT(GL_MATRIX_INDEX_ARRAY_SIZE_OES,0x8846)
DYNAMIC_GL_CONSTANT(GL_MATRIX_INDEX_ARRAY_TYPE_OES,0x8847)
DYNAMIC_GL_CONSTANT(GL_MATRIX_INDEX_ARRAY_STRIDE_OES,0x8848)
DYNAMIC_GL_CONSTANT(GL_MATRIX_INDEX_ARRAY_POINTER_OES,0x8849)
DYNAMIC_GL_CONSTANT(GL_MATRIX_INDEX_ARRAY_BUFFER_BINDING_OES,0x8B9E)
DYNAMIC_GL_CONSTANT(GL_WEIGHT_ARRAY_SIZE_OES,0x86AB)
DYNAMIC_GL_CONSTANT(GL_WEIGHT_ARRAY_TYPE_OES,0x86A9)
DYNAMIC_GL_CONSTANT(GL_WEIGHT_ARRAY_STRIDE_OES,0x86AA)
DYNAMIC_GL_CONSTANT(GL_WEIGHT_ARRAY_POINTER_OES,0x86AC)
DYNAMIC_GL_CONSTANT(GL_WEIGHT_ARRAY_BUFFER_BINDING_OES,0x889E)
DYNAMIC_GL_FUNCTION_V(CurrentPaletteMatrixOES,(DYNAMIC_GL_TYPE(GLuint) matrixpaletteindex),(matrixpaletteindex))
DYNAMIC_GL_FUNCTION_V(LoadPaletteFromModelViewMatrixOES,(),())
DYNAMIC_GL_FUNCTION_V(MatrixIndexPointerOES,(DYNAMIC_GL_TYPE(GLint) size , DYNAMIC_GL_TYPE(GLenum) type , DYNAMIC_GL_TYPE(GLsizei) stride , const DYNAMIC_GL_TYPE(GLvoid) * pointer),(size , type , stride , pointer))
DYNAMIC_GL_FUNCTION_V(WeightPointerOES,(DYNAMIC_GL_TYPE(GLint) size , DYNAMIC_GL_TYPE(GLenum) type , DYNAMIC_GL_TYPE(GLsizei) stride , const DYNAMIC_GL_TYPE(GLvoid) * pointer),(size , type , stride , pointer))
#endif /*USE_DYNAMIC_GL_OES_matrix_palette*/

/*QCOM_extended_get*/
#ifdef USE_DYNAMIC_GL_QCOM_extended_get
DYNAMIC_GL_FEATURE(QCOM_extended_get)
DYNAMIC_GL_CONSTANT(GL_TEXTURE_WIDTH_QCOM,0x8BD2)
DYNAMIC_GL_CONSTANT(GL_TEXTURE_HEIGHT_QCOM,0x8BD3)
DYNAMIC_GL_CONSTANT(GL_TEXTURE_DEPTH_QCOM,0x8BD4)
DYNAMIC_GL_CONSTANT(GL_TEXTURE_INTERNAL_FORMAT_QCOM,0x8BD5)
DYNAMIC_GL_CONSTANT(GL_TEXTURE_FORMAT_QCOM,0x8BD6)
DYNAMIC_GL_CONSTANT(GL_TEXTURE_TYPE_QCOM,0x8BD7)
DYNAMIC_GL_CONSTANT(GL_TEXTURE_IMAGE_VALID_QCOM,0x8BD8)
DYNAMIC_GL_CONSTANT(GL_TEXTURE_NUM_LEVELS_QCOM,0x8BD9)
DYNAMIC_GL_CONSTANT(GL_TEXTURE_TARGET_QCOM,0x8BDA)
DYNAMIC_GL_CONSTANT(GL_TEXTURE_OBJECT_VALID_QCOM,0x8BDB)
DYNAMIC_GL_CONSTANT(GL_STATE_RESTORE,0x8BDC)
DYNAMIC_GL_FUNCTION_V(ExtGetTexturesQCOM,(DYNAMIC_GL_TYPE(GLuint) * textures , DYNAMIC_GL_TYPE(GLint) maxTextures , DYNAMIC_GL_TYPE(GLint) * numTextures),(textures , maxTextures , numTextures))
DYNAMIC_GL_FUNCTION_V(ExtGetBuffersQCOM,(DYNAMIC_GL_TYPE(GLuint) * buffers , DYNAMIC_GL_TYPE(GLint) maxBuffers , DYNAMIC_GL_TYPE(GLint) * numBuffers),(buffers , maxBuffers , numBuffers))
DYNAMIC_GL_FUNCTION_V(ExtGetRenderbuffersQCOM,(DYNAMIC_GL_TYPE(GLuint) * renderbuffers , DYNAMIC_GL_TYPE(GLint) maxRenderbuffers , DYNAMIC_GL_TYPE(GLint) * numRenderbuffers),(renderbuffers , maxRenderbuffers , numRenderbuffers))
DYNAMIC_GL_FUNCTION_V(ExtGetFramebuffersQCOM,(DYNAMIC_GL_TYPE(GLuint) * framebuffers , DYNAMIC_GL_TYPE(GLint) maxFramebuffers , DYNAMIC_GL_TYPE(GLint) * numFramebuffers),(framebuffers , maxFramebuffers , numFramebuffers))
DYNAMIC_GL_FUNCTION_V(ExtGetTexLevelParameterivQCOM,(DYNAMIC_GL_TYPE(GLuint) texture , DYNAMIC_GL_TYPE(GLenum) face , DYNAMIC_GL_TYPE(GLint) level , DYNAMIC_GL_TYPE(GLenum) pname , DYNAMIC_GL_TYPE(GLint) * params),(texture , face , level , pname , params))
DYNAMIC_GL_FUNCTION_V(ExtTexObjectStateOverrideiQCOM,(DYNAMIC_GL_TYPE(GLenum) target , DYNAMIC_GL_TYPE(GLenum) pname , DYNAMIC_GL_TYPE(GLint) param),(target , pname , param))
DYNAMIC_GL_FUNCTION_V(ExtGetTexSubImageQCOM,(DYNAMIC_GL_TYPE(GLenum) target , DYNAMIC_GL_TYPE(GLint) level , DYNAMIC_GL_TYPE(GLint) xoffset , DYNAMIC_GL_TYPE(GLint) yoffset , DYNAMIC_GL_TYPE(GLint) zoffset , DYNAMIC_GL_TYPE(GLsizei) width , DYNAMIC_GL_TYPE(GLsizei) height , DYNAMIC_GL_TYPE(GLsizei) depth , DYNAMIC_GL_TYPE(GLenum) format , DYNAMIC_GL_TYPE(GLenum) type , DYNAMIC_GL_TYPE(GLvoid) * texels),(target , level , xoffset , yoffset , zoffset , width , height , depth , format , type , texels))
DYNAMIC_GL_FUNCTION_V(ExtGetBufferPointervQCOM,(DYNAMIC_GL_TYPE(GLenum) target , DYNAMIC_GL_TYPE(GLvoid) * p1),(target , p1))
#endif /*USE_DYNAMIC_GL_QCOM_extended_get*/

/*OES_vertex_array_object*/
#ifdef USE_DYNAMIC_GL_OES_vertex_array_object
DYNAMIC_GL_FEATURE(OES_vertex_array_object)
DYNAMIC_GL_CONSTANT(GL_VERTEX_ARRAY_BINDING_OES,0x85B5)
DYNAMIC_GL_FUNCTION_V(BindVertexArrayOES,(DYNAMIC_GL_TYPE(GLuint) array),(array))
DYNAMIC_GL_FUNCTION_V(DeleteVertexArraysOES,(DYNAMIC_GL_TYPE(GLsizei) n , const DYNAMIC_GL_TYPE(GLuint) * arrays),(n , arrays))
DYNAMIC_GL_FUNCTION_V(GenVertexArraysOES,(DYNAMIC_GL_TYPE(GLsizei) n , DYNAMIC_GL_TYPE(GLuint) * arrays),(n , arrays))
DYNAMIC_GL_FUNCTION(DYNAMIC_GL_TYPE(GLboolean),IsVertexArrayOES,(DYNAMIC_GL_TYPE(GLuint) array),(array))
#endif /*USE_DYNAMIC_GL_OES_vertex_array_object*/

/*OES_blend_subtract*/
#ifdef USE_DYNAMIC_GL_OES_blend_subtract
DYNAMIC_GL_FEATURE(OES_blend_subtract)
DYNAMIC_GL_CONSTANT(GL_BLEND_EQUATION_OES,0x8009)
DYNAMIC_GL_CONSTANT(GL_FUNC_ADD_OES,0x8006)
DYNAMIC_GL_CONSTANT(GL_FUNC_SUBTRACT_OES,0x800A)
DYNAMIC_GL_CONSTANT(GL_FUNC_REVERSE_SUBTRACT_OES,0x800B)
DYNAMIC_GL_FUNCTION_V(BlendEquationOES,(DYNAMIC_GL_TYPE(GLenum) mode),(mode))
#endif /*USE_DYNAMIC_GL_OES_blend_subtract*/

/*APPLE_texture_max_level*/
#ifdef USE_DYNAMIC_GL_APPLE_texture_max_level
DYNAMIC_GL_FEATURE(APPLE_texture_max_level)
DYNAMIC_GL_CONSTANT(GL_TEXTURE_MAX_LEVEL_APPLE,0x813D)
#endif /*USE_DYNAMIC_GL_APPLE_texture_max_level*/

/*OES_texture_env_crossbar*/
#ifdef USE_DYNAMIC_GL_OES_texture_env_crossbar
DYNAMIC_GL_FEATURE(OES_texture_env_crossbar)
#endif /*USE_DYNAMIC_GL_OES_texture_env_crossbar*/

/*OES_required_internalformat*/
#ifdef USE_DYNAMIC_GL_OES_required_internalformat
DYNAMIC_GL_FEATURE(OES_required_internalformat)
#endif /*USE_DYNAMIC_GL_OES_required_internalformat*/

/*OES_stencil1*/
#ifdef USE_DYNAMIC_GL_OES_stencil1
DYNAMIC_GL_FEATURE(OES_stencil1)
DYNAMIC_GL_CONSTANT(GL_STENCIL_INDEX1_OES,0x8D46)
#endif /*USE_DYNAMIC_GL_OES_stencil1*/

/*EXT_read_format_bgra*/
#ifdef USE_DYNAMIC_GL_EXT_read_format_bgra
DYNAMIC_GL_FEATURE(EXT_read_format_bgra)
DYNAMIC_GL_CONSTANT(GL_BGRA_EXT,0x80E1)
DYNAMIC_GL_CONSTANT(GL_UNSIGNED_SHORT_4_4_4_4_REV_EXT,0x8365)
DYNAMIC_GL_CONSTANT(GL_UNSIGNED_SHORT_1_5_5_5_REV_EXT,0x8366)
#endif /*USE_DYNAMIC_GL_EXT_read_format_bgra*/

/*EXT_blend_minmax*/
#ifdef USE_DYNAMIC_GL_EXT_blend_minmax
DYNAMIC_GL_FEATURE(EXT_blend_minmax)
DYNAMIC_GL_CONSTANT(GL_MIN_EXT,0x8007)
DYNAMIC_GL_CONSTANT(GL_MAX_EXT,0x8008)
#endif /*USE_DYNAMIC_GL_EXT_blend_minmax*/

/*OES_mapbuffer*/
#ifdef USE_DYNAMIC_GL_OES_mapbuffer
DYNAMIC_GL_FEATURE(OES_mapbuffer)
DYNAMIC_GL_CONSTANT(GL_WRITE_ONLY_OES,0x88B9)
DYNAMIC_GL_CONSTANT(GL_BUFFER_ACCESS_OES,0x88BB)
DYNAMIC_GL_CONSTANT(GL_BUFFER_MAPPED_OES,0x88BC)
DYNAMIC_GL_CONSTANT(GL_BUFFER_MAP_POINTER_OES,0x88BD)
DYNAMIC_GL_FUNCTION(DYNAMIC_GL_TYPE(GLboolean),UnmapBufferOES,(DYNAMIC_GL_TYPE(GLenum) target),(target))
DYNAMIC_GL_FUNCTION_V(GetBufferPointervOES,(DYNAMIC_GL_TYPE(GLenum) target , DYNAMIC_GL_TYPE(GLenum) pname , DYNAMIC_GL_TYPE(GLvoid) * p1),(target , pname , p1))
#endif /*USE_DYNAMIC_GL_OES_mapbuffer*/

/*OES_fixed_point*/
#ifdef USE_DYNAMIC_GL_OES_fixed_point
DYNAMIC_GL_FEATURE(OES_fixed_point)
DYNAMIC_GL_CONSTANT(GL_FIXED_OES,0x140C)
DYNAMIC_GL_FUNCTION_V(AlphaFuncxOES,(DYNAMIC_GL_TYPE(GLenum) func , DYNAMIC_GL_TYPE(GLclampx) ref),(func , ref))
DYNAMIC_GL_FUNCTION_V(ClearColorxOES,(DYNAMIC_GL_TYPE(GLclampx) red , DYNAMIC_GL_TYPE(GLclampx) green , DYNAMIC_GL_TYPE(GLclampx) blue , DYNAMIC_GL_TYPE(GLclampx) alpha),(red , green , blue , alpha))
DYNAMIC_GL_FUNCTION_V(ClearDepthxOES,(DYNAMIC_GL_TYPE(GLclampx) depth),(depth))
DYNAMIC_GL_FUNCTION_V(ClipPlanexOES,(DYNAMIC_GL_TYPE(GLenum) plane , const DYNAMIC_GL_TYPE(GLfixed) * equation),(plane , equation))
DYNAMIC_GL_FUNCTION_V(Color4xOES,(DYNAMIC_GL_TYPE(GLfixed) red , DYNAMIC_GL_TYPE(GLfixed) green , DYNAMIC_GL_TYPE(GLfixed) blue , DYNAMIC_GL_TYPE(GLfixed) alpha),(red , green , blue , alpha))
DYNAMIC_GL_FUNCTION_V(DepthRangexOES,(DYNAMIC_GL_TYPE(GLclampx) zNear , DYNAMIC_GL_TYPE(GLclampx) zFar),(zNear , zFar))
DYNAMIC_GL_FUNCTION_V(FogxOES,(DYNAMIC_GL_TYPE(GLenum) pname , DYNAMIC_GL_TYPE(GLfixed) param),(pname , param))
DYNAMIC_GL_FUNCTION_V(FogxvOES,(DYNAMIC_GL_TYPE(GLenum) pname , const DYNAMIC_GL_TYPE(GLfixed) * params),(pname , params))
DYNAMIC_GL_FUNCTION_V(FrustumxOES,(DYNAMIC_GL_TYPE(GLfixed) left , DYNAMIC_GL_TYPE(GLfixed) right , DYNAMIC_GL_TYPE(GLfixed) bottom , DYNAMIC_GL_TYPE(GLfixed) top , DYNAMIC_GL_TYPE(GLfixed) zNear , DYNAMIC_GL_TYPE(GLfixed) zFar),(left , right , bottom , top , zNear , zFar))
DYNAMIC_GL_FUNCTION_V(GetFixedvOES,(DYNAMIC_GL_TYPE(GLenum) pname , DYNAMIC_GL_TYPE(GLfixed) * params),(pname , params))
DYNAMIC_GL_FUNCTION_V(GetLightxvOES,(DYNAMIC_GL_TYPE(GLenum) light , DYNAMIC_GL_TYPE(GLenum) pname , DYNAMIC_GL_TYPE(GLfixed) * params),(light , pname , params))
DYNAMIC_GL_FUNCTION_V(GetMaterialxvOES,(DYNAMIC_GL_TYPE(GLenum) face , DYNAMIC_GL_TYPE(GLenum) pname , DYNAMIC_GL_TYPE(GLfixed) * params),(face , pname , params))
DYNAMIC_GL_FUNCTION_V(GetTexEnvxvOES,(DYNAMIC_GL_TYPE(GLenum) env , DYNAMIC_GL_TYPE(GLenum) pname , DYNAMIC_GL_TYPE(GLfixed) * params),(env , pname , params))
DYNAMIC_GL_FUNCTION_V(GetTexParameterxvOES,(DYNAMIC_GL_TYPE(GLenum) target , DYNAMIC_GL_TYPE(GLenum) pname , DYNAMIC_GL_TYPE(GLfixed) * params),(target , pname , params))
DYNAMIC_GL_FUNCTION_V(LightModelxOES,(DYNAMIC_GL_TYPE(GLenum) pname , DYNAMIC_GL_TYPE(GLfixed) param),(pname , param))
DYNAMIC_GL_FUNCTION_V(LightModelxvOES,(DYNAMIC_GL_TYPE(GLenum) pname , const DYNAMIC_GL_TYPE(GLfixed) * params),(pname , params))
DYNAMIC_GL_FUNCTION_V(LightxOES,(DYNAMIC_GL_TYPE(GLenum) light , DYNAMIC_GL_TYPE(GLenum) pname , DYNAMIC_GL_TYPE(GLfixed) param),(light , pname , param))
DYNAMIC_GL_FUNCTION_V(LightxvOES,(DYNAMIC_GL_TYPE(GLenum) light , DYNAMIC_GL_TYPE(GLenum) pname , const DYNAMIC_GL_TYPE(GLfixed) * params),(light , pname , params))
DYNAMIC_GL_FUNCTION_V(LineWidthxOES,(DYNAMIC_GL_TYPE(GLfixed) width),(width))
DYNAMIC_GL_FUNCTION_V(LoadMatrixxOES,(const DYNAMIC_GL_TYPE(GLfixed) * m),(m))
DYNAMIC_GL_FUNCTION_V(MaterialxOES,(DYNAMIC_GL_TYPE(GLenum) face , DYNAMIC_GL_TYPE(GLenum) pname , DYNAMIC_GL_TYPE(GLfixed) param),(face , pname , param))
DYNAMIC_GL_FUNCTION_V(MaterialxvOES,(DYNAMIC_GL_TYPE(GLenum) face , DYNAMIC_GL_TYPE(GLenum) pname , const DYNAMIC_GL_TYPE(GLfixed) * params),(face , pname , params))
DYNAMIC_GL_FUNCTION_V(MultMatrixxOES,(const DYNAMIC_GL_TYPE(GLfixed) * m),(m))
DYNAMIC_GL_FUNCTION_V(MultiTexCoord4xOES,(DYNAMIC_GL_TYPE(GLenum) target , DYNAMIC_GL_TYPE(GLfixed) s , DYNAMIC_GL_TYPE(GLfixed) t , DYNAMIC_GL_TYPE(GLfixed) r , DYNAMIC_GL_TYPE(GLfixed) q),(target , s , t , r , q))
DYNAMIC_GL_FUNCTION_V(Normal3xOES,(DYNAMIC_GL_TYPE(GLfixed) nx , DYNAMIC_GL_TYPE(GLfixed) ny , DYNAMIC_GL_TYPE(GLfixed) nz),(nx , ny , nz))
DYNAMIC_GL_FUNCTION_V(OrthoxOES,(DYNAMIC_GL_TYPE(GLfixed) left , DYNAMIC_GL_TYPE(GLfixed) right , DYNAMIC_GL_TYPE(GLfixed) bottom , DYNAMIC_GL_TYPE(GLfixed) top , DYNAMIC_GL_TYPE(GLfixed) zNear , DYNAMIC_GL_TYPE(GLfixed) zFar),(left , right , bottom , top , zNear , zFar))
DYNAMIC_GL_FUNCTION_V(PointParameterxOES,(DYNAMIC_GL_TYPE(GLenum) pname , DYNAMIC_GL_TYPE(GLfixed) param),(pname , param))
DYNAMIC_GL_FUNCTION_V(PointParameterxvOES,(DYNAMIC_GL_TYPE(GLenum) pname , const DYNAMIC_GL_TYPE(GLfixed) * params),(pname , params))
DYNAMIC_GL_FUNCTION_V(PointSizexOES,(DYNAMIC_GL_TYPE(GLfixed) size),(size))
DYNAMIC_GL_FUNCTION_V(PolygonOffsetxOES,(DYNAMIC_GL_TYPE(GLfixed) factor , DYNAMIC_GL_TYPE(GLfixed) units),(factor , units))
DYNAMIC_GL_FUNCTION_V(RotatexOES,(DYNAMIC_GL_TYPE(GLfixed) angle , DYNAMIC_GL_TYPE(GLfixed) x , DYNAMIC_GL_TYPE(GLfixed) y , DYNAMIC_GL_TYPE(GLfixed) z),(angle , x , y , z))
DYNAMIC_GL_FUNCTION_V(SampleCoveragexOES,(DYNAMIC_GL_TYPE(GLclampx) value , DYNAMIC_GL_TYPE(GLboolean) invert),(value , invert))
DYNAMIC_GL_FUNCTION_V(ScalexOES,(DYNAMIC_GL_TYPE(GLfixed) x , DYNAMIC_GL_TYPE(GLfixed) y , DYNAMIC_GL_TYPE(GLfixed) z),(x , y , z))
DYNAMIC_GL_FUNCTION_V(TexEnvxOES,(DYNAMIC_GL_TYPE(GLenum) target , DYNAMIC_GL_TYPE(GLenum) pname , DYNAMIC_GL_TYPE(GLfixed) param),(target , pname , param))
DYNAMIC_GL_FUNCTION_V(TexEnvxvOES,(DYNAMIC_GL_TYPE(GLenum) target , DYNAMIC_GL_TYPE(GLenum) pname , const DYNAMIC_GL_TYPE(GLfixed) * params),(target , pname , params))
DYNAMIC_GL_FUNCTION_V(TexParameterxOES,(DYNAMIC_GL_TYPE(GLenum) target , DYNAMIC_GL_TYPE(GLenum) pname , DYNAMIC_GL_TYPE(GLfixed) param),(target , pname , param))
DYNAMIC_GL_FUNCTION_V(TexParameterxvOES,(DYNAMIC_GL_TYPE(GLenum) target , DYNAMIC_GL_TYPE(GLenum) pname , const DYNAMIC_GL_TYPE(GLfixed) * params),(target , pname , params))
DYNAMIC_GL_FUNCTION_V(TranslatexOES,(DYNAMIC_GL_TYPE(GLfixed) x , DYNAMIC_GL_TYPE(GLfixed) y , DYNAMIC_GL_TYPE(GLfixed) z),(x , y , z))
#endif /*USE_DYNAMIC_GL_OES_fixed_point*/

/*EXT_multi_draw_arrays*/
#ifdef USE_DYNAMIC_GL_EXT_multi_draw_arrays
DYNAMIC_GL_FEATURE(EXT_multi_draw_arrays)
DYNAMIC_GL_FUNCTION_V(MultiDrawArraysEXT,(DYNAMIC_GL_TYPE(GLenum) mode , DYNAMIC_GL_TYPE(GLint) * first , DYNAMIC_GL_TYPE(GLsizei) * count , DYNAMIC_GL_TYPE(GLsizei) primcount),(mode , first , count , primcount))
DYNAMIC_GL_FUNCTION_V(MultiDrawElementsEXT,(DYNAMIC_GL_TYPE(GLenum) mode , const DYNAMIC_GL_TYPE(GLsizei) * count , DYNAMIC_GL_TYPE(GLenum) type , const DYNAMIC_GL_TYPE(GLvoid) * * indices , DYNAMIC_GL_TYPE(GLsizei) primcount),(mode , count , type , indices , primcount))
#endif /*USE_DYNAMIC_GL_EXT_multi_draw_arrays*/

