/*CORE*/
#ifdef USE_DYNAMIC_GL_CORE
DYNAMIC_GL_FEATURE(CORE)
DYNAMIC_GL_TYPEDEF(void,void)
DYNAMIC_GL_TYPEDEF(char,char)
DYNAMIC_GL_TYPEDEF(unsigned int,enum)
DYNAMIC_GL_TYPEDEF(unsigned char,boolean)
DYNAMIC_GL_TYPEDEF(unsigned int,bitfield)
DYNAMIC_GL_TYPEDEF(khronos_int8_t,byte)
DYNAMIC_GL_TYPEDEF(short,short)
DYNAMIC_GL_TYPEDEF(int,int)
DYNAMIC_GL_TYPEDEF(int,sizei)
DYNAMIC_GL_TYPEDEF(khronos_uint8_t,ubyte)
DYNAMIC_GL_TYPEDEF(unsigned short,ushort)
DYNAMIC_GL_TYPEDEF(unsigned int,uint)
DYNAMIC_GL_TYPEDEF(khronos_float_t,float)
DYNAMIC_GL_TYPEDEF(khronos_float_t,clampf)
DYNAMIC_GL_TYPEDEF(khronos_int32_t,fixed)
DYNAMIC_GL_TYPEDEF(khronos_int32_t,clampx)
DYNAMIC_GL_TYPEDEF(khronos_intptr_t,intptr)
DYNAMIC_GL_TYPEDEF(khronos_ssize_t,sizeiptr)
DYNAMIC_GL_CONSTANT(VERSION_ES_CM_1_0,1)
DYNAMIC_GL_CONSTANT(VERSION_ES_CL_1_0,1)
DYNAMIC_GL_CONSTANT(VERSION_ES_CM_1_1,1)
DYNAMIC_GL_CONSTANT(VERSION_ES_CL_1_1,1)
DYNAMIC_GL_CONSTANT(DEPTH_BUFFER_BIT,0x00000100)
DYNAMIC_GL_CONSTANT(STENCIL_BUFFER_BIT,0x00000400)
DYNAMIC_GL_CONSTANT(COLOR_BUFFER_BIT,0x00004000)
DYNAMIC_GL_CONSTANT(FALSE,0)
DYNAMIC_GL_CONSTANT(TRUE,1)
DYNAMIC_GL_CONSTANT(POINTS,0x0000)
DYNAMIC_GL_CONSTANT(LINES,0x0001)
DYNAMIC_GL_CONSTANT(LINE_LOOP,0x0002)
DYNAMIC_GL_CONSTANT(LINE_STRIP,0x0003)
DYNAMIC_GL_CONSTANT(TRIANGLES,0x0004)
DYNAMIC_GL_CONSTANT(TRIANGLE_STRIP,0x0005)
DYNAMIC_GL_CONSTANT(TRIANGLE_FAN,0x0006)
DYNAMIC_GL_CONSTANT(NEVER,0x0200)
DYNAMIC_GL_CONSTANT(LESS,0x0201)
DYNAMIC_GL_CONSTANT(EQUAL,0x0202)
DYNAMIC_GL_CONSTANT(LEQUAL,0x0203)
DYNAMIC_GL_CONSTANT(GREATER,0x0204)
DYNAMIC_GL_CONSTANT(NOTEQUAL,0x0205)
DYNAMIC_GL_CONSTANT(GEQUAL,0x0206)
DYNAMIC_GL_CONSTANT(ALWAYS,0x0207)
DYNAMIC_GL_CONSTANT(ZERO,0)
DYNAMIC_GL_CONSTANT(ONE,1)
DYNAMIC_GL_CONSTANT(SRC_COLOR,0x0300)
DYNAMIC_GL_CONSTANT(ONE_MINUS_SRC_COLOR,0x0301)
DYNAMIC_GL_CONSTANT(SRC_ALPHA,0x0302)
DYNAMIC_GL_CONSTANT(ONE_MINUS_SRC_ALPHA,0x0303)
DYNAMIC_GL_CONSTANT(DST_ALPHA,0x0304)
DYNAMIC_GL_CONSTANT(ONE_MINUS_DST_ALPHA,0x0305)
DYNAMIC_GL_CONSTANT(DST_COLOR,0x0306)
DYNAMIC_GL_CONSTANT(ONE_MINUS_DST_COLOR,0x0307)
DYNAMIC_GL_CONSTANT(SRC_ALPHA_SATURATE,0x0308)
DYNAMIC_GL_CONSTANT(CLIP_PLANE0,0x3000)
DYNAMIC_GL_CONSTANT(CLIP_PLANE1,0x3001)
DYNAMIC_GL_CONSTANT(CLIP_PLANE2,0x3002)
DYNAMIC_GL_CONSTANT(CLIP_PLANE3,0x3003)
DYNAMIC_GL_CONSTANT(CLIP_PLANE4,0x3004)
DYNAMIC_GL_CONSTANT(CLIP_PLANE5,0x3005)
DYNAMIC_GL_CONSTANT(FRONT,0x0404)
DYNAMIC_GL_CONSTANT(BACK,0x0405)
DYNAMIC_GL_CONSTANT(FRONT_AND_BACK,0x0408)
DYNAMIC_GL_CONSTANT(FOG,0x0B60)
DYNAMIC_GL_CONSTANT(LIGHTING,0x0B50)
DYNAMIC_GL_CONSTANT(TEXTURE_2D,0x0DE1)
DYNAMIC_GL_CONSTANT(CULL_FACE,0x0B44)
DYNAMIC_GL_CONSTANT(ALPHA_TEST,0x0BC0)
DYNAMIC_GL_CONSTANT(BLEND,0x0BE2)
DYNAMIC_GL_CONSTANT(COLOR_LOGIC_OP,0x0BF2)
DYNAMIC_GL_CONSTANT(DITHER,0x0BD0)
DYNAMIC_GL_CONSTANT(STENCIL_TEST,0x0B90)
DYNAMIC_GL_CONSTANT(DEPTH_TEST,0x0B71)
DYNAMIC_GL_CONSTANT(POINT_SMOOTH,0x0B10)
DYNAMIC_GL_CONSTANT(LINE_SMOOTH,0x0B20)
DYNAMIC_GL_CONSTANT(SCISSOR_TEST,0x0C11)
DYNAMIC_GL_CONSTANT(COLOR_MATERIAL,0x0B57)
DYNAMIC_GL_CONSTANT(NORMALIZE,0x0BA1)
DYNAMIC_GL_CONSTANT(RESCALE_NORMAL,0x803A)
DYNAMIC_GL_CONSTANT(POLYGON_OFFSET_FILL,0x8037)
DYNAMIC_GL_CONSTANT(VERTEX_ARRAY,0x8074)
DYNAMIC_GL_CONSTANT(NORMAL_ARRAY,0x8075)
DYNAMIC_GL_CONSTANT(COLOR_ARRAY,0x8076)
DYNAMIC_GL_CONSTANT(TEXTURE_COORD_ARRAY,0x8078)
DYNAMIC_GL_CONSTANT(MULTISAMPLE,0x809D)
DYNAMIC_GL_CONSTANT(SAMPLE_ALPHA_TO_COVERAGE,0x809E)
DYNAMIC_GL_CONSTANT(SAMPLE_ALPHA_TO_ONE,0x809F)
DYNAMIC_GL_CONSTANT(SAMPLE_COVERAGE,0x80A0)
DYNAMIC_GL_CONSTANT(NO_ERROR,0)
DYNAMIC_GL_CONSTANT(INVALID_ENUM,0x0500)
DYNAMIC_GL_CONSTANT(INVALID_VALUE,0x0501)
DYNAMIC_GL_CONSTANT(INVALID_OPERATION,0x0502)
DYNAMIC_GL_CONSTANT(STACK_OVERFLOW,0x0503)
DYNAMIC_GL_CONSTANT(STACK_UNDERFLOW,0x0504)
DYNAMIC_GL_CONSTANT(OUT_OF_MEMORY,0x0505)
DYNAMIC_GL_CONSTANT(EXP,0x0800)
DYNAMIC_GL_CONSTANT(EXP2,0x0801)
DYNAMIC_GL_CONSTANT(FOG_DENSITY,0x0B62)
DYNAMIC_GL_CONSTANT(FOG_START,0x0B63)
DYNAMIC_GL_CONSTANT(FOG_END,0x0B64)
DYNAMIC_GL_CONSTANT(FOG_MODE,0x0B65)
DYNAMIC_GL_CONSTANT(FOG_COLOR,0x0B66)
DYNAMIC_GL_CONSTANT(CW,0x0900)
DYNAMIC_GL_CONSTANT(CCW,0x0901)
DYNAMIC_GL_CONSTANT(CURRENT_COLOR,0x0B00)
DYNAMIC_GL_CONSTANT(CURRENT_NORMAL,0x0B02)
DYNAMIC_GL_CONSTANT(CURRENT_TEXTURE_COORDS,0x0B03)
DYNAMIC_GL_CONSTANT(POINT_SIZE,0x0B11)
DYNAMIC_GL_CONSTANT(POINT_SIZE_MIN,0x8126)
DYNAMIC_GL_CONSTANT(POINT_SIZE_MAX,0x8127)
DYNAMIC_GL_CONSTANT(POINT_FADE_THRESHOLD_SIZE,0x8128)
DYNAMIC_GL_CONSTANT(POINT_DISTANCE_ATTENUATION,0x8129)
DYNAMIC_GL_CONSTANT(SMOOTH_POINT_SIZE_RANGE,0x0B12)
DYNAMIC_GL_CONSTANT(LINE_WIDTH,0x0B21)
DYNAMIC_GL_CONSTANT(SMOOTH_LINE_WIDTH_RANGE,0x0B22)
DYNAMIC_GL_CONSTANT(ALIASED_POINT_SIZE_RANGE,0x846D)
DYNAMIC_GL_CONSTANT(ALIASED_LINE_WIDTH_RANGE,0x846E)
DYNAMIC_GL_CONSTANT(CULL_FACE_MODE,0x0B45)
DYNAMIC_GL_CONSTANT(FRONT_FACE,0x0B46)
DYNAMIC_GL_CONSTANT(SHADE_MODEL,0x0B54)
DYNAMIC_GL_CONSTANT(DEPTH_RANGE,0x0B70)
DYNAMIC_GL_CONSTANT(DEPTH_WRITEMASK,0x0B72)
DYNAMIC_GL_CONSTANT(DEPTH_CLEAR_VALUE,0x0B73)
DYNAMIC_GL_CONSTANT(DEPTH_FUNC,0x0B74)
DYNAMIC_GL_CONSTANT(STENCIL_CLEAR_VALUE,0x0B91)
DYNAMIC_GL_CONSTANT(STENCIL_FUNC,0x0B92)
DYNAMIC_GL_CONSTANT(STENCIL_VALUE_MASK,0x0B93)
DYNAMIC_GL_CONSTANT(STENCIL_FAIL,0x0B94)
DYNAMIC_GL_CONSTANT(STENCIL_PASS_DEPTH_FAIL,0x0B95)
DYNAMIC_GL_CONSTANT(STENCIL_PASS_DEPTH_PASS,0x0B96)
DYNAMIC_GL_CONSTANT(STENCIL_REF,0x0B97)
DYNAMIC_GL_CONSTANT(STENCIL_WRITEMASK,0x0B98)
DYNAMIC_GL_CONSTANT(MATRIX_MODE,0x0BA0)
DYNAMIC_GL_CONSTANT(VIEWPORT,0x0BA2)
DYNAMIC_GL_CONSTANT(MODELVIEW_STACK_DEPTH,0x0BA3)
DYNAMIC_GL_CONSTANT(PROJECTION_STACK_DEPTH,0x0BA4)
DYNAMIC_GL_CONSTANT(TEXTURE_STACK_DEPTH,0x0BA5)
DYNAMIC_GL_CONSTANT(MODELVIEW_MATRIX,0x0BA6)
DYNAMIC_GL_CONSTANT(PROJECTION_MATRIX,0x0BA7)
DYNAMIC_GL_CONSTANT(TEXTURE_MATRIX,0x0BA8)
DYNAMIC_GL_CONSTANT(ALPHA_TEST_FUNC,0x0BC1)
DYNAMIC_GL_CONSTANT(ALPHA_TEST_REF,0x0BC2)
DYNAMIC_GL_CONSTANT(BLEND_DST,0x0BE0)
DYNAMIC_GL_CONSTANT(BLEND_SRC,0x0BE1)
DYNAMIC_GL_CONSTANT(LOGIC_OP_MODE,0x0BF0)
DYNAMIC_GL_CONSTANT(SCISSOR_BOX,0x0C10)
DYNAMIC_GL_CONSTANT(SCISSOR_TEST,0x0C11)
DYNAMIC_GL_CONSTANT(COLOR_CLEAR_VALUE,0x0C22)
DYNAMIC_GL_CONSTANT(COLOR_WRITEMASK,0x0C23)
DYNAMIC_GL_CONSTANT(UNPACK_ALIGNMENT,0x0CF5)
DYNAMIC_GL_CONSTANT(PACK_ALIGNMENT,0x0D05)
DYNAMIC_GL_CONSTANT(MAX_LIGHTS,0x0D31)
DYNAMIC_GL_CONSTANT(MAX_CLIP_PLANES,0x0D32)
DYNAMIC_GL_CONSTANT(MAX_TEXTURE_SIZE,0x0D33)
DYNAMIC_GL_CONSTANT(MAX_MODELVIEW_STACK_DEPTH,0x0D36)
DYNAMIC_GL_CONSTANT(MAX_PROJECTION_STACK_DEPTH,0x0D38)
DYNAMIC_GL_CONSTANT(MAX_TEXTURE_STACK_DEPTH,0x0D39)
DYNAMIC_GL_CONSTANT(MAX_VIEWPORT_DIMS,0x0D3A)
DYNAMIC_GL_CONSTANT(MAX_TEXTURE_UNITS,0x84E2)
DYNAMIC_GL_CONSTANT(SUBPIXEL_BITS,0x0D50)
DYNAMIC_GL_CONSTANT(RED_BITS,0x0D52)
DYNAMIC_GL_CONSTANT(GREEN_BITS,0x0D53)
DYNAMIC_GL_CONSTANT(BLUE_BITS,0x0D54)
DYNAMIC_GL_CONSTANT(ALPHA_BITS,0x0D55)
DYNAMIC_GL_CONSTANT(DEPTH_BITS,0x0D56)
DYNAMIC_GL_CONSTANT(STENCIL_BITS,0x0D57)
DYNAMIC_GL_CONSTANT(POLYGON_OFFSET_UNITS,0x2A00)
DYNAMIC_GL_CONSTANT(POLYGON_OFFSET_FILL,0x8037)
DYNAMIC_GL_CONSTANT(POLYGON_OFFSET_FACTOR,0x8038)
DYNAMIC_GL_CONSTANT(TEXTURE_BINDING_2D,0x8069)
DYNAMIC_GL_CONSTANT(VERTEX_ARRAY_SIZE,0x807A)
DYNAMIC_GL_CONSTANT(VERTEX_ARRAY_TYPE,0x807B)
DYNAMIC_GL_CONSTANT(VERTEX_ARRAY_STRIDE,0x807C)
DYNAMIC_GL_CONSTANT(NORMAL_ARRAY_TYPE,0x807E)
DYNAMIC_GL_CONSTANT(NORMAL_ARRAY_STRIDE,0x807F)
DYNAMIC_GL_CONSTANT(COLOR_ARRAY_SIZE,0x8081)
DYNAMIC_GL_CONSTANT(COLOR_ARRAY_TYPE,0x8082)
DYNAMIC_GL_CONSTANT(COLOR_ARRAY_STRIDE,0x8083)
DYNAMIC_GL_CONSTANT(TEXTURE_COORD_ARRAY_SIZE,0x8088)
DYNAMIC_GL_CONSTANT(TEXTURE_COORD_ARRAY_TYPE,0x8089)
DYNAMIC_GL_CONSTANT(TEXTURE_COORD_ARRAY_STRIDE,0x808A)
DYNAMIC_GL_CONSTANT(VERTEX_ARRAY_POINTER,0x808E)
DYNAMIC_GL_CONSTANT(NORMAL_ARRAY_POINTER,0x808F)
DYNAMIC_GL_CONSTANT(COLOR_ARRAY_POINTER,0x8090)
DYNAMIC_GL_CONSTANT(TEXTURE_COORD_ARRAY_POINTER,0x8092)
DYNAMIC_GL_CONSTANT(SAMPLE_BUFFERS,0x80A8)
DYNAMIC_GL_CONSTANT(SAMPLES,0x80A9)
DYNAMIC_GL_CONSTANT(SAMPLE_COVERAGE_VALUE,0x80AA)
DYNAMIC_GL_CONSTANT(SAMPLE_COVERAGE_INVERT,0x80AB)
DYNAMIC_GL_CONSTANT(NUM_COMPRESSED_TEXTURE_FORMATS,0x86A2)
DYNAMIC_GL_CONSTANT(COMPRESSED_TEXTURE_FORMATS,0x86A3)
DYNAMIC_GL_CONSTANT(DONT_CARE,0x1100)
DYNAMIC_GL_CONSTANT(FASTEST,0x1101)
DYNAMIC_GL_CONSTANT(NICEST,0x1102)
DYNAMIC_GL_CONSTANT(PERSPECTIVE_CORRECTION_HINT,0x0C50)
DYNAMIC_GL_CONSTANT(POINT_SMOOTH_HINT,0x0C51)
DYNAMIC_GL_CONSTANT(LINE_SMOOTH_HINT,0x0C52)
DYNAMIC_GL_CONSTANT(FOG_HINT,0x0C54)
DYNAMIC_GL_CONSTANT(GENERATE_MIPMAP_HINT,0x8192)
DYNAMIC_GL_CONSTANT(LIGHT_MODEL_AMBIENT,0x0B53)
DYNAMIC_GL_CONSTANT(LIGHT_MODEL_TWO_SIDE,0x0B52)
DYNAMIC_GL_CONSTANT(AMBIENT,0x1200)
DYNAMIC_GL_CONSTANT(DIFFUSE,0x1201)
DYNAMIC_GL_CONSTANT(SPECULAR,0x1202)
DYNAMIC_GL_CONSTANT(POSITION,0x1203)
DYNAMIC_GL_CONSTANT(SPOT_DIRECTION,0x1204)
DYNAMIC_GL_CONSTANT(SPOT_EXPONENT,0x1205)
DYNAMIC_GL_CONSTANT(SPOT_CUTOFF,0x1206)
DYNAMIC_GL_CONSTANT(CONSTANT_ATTENUATION,0x1207)
DYNAMIC_GL_CONSTANT(LINEAR_ATTENUATION,0x1208)
DYNAMIC_GL_CONSTANT(QUADRATIC_ATTENUATION,0x1209)
DYNAMIC_GL_CONSTANT(BYTE,0x1400)
DYNAMIC_GL_CONSTANT(UNSIGNED_BYTE,0x1401)
DYNAMIC_GL_CONSTANT(SHORT,0x1402)
DYNAMIC_GL_CONSTANT(UNSIGNED_SHORT,0x1403)
DYNAMIC_GL_CONSTANT(FLOAT,0x1406)
DYNAMIC_GL_CONSTANT(FIXED,0x140C)
DYNAMIC_GL_CONSTANT(CLEAR,0x1500)
DYNAMIC_GL_CONSTANT(AND,0x1501)
DYNAMIC_GL_CONSTANT(AND_REVERSE,0x1502)
DYNAMIC_GL_CONSTANT(COPY,0x1503)
DYNAMIC_GL_CONSTANT(AND_INVERTED,0x1504)
DYNAMIC_GL_CONSTANT(NOOP,0x1505)
DYNAMIC_GL_CONSTANT(XOR,0x1506)
DYNAMIC_GL_CONSTANT(OR,0x1507)
DYNAMIC_GL_CONSTANT(NOR,0x1508)
DYNAMIC_GL_CONSTANT(EQUIV,0x1509)
DYNAMIC_GL_CONSTANT(INVERT,0x150A)
DYNAMIC_GL_CONSTANT(OR_REVERSE,0x150B)
DYNAMIC_GL_CONSTANT(COPY_INVERTED,0x150C)
DYNAMIC_GL_CONSTANT(OR_INVERTED,0x150D)
DYNAMIC_GL_CONSTANT(NAND,0x150E)
DYNAMIC_GL_CONSTANT(SET,0x150F)
DYNAMIC_GL_CONSTANT(EMISSION,0x1600)
DYNAMIC_GL_CONSTANT(SHININESS,0x1601)
DYNAMIC_GL_CONSTANT(AMBIENT_AND_DIFFUSE,0x1602)
DYNAMIC_GL_CONSTANT(MODELVIEW,0x1700)
DYNAMIC_GL_CONSTANT(PROJECTION,0x1701)
DYNAMIC_GL_CONSTANT(TEXTURE,0x1702)
DYNAMIC_GL_CONSTANT(ALPHA,0x1906)
DYNAMIC_GL_CONSTANT(RGB,0x1907)
DYNAMIC_GL_CONSTANT(RGBA,0x1908)
DYNAMIC_GL_CONSTANT(LUMINANCE,0x1909)
DYNAMIC_GL_CONSTANT(LUMINANCE_ALPHA,0x190A)
DYNAMIC_GL_CONSTANT(UNPACK_ALIGNMENT,0x0CF5)
DYNAMIC_GL_CONSTANT(PACK_ALIGNMENT,0x0D05)
DYNAMIC_GL_CONSTANT(UNSIGNED_SHORT_4_4_4_4,0x8033)
DYNAMIC_GL_CONSTANT(UNSIGNED_SHORT_5_5_5_1,0x8034)
DYNAMIC_GL_CONSTANT(UNSIGNED_SHORT_5_6_5,0x8363)
DYNAMIC_GL_CONSTANT(FLAT,0x1D00)
DYNAMIC_GL_CONSTANT(SMOOTH,0x1D01)
DYNAMIC_GL_CONSTANT(KEEP,0x1E00)
DYNAMIC_GL_CONSTANT(REPLACE,0x1E01)
DYNAMIC_GL_CONSTANT(INCR,0x1E02)
DYNAMIC_GL_CONSTANT(DECR,0x1E03)
DYNAMIC_GL_CONSTANT(VENDOR,0x1F00)
DYNAMIC_GL_CONSTANT(RENDERER,0x1F01)
DYNAMIC_GL_CONSTANT(VERSION,0x1F02)
DYNAMIC_GL_CONSTANT(EXTENSIONS,0x1F03)
DYNAMIC_GL_CONSTANT(MODULATE,0x2100)
DYNAMIC_GL_CONSTANT(DECAL,0x2101)
DYNAMIC_GL_CONSTANT(ADD,0x0104)
DYNAMIC_GL_CONSTANT(TEXTURE_ENV_MODE,0x2200)
DYNAMIC_GL_CONSTANT(TEXTURE_ENV_COLOR,0x2201)
DYNAMIC_GL_CONSTANT(TEXTURE_ENV,0x2300)
DYNAMIC_GL_CONSTANT(NEAREST,0x2600)
DYNAMIC_GL_CONSTANT(LINEAR,0x2601)
DYNAMIC_GL_CONSTANT(NEAREST_MIPMAP_NEAREST,0x2700)
DYNAMIC_GL_CONSTANT(LINEAR_MIPMAP_NEAREST,0x2701)
DYNAMIC_GL_CONSTANT(NEAREST_MIPMAP_LINEAR,0x2702)
DYNAMIC_GL_CONSTANT(LINEAR_MIPMAP_LINEAR,0x2703)
DYNAMIC_GL_CONSTANT(TEXTURE_MAG_FILTER,0x2800)
DYNAMIC_GL_CONSTANT(TEXTURE_MIN_FILTER,0x2801)
DYNAMIC_GL_CONSTANT(TEXTURE_WRAP_S,0x2802)
DYNAMIC_GL_CONSTANT(TEXTURE_WRAP_T,0x2803)
DYNAMIC_GL_CONSTANT(GENERATE_MIPMAP,0x8191)
DYNAMIC_GL_CONSTANT(TEXTURE0,0x84C0)
DYNAMIC_GL_CONSTANT(TEXTURE1,0x84C1)
DYNAMIC_GL_CONSTANT(TEXTURE2,0x84C2)
DYNAMIC_GL_CONSTANT(TEXTURE3,0x84C3)
DYNAMIC_GL_CONSTANT(TEXTURE4,0x84C4)
DYNAMIC_GL_CONSTANT(TEXTURE5,0x84C5)
DYNAMIC_GL_CONSTANT(TEXTURE6,0x84C6)
DYNAMIC_GL_CONSTANT(TEXTURE7,0x84C7)
DYNAMIC_GL_CONSTANT(TEXTURE8,0x84C8)
DYNAMIC_GL_CONSTANT(TEXTURE9,0x84C9)
DYNAMIC_GL_CONSTANT(TEXTURE10,0x84CA)
DYNAMIC_GL_CONSTANT(TEXTURE11,0x84CB)
DYNAMIC_GL_CONSTANT(TEXTURE12,0x84CC)
DYNAMIC_GL_CONSTANT(TEXTURE13,0x84CD)
DYNAMIC_GL_CONSTANT(TEXTURE14,0x84CE)
DYNAMIC_GL_CONSTANT(TEXTURE15,0x84CF)
DYNAMIC_GL_CONSTANT(TEXTURE16,0x84D0)
DYNAMIC_GL_CONSTANT(TEXTURE17,0x84D1)
DYNAMIC_GL_CONSTANT(TEXTURE18,0x84D2)
DYNAMIC_GL_CONSTANT(TEXTURE19,0x84D3)
DYNAMIC_GL_CONSTANT(TEXTURE20,0x84D4)
DYNAMIC_GL_CONSTANT(TEXTURE21,0x84D5)
DYNAMIC_GL_CONSTANT(TEXTURE22,0x84D6)
DYNAMIC_GL_CONSTANT(TEXTURE23,0x84D7)
DYNAMIC_GL_CONSTANT(TEXTURE24,0x84D8)
DYNAMIC_GL_CONSTANT(TEXTURE25,0x84D9)
DYNAMIC_GL_CONSTANT(TEXTURE26,0x84DA)
DYNAMIC_GL_CONSTANT(TEXTURE27,0x84DB)
DYNAMIC_GL_CONSTANT(TEXTURE28,0x84DC)
DYNAMIC_GL_CONSTANT(TEXTURE29,0x84DD)
DYNAMIC_GL_CONSTANT(TEXTURE30,0x84DE)
DYNAMIC_GL_CONSTANT(TEXTURE31,0x84DF)
DYNAMIC_GL_CONSTANT(ACTIVE_TEXTURE,0x84E0)
DYNAMIC_GL_CONSTANT(CLIENT_ACTIVE_TEXTURE,0x84E1)
DYNAMIC_GL_CONSTANT(REPEAT,0x2901)
DYNAMIC_GL_CONSTANT(CLAMP_TO_EDGE,0x812F)
DYNAMIC_GL_CONSTANT(LIGHT0,0x4000)
DYNAMIC_GL_CONSTANT(LIGHT1,0x4001)
DYNAMIC_GL_CONSTANT(LIGHT2,0x4002)
DYNAMIC_GL_CONSTANT(LIGHT3,0x4003)
DYNAMIC_GL_CONSTANT(LIGHT4,0x4004)
DYNAMIC_GL_CONSTANT(LIGHT5,0x4005)
DYNAMIC_GL_CONSTANT(LIGHT6,0x4006)
DYNAMIC_GL_CONSTANT(LIGHT7,0x4007)
DYNAMIC_GL_CONSTANT(ARRAY_BUFFER,0x8892)
DYNAMIC_GL_CONSTANT(ELEMENT_ARRAY_BUFFER,0x8893)
DYNAMIC_GL_CONSTANT(ARRAY_BUFFER_BINDING,0x8894)
DYNAMIC_GL_CONSTANT(ELEMENT_ARRAY_BUFFER_BINDING,0x8895)
DYNAMIC_GL_CONSTANT(VERTEX_ARRAY_BUFFER_BINDING,0x8896)
DYNAMIC_GL_CONSTANT(NORMAL_ARRAY_BUFFER_BINDING,0x8897)
DYNAMIC_GL_CONSTANT(COLOR_ARRAY_BUFFER_BINDING,0x8898)
DYNAMIC_GL_CONSTANT(TEXTURE_COORD_ARRAY_BUFFER_BINDING,0x889A)
DYNAMIC_GL_CONSTANT(STATIC_DRAW,0x88E4)
DYNAMIC_GL_CONSTANT(DYNAMIC_DRAW,0x88E8)
DYNAMIC_GL_CONSTANT(BUFFER_SIZE,0x8764)
DYNAMIC_GL_CONSTANT(BUFFER_USAGE,0x8765)
DYNAMIC_GL_CONSTANT(SUBTRACT,0x84E7)
DYNAMIC_GL_CONSTANT(COMBINE,0x8570)
DYNAMIC_GL_CONSTANT(COMBINE_RGB,0x8571)
DYNAMIC_GL_CONSTANT(COMBINE_ALPHA,0x8572)
DYNAMIC_GL_CONSTANT(RGB_SCALE,0x8573)
DYNAMIC_GL_CONSTANT(ADD_SIGNED,0x8574)
DYNAMIC_GL_CONSTANT(INTERPOLATE,0x8575)
DYNAMIC_GL_CONSTANT(CONSTANT,0x8576)
DYNAMIC_GL_CONSTANT(PRIMARY_COLOR,0x8577)
DYNAMIC_GL_CONSTANT(PREVIOUS,0x8578)
DYNAMIC_GL_CONSTANT(OPERAND0_RGB,0x8590)
DYNAMIC_GL_CONSTANT(OPERAND1_RGB,0x8591)
DYNAMIC_GL_CONSTANT(OPERAND2_RGB,0x8592)
DYNAMIC_GL_CONSTANT(OPERAND0_ALPHA,0x8598)
DYNAMIC_GL_CONSTANT(OPERAND1_ALPHA,0x8599)
DYNAMIC_GL_CONSTANT(OPERAND2_ALPHA,0x859A)
DYNAMIC_GL_CONSTANT(ALPHA_SCALE,0x0D1C)
DYNAMIC_GL_CONSTANT(SRC0_RGB,0x8580)
DYNAMIC_GL_CONSTANT(SRC1_RGB,0x8581)
DYNAMIC_GL_CONSTANT(SRC2_RGB,0x8582)
DYNAMIC_GL_CONSTANT(SRC0_ALPHA,0x8588)
DYNAMIC_GL_CONSTANT(SRC1_ALPHA,0x8589)
DYNAMIC_GL_CONSTANT(SRC2_ALPHA,0x858A)
DYNAMIC_GL_CONSTANT(DOT3_RGB,0x86AE)
DYNAMIC_GL_CONSTANT(DOT3_RGBA,0x86AF)
DYNAMIC_GL_FUNCTION_V(AlphaFunc,(DYNAMIC_GL_TYPE(enum) func , DYNAMIC_GL_TYPE(clampf) ref),(func , ref))
DYNAMIC_GL_FUNCTION_V(ClearColor,(DYNAMIC_GL_TYPE(clampf) red , DYNAMIC_GL_TYPE(clampf) green , DYNAMIC_GL_TYPE(clampf) blue , DYNAMIC_GL_TYPE(clampf) alpha),(red , green , blue , alpha))
DYNAMIC_GL_FUNCTION_V(ClearDepthf,(DYNAMIC_GL_TYPE(clampf) depth),(depth))
DYNAMIC_GL_FUNCTION_V(ClipPlanef,(DYNAMIC_GL_TYPE(enum) plane , const DYNAMIC_GL_TYPE(float) * equation),(plane , equation))
DYNAMIC_GL_FUNCTION_V(Color4f,(DYNAMIC_GL_TYPE(float) red , DYNAMIC_GL_TYPE(float) green , DYNAMIC_GL_TYPE(float) blue , DYNAMIC_GL_TYPE(float) alpha),(red , green , blue , alpha))
DYNAMIC_GL_FUNCTION_V(DepthRangef,(DYNAMIC_GL_TYPE(clampf) zNear , DYNAMIC_GL_TYPE(clampf) zFar),(zNear , zFar))
DYNAMIC_GL_FUNCTION_V(Fogf,(DYNAMIC_GL_TYPE(enum) pname , DYNAMIC_GL_TYPE(float) param),(pname , param))
DYNAMIC_GL_FUNCTION_V(Fogfv,(DYNAMIC_GL_TYPE(enum) pname , const DYNAMIC_GL_TYPE(float) * params),(pname , params))
DYNAMIC_GL_FUNCTION_V(Frustumf,(DYNAMIC_GL_TYPE(float) left , DYNAMIC_GL_TYPE(float) right , DYNAMIC_GL_TYPE(float) bottom , DYNAMIC_GL_TYPE(float) top , DYNAMIC_GL_TYPE(float) zNear , DYNAMIC_GL_TYPE(float) zFar),(left , right , bottom , top , zNear , zFar))
DYNAMIC_GL_FUNCTION_V(GetFloatv,(DYNAMIC_GL_TYPE(enum) pname , DYNAMIC_GL_TYPE(float) * params),(pname , params))
DYNAMIC_GL_FUNCTION_V(GetLightfv,(DYNAMIC_GL_TYPE(enum) light , DYNAMIC_GL_TYPE(enum) pname , DYNAMIC_GL_TYPE(float) * params),(light , pname , params))
DYNAMIC_GL_FUNCTION_V(GetMaterialfv,(DYNAMIC_GL_TYPE(enum) face , DYNAMIC_GL_TYPE(enum) pname , DYNAMIC_GL_TYPE(float) * params),(face , pname , params))
DYNAMIC_GL_FUNCTION_V(GetTexEnvfv,(DYNAMIC_GL_TYPE(enum) env , DYNAMIC_GL_TYPE(enum) pname , DYNAMIC_GL_TYPE(float) * params),(env , pname , params))
DYNAMIC_GL_FUNCTION_V(GetTexParameterfv,(DYNAMIC_GL_TYPE(enum) target , DYNAMIC_GL_TYPE(enum) pname , DYNAMIC_GL_TYPE(float) * params),(target , pname , params))
DYNAMIC_GL_FUNCTION_V(LightModelf,(DYNAMIC_GL_TYPE(enum) pname , DYNAMIC_GL_TYPE(float) param),(pname , param))
DYNAMIC_GL_FUNCTION_V(LightModelfv,(DYNAMIC_GL_TYPE(enum) pname , const DYNAMIC_GL_TYPE(float) * params),(pname , params))
DYNAMIC_GL_FUNCTION_V(Lightf,(DYNAMIC_GL_TYPE(enum) light , DYNAMIC_GL_TYPE(enum) pname , DYNAMIC_GL_TYPE(float) param),(light , pname , param))
DYNAMIC_GL_FUNCTION_V(Lightfv,(DYNAMIC_GL_TYPE(enum) light , DYNAMIC_GL_TYPE(enum) pname , const DYNAMIC_GL_TYPE(float) * params),(light , pname , params))
DYNAMIC_GL_FUNCTION_V(LineWidth,(DYNAMIC_GL_TYPE(float) width),(width))
DYNAMIC_GL_FUNCTION_V(LoadMatrixf,(const DYNAMIC_GL_TYPE(float) * m),(m))
DYNAMIC_GL_FUNCTION_V(Materialf,(DYNAMIC_GL_TYPE(enum) face , DYNAMIC_GL_TYPE(enum) pname , DYNAMIC_GL_TYPE(float) param),(face , pname , param))
DYNAMIC_GL_FUNCTION_V(Materialfv,(DYNAMIC_GL_TYPE(enum) face , DYNAMIC_GL_TYPE(enum) pname , const DYNAMIC_GL_TYPE(float) * params),(face , pname , params))
DYNAMIC_GL_FUNCTION_V(MultMatrixf,(const DYNAMIC_GL_TYPE(float) * m),(m))
DYNAMIC_GL_FUNCTION_V(MultiTexCoord4f,(DYNAMIC_GL_TYPE(enum) target , DYNAMIC_GL_TYPE(float) s , DYNAMIC_GL_TYPE(float) t , DYNAMIC_GL_TYPE(float) r , DYNAMIC_GL_TYPE(float) q),(target , s , t , r , q))
DYNAMIC_GL_FUNCTION_V(Normal3f,(DYNAMIC_GL_TYPE(float) nx , DYNAMIC_GL_TYPE(float) ny , DYNAMIC_GL_TYPE(float) nz),(nx , ny , nz))
DYNAMIC_GL_FUNCTION_V(Orthof,(DYNAMIC_GL_TYPE(float) left , DYNAMIC_GL_TYPE(float) right , DYNAMIC_GL_TYPE(float) bottom , DYNAMIC_GL_TYPE(float) top , DYNAMIC_GL_TYPE(float) zNear , DYNAMIC_GL_TYPE(float) zFar),(left , right , bottom , top , zNear , zFar))
DYNAMIC_GL_FUNCTION_V(PointParameterf,(DYNAMIC_GL_TYPE(enum) pname , DYNAMIC_GL_TYPE(float) param),(pname , param))
DYNAMIC_GL_FUNCTION_V(PointParameterfv,(DYNAMIC_GL_TYPE(enum) pname , const DYNAMIC_GL_TYPE(float) * params),(pname , params))
DYNAMIC_GL_FUNCTION_V(PointSize,(DYNAMIC_GL_TYPE(float) size),(size))
DYNAMIC_GL_FUNCTION_V(PolygonOffset,(DYNAMIC_GL_TYPE(float) factor , DYNAMIC_GL_TYPE(float) units),(factor , units))
DYNAMIC_GL_FUNCTION_V(Rotatef,(DYNAMIC_GL_TYPE(float) angle , DYNAMIC_GL_TYPE(float) x , DYNAMIC_GL_TYPE(float) y , DYNAMIC_GL_TYPE(float) z),(angle , x , y , z))
DYNAMIC_GL_FUNCTION_V(Scalef,(DYNAMIC_GL_TYPE(float) x , DYNAMIC_GL_TYPE(float) y , DYNAMIC_GL_TYPE(float) z),(x , y , z))
DYNAMIC_GL_FUNCTION_V(TexEnvf,(DYNAMIC_GL_TYPE(enum) target , DYNAMIC_GL_TYPE(enum) pname , DYNAMIC_GL_TYPE(float) param),(target , pname , param))
DYNAMIC_GL_FUNCTION_V(TexEnvfv,(DYNAMIC_GL_TYPE(enum) target , DYNAMIC_GL_TYPE(enum) pname , const DYNAMIC_GL_TYPE(float) * params),(target , pname , params))
DYNAMIC_GL_FUNCTION_V(TexParameterf,(DYNAMIC_GL_TYPE(enum) target , DYNAMIC_GL_TYPE(enum) pname , DYNAMIC_GL_TYPE(float) param),(target , pname , param))
DYNAMIC_GL_FUNCTION_V(TexParameterfv,(DYNAMIC_GL_TYPE(enum) target , DYNAMIC_GL_TYPE(enum) pname , const DYNAMIC_GL_TYPE(float) * params),(target , pname , params))
DYNAMIC_GL_FUNCTION_V(Translatef,(DYNAMIC_GL_TYPE(float) x , DYNAMIC_GL_TYPE(float) y , DYNAMIC_GL_TYPE(float) z),(x , y , z))
DYNAMIC_GL_FUNCTION_V(ActiveTexture,(DYNAMIC_GL_TYPE(enum) texture),(texture))
DYNAMIC_GL_FUNCTION_V(AlphaFuncx,(DYNAMIC_GL_TYPE(enum) func , DYNAMIC_GL_TYPE(clampx) ref),(func , ref))
DYNAMIC_GL_FUNCTION_V(BindBuffer,(DYNAMIC_GL_TYPE(enum) target , DYNAMIC_GL_TYPE(uint) buffer),(target , buffer))
DYNAMIC_GL_FUNCTION_V(BindTexture,(DYNAMIC_GL_TYPE(enum) target , DYNAMIC_GL_TYPE(uint) texture),(target , texture))
DYNAMIC_GL_FUNCTION_V(BlendFunc,(DYNAMIC_GL_TYPE(enum) sfactor , DYNAMIC_GL_TYPE(enum) dfactor),(sfactor , dfactor))
DYNAMIC_GL_FUNCTION_V(BufferData,(DYNAMIC_GL_TYPE(enum) target , DYNAMIC_GL_TYPE(sizeiptr) size , const DYNAMIC_GL_TYPE(void) * data , DYNAMIC_GL_TYPE(enum) usage),(target , size , data , usage))
DYNAMIC_GL_FUNCTION_V(BufferSubData,(DYNAMIC_GL_TYPE(enum) target , DYNAMIC_GL_TYPE(intptr) offset , DYNAMIC_GL_TYPE(sizeiptr) size , const DYNAMIC_GL_TYPE(void) * data),(target , offset , size , data))
DYNAMIC_GL_FUNCTION_V(Clear,(DYNAMIC_GL_TYPE(bitfield) mask),(mask))
DYNAMIC_GL_FUNCTION_V(ClearColorx,(DYNAMIC_GL_TYPE(clampx) red , DYNAMIC_GL_TYPE(clampx) green , DYNAMIC_GL_TYPE(clampx) blue , DYNAMIC_GL_TYPE(clampx) alpha),(red , green , blue , alpha))
DYNAMIC_GL_FUNCTION_V(ClearDepthx,(DYNAMIC_GL_TYPE(clampx) depth),(depth))
DYNAMIC_GL_FUNCTION_V(ClearStencil,(DYNAMIC_GL_TYPE(int) s),(s))
DYNAMIC_GL_FUNCTION_V(ClientActiveTexture,(DYNAMIC_GL_TYPE(enum) texture),(texture))
DYNAMIC_GL_FUNCTION_V(ClipPlanex,(DYNAMIC_GL_TYPE(enum) plane , const DYNAMIC_GL_TYPE(fixed) * equation),(plane , equation))
DYNAMIC_GL_FUNCTION_V(Color4ub,(DYNAMIC_GL_TYPE(ubyte) red , DYNAMIC_GL_TYPE(ubyte) green , DYNAMIC_GL_TYPE(ubyte) blue , DYNAMIC_GL_TYPE(ubyte) alpha),(red , green , blue , alpha))
DYNAMIC_GL_FUNCTION_V(Color4x,(DYNAMIC_GL_TYPE(fixed) red , DYNAMIC_GL_TYPE(fixed) green , DYNAMIC_GL_TYPE(fixed) blue , DYNAMIC_GL_TYPE(fixed) alpha),(red , green , blue , alpha))
DYNAMIC_GL_FUNCTION_V(ColorMask,(DYNAMIC_GL_TYPE(boolean) red , DYNAMIC_GL_TYPE(boolean) green , DYNAMIC_GL_TYPE(boolean) blue , DYNAMIC_GL_TYPE(boolean) alpha),(red , green , blue , alpha))
DYNAMIC_GL_FUNCTION_V(ColorPointer,(DYNAMIC_GL_TYPE(int) size , DYNAMIC_GL_TYPE(enum) type , DYNAMIC_GL_TYPE(sizei) stride , const DYNAMIC_GL_TYPE(void) * pointer),(size , type , stride , pointer))
DYNAMIC_GL_FUNCTION_V(CompressedTexImage2D,(DYNAMIC_GL_TYPE(enum) target , DYNAMIC_GL_TYPE(int) level , DYNAMIC_GL_TYPE(enum) internalformat , DYNAMIC_GL_TYPE(sizei) width , DYNAMIC_GL_TYPE(sizei) height , DYNAMIC_GL_TYPE(int) border , DYNAMIC_GL_TYPE(sizei) imageSize , const DYNAMIC_GL_TYPE(void) * data),(target , level , internalformat , width , height , border , imageSize , data))
DYNAMIC_GL_FUNCTION_V(CompressedTexSubImage2D,(DYNAMIC_GL_TYPE(enum) target , DYNAMIC_GL_TYPE(int) level , DYNAMIC_GL_TYPE(int) xoffset , DYNAMIC_GL_TYPE(int) yoffset , DYNAMIC_GL_TYPE(sizei) width , DYNAMIC_GL_TYPE(sizei) height , DYNAMIC_GL_TYPE(enum) format , DYNAMIC_GL_TYPE(sizei) imageSize , const DYNAMIC_GL_TYPE(void) * data),(target , level , xoffset , yoffset , width , height , format , imageSize , data))
DYNAMIC_GL_FUNCTION_V(CopyTexImage2D,(DYNAMIC_GL_TYPE(enum) target , DYNAMIC_GL_TYPE(int) level , DYNAMIC_GL_TYPE(enum) internalformat , DYNAMIC_GL_TYPE(int) x , DYNAMIC_GL_TYPE(int) y , DYNAMIC_GL_TYPE(sizei) width , DYNAMIC_GL_TYPE(sizei) height , DYNAMIC_GL_TYPE(int) border),(target , level , internalformat , x , y , width , height , border))
DYNAMIC_GL_FUNCTION_V(CopyTexSubImage2D,(DYNAMIC_GL_TYPE(enum) target , DYNAMIC_GL_TYPE(int) level , DYNAMIC_GL_TYPE(int) xoffset , DYNAMIC_GL_TYPE(int) yoffset , DYNAMIC_GL_TYPE(int) x , DYNAMIC_GL_TYPE(int) y , DYNAMIC_GL_TYPE(sizei) width , DYNAMIC_GL_TYPE(sizei) height),(target , level , xoffset , yoffset , x , y , width , height))
DYNAMIC_GL_FUNCTION_V(CullFace,(DYNAMIC_GL_TYPE(enum) mode),(mode))
DYNAMIC_GL_FUNCTION_V(DeleteBuffers,(DYNAMIC_GL_TYPE(sizei) n , const DYNAMIC_GL_TYPE(uint) * buffers),(n , buffers))
DYNAMIC_GL_FUNCTION_V(DeleteTextures,(DYNAMIC_GL_TYPE(sizei) n , const DYNAMIC_GL_TYPE(uint) * textures),(n , textures))
DYNAMIC_GL_FUNCTION_V(DepthFunc,(DYNAMIC_GL_TYPE(enum) func),(func))
DYNAMIC_GL_FUNCTION_V(DepthMask,(DYNAMIC_GL_TYPE(boolean) flag),(flag))
DYNAMIC_GL_FUNCTION_V(DepthRangex,(DYNAMIC_GL_TYPE(clampx) zNear , DYNAMIC_GL_TYPE(clampx) zFar),(zNear , zFar))
DYNAMIC_GL_FUNCTION_V(Disable,(DYNAMIC_GL_TYPE(enum) cap),(cap))
DYNAMIC_GL_FUNCTION_V(DisableClientState,(DYNAMIC_GL_TYPE(enum) array),(array))
DYNAMIC_GL_FUNCTION_V(DrawArrays,(DYNAMIC_GL_TYPE(enum) mode , DYNAMIC_GL_TYPE(int) first , DYNAMIC_GL_TYPE(sizei) count),(mode , first , count))
DYNAMIC_GL_FUNCTION_V(DrawElements,(DYNAMIC_GL_TYPE(enum) mode , DYNAMIC_GL_TYPE(sizei) count , DYNAMIC_GL_TYPE(enum) type , const DYNAMIC_GL_TYPE(void) * indices),(mode , count , type , indices))
DYNAMIC_GL_FUNCTION_V(Enable,(DYNAMIC_GL_TYPE(enum) cap),(cap))
DYNAMIC_GL_FUNCTION_V(EnableClientState,(DYNAMIC_GL_TYPE(enum) array),(array))
DYNAMIC_GL_FUNCTION_V(Finish,(),())
DYNAMIC_GL_FUNCTION_V(Flush,(),())
DYNAMIC_GL_FUNCTION_V(Fogx,(DYNAMIC_GL_TYPE(enum) pname , DYNAMIC_GL_TYPE(fixed) param),(pname , param))
DYNAMIC_GL_FUNCTION_V(Fogxv,(DYNAMIC_GL_TYPE(enum) pname , const DYNAMIC_GL_TYPE(fixed) * params),(pname , params))
DYNAMIC_GL_FUNCTION_V(FrontFace,(DYNAMIC_GL_TYPE(enum) mode),(mode))
DYNAMIC_GL_FUNCTION_V(Frustumx,(DYNAMIC_GL_TYPE(fixed) left , DYNAMIC_GL_TYPE(fixed) right , DYNAMIC_GL_TYPE(fixed) bottom , DYNAMIC_GL_TYPE(fixed) top , DYNAMIC_GL_TYPE(fixed) zNear , DYNAMIC_GL_TYPE(fixed) zFar),(left , right , bottom , top , zNear , zFar))
DYNAMIC_GL_FUNCTION_V(GetBooleanv,(DYNAMIC_GL_TYPE(enum) pname , DYNAMIC_GL_TYPE(boolean) * params),(pname , params))
DYNAMIC_GL_FUNCTION_V(GetBufferParameteriv,(DYNAMIC_GL_TYPE(enum) target , DYNAMIC_GL_TYPE(enum) pname , DYNAMIC_GL_TYPE(int) * params),(target , pname , params))
DYNAMIC_GL_FUNCTION_V(GenBuffers,(DYNAMIC_GL_TYPE(sizei) n , DYNAMIC_GL_TYPE(uint) * buffers),(n , buffers))
DYNAMIC_GL_FUNCTION_V(GenTextures,(DYNAMIC_GL_TYPE(sizei) n , DYNAMIC_GL_TYPE(uint) * textures),(n , textures))
DYNAMIC_GL_FUNCTION(DYNAMIC_GL_TYPE(enum),GetError,(),())
DYNAMIC_GL_FUNCTION_V(GetFixedv,(DYNAMIC_GL_TYPE(enum) pname , DYNAMIC_GL_TYPE(fixed) * params),(pname , params))
DYNAMIC_GL_FUNCTION_V(GetIntegerv,(DYNAMIC_GL_TYPE(enum) pname , DYNAMIC_GL_TYPE(int) * params),(pname , params))
DYNAMIC_GL_FUNCTION_V(GetLightxv,(DYNAMIC_GL_TYPE(enum) light , DYNAMIC_GL_TYPE(enum) pname , DYNAMIC_GL_TYPE(fixed) * params),(light , pname , params))
DYNAMIC_GL_FUNCTION_V(GetMaterialxv,(DYNAMIC_GL_TYPE(enum) face , DYNAMIC_GL_TYPE(enum) pname , DYNAMIC_GL_TYPE(fixed) * params),(face , pname , params))
DYNAMIC_GL_FUNCTION_V(GetPointerv,(DYNAMIC_GL_TYPE(enum) pname , DYNAMIC_GL_TYPE(void) * p1),(pname , p1))
DYNAMIC_GL_FUNCTION(DYNAMIC_GL_TYPE(ubyte*),GetString,(DYNAMIC_GL_TYPE(enum) name),(name))
DYNAMIC_GL_FUNCTION_V(GetTexEnviv,(DYNAMIC_GL_TYPE(enum) env , DYNAMIC_GL_TYPE(enum) pname , DYNAMIC_GL_TYPE(int) * params),(env , pname , params))
DYNAMIC_GL_FUNCTION_V(GetTexEnvxv,(DYNAMIC_GL_TYPE(enum) env , DYNAMIC_GL_TYPE(enum) pname , DYNAMIC_GL_TYPE(fixed) * params),(env , pname , params))
DYNAMIC_GL_FUNCTION_V(GetTexParameteriv,(DYNAMIC_GL_TYPE(enum) target , DYNAMIC_GL_TYPE(enum) pname , DYNAMIC_GL_TYPE(int) * params),(target , pname , params))
DYNAMIC_GL_FUNCTION_V(GetTexParameterxv,(DYNAMIC_GL_TYPE(enum) target , DYNAMIC_GL_TYPE(enum) pname , DYNAMIC_GL_TYPE(fixed) * params),(target , pname , params))
DYNAMIC_GL_FUNCTION_V(Hint,(DYNAMIC_GL_TYPE(enum) target , DYNAMIC_GL_TYPE(enum) mode),(target , mode))
DYNAMIC_GL_FUNCTION(DYNAMIC_GL_TYPE(boolean),IsBuffer,(DYNAMIC_GL_TYPE(uint) buffer),(buffer))
DYNAMIC_GL_FUNCTION(DYNAMIC_GL_TYPE(boolean),IsEnabled,(DYNAMIC_GL_TYPE(enum) cap),(cap))
DYNAMIC_GL_FUNCTION(DYNAMIC_GL_TYPE(boolean),IsTexture,(DYNAMIC_GL_TYPE(uint) texture),(texture))
DYNAMIC_GL_FUNCTION_V(LightModelx,(DYNAMIC_GL_TYPE(enum) pname , DYNAMIC_GL_TYPE(fixed) param),(pname , param))
DYNAMIC_GL_FUNCTION_V(LightModelxv,(DYNAMIC_GL_TYPE(enum) pname , const DYNAMIC_GL_TYPE(fixed) * params),(pname , params))
DYNAMIC_GL_FUNCTION_V(Lightx,(DYNAMIC_GL_TYPE(enum) light , DYNAMIC_GL_TYPE(enum) pname , DYNAMIC_GL_TYPE(fixed) param),(light , pname , param))
DYNAMIC_GL_FUNCTION_V(Lightxv,(DYNAMIC_GL_TYPE(enum) light , DYNAMIC_GL_TYPE(enum) pname , const DYNAMIC_GL_TYPE(fixed) * params),(light , pname , params))
DYNAMIC_GL_FUNCTION_V(LineWidthx,(DYNAMIC_GL_TYPE(fixed) width),(width))
DYNAMIC_GL_FUNCTION_V(LoadIdentity,(),())
DYNAMIC_GL_FUNCTION_V(LoadMatrixx,(const DYNAMIC_GL_TYPE(fixed) * m),(m))
DYNAMIC_GL_FUNCTION_V(LogicOp,(DYNAMIC_GL_TYPE(enum) opcode),(opcode))
DYNAMIC_GL_FUNCTION_V(Materialx,(DYNAMIC_GL_TYPE(enum) face , DYNAMIC_GL_TYPE(enum) pname , DYNAMIC_GL_TYPE(fixed) param),(face , pname , param))
DYNAMIC_GL_FUNCTION_V(Materialxv,(DYNAMIC_GL_TYPE(enum) face , DYNAMIC_GL_TYPE(enum) pname , const DYNAMIC_GL_TYPE(fixed) * params),(face , pname , params))
DYNAMIC_GL_FUNCTION_V(MatrixMode,(DYNAMIC_GL_TYPE(enum) mode),(mode))
DYNAMIC_GL_FUNCTION_V(MultMatrixx,(const DYNAMIC_GL_TYPE(fixed) * m),(m))
DYNAMIC_GL_FUNCTION_V(MultiTexCoord4x,(DYNAMIC_GL_TYPE(enum) target , DYNAMIC_GL_TYPE(fixed) s , DYNAMIC_GL_TYPE(fixed) t , DYNAMIC_GL_TYPE(fixed) r , DYNAMIC_GL_TYPE(fixed) q),(target , s , t , r , q))
DYNAMIC_GL_FUNCTION_V(Normal3x,(DYNAMIC_GL_TYPE(fixed) nx , DYNAMIC_GL_TYPE(fixed) ny , DYNAMIC_GL_TYPE(fixed) nz),(nx , ny , nz))
DYNAMIC_GL_FUNCTION_V(NormalPointer,(DYNAMIC_GL_TYPE(enum) type , DYNAMIC_GL_TYPE(sizei) stride , const DYNAMIC_GL_TYPE(void) * pointer),(type , stride , pointer))
DYNAMIC_GL_FUNCTION_V(Orthox,(DYNAMIC_GL_TYPE(fixed) left , DYNAMIC_GL_TYPE(fixed) right , DYNAMIC_GL_TYPE(fixed) bottom , DYNAMIC_GL_TYPE(fixed) top , DYNAMIC_GL_TYPE(fixed) zNear , DYNAMIC_GL_TYPE(fixed) zFar),(left , right , bottom , top , zNear , zFar))
DYNAMIC_GL_FUNCTION_V(PixelStorei,(DYNAMIC_GL_TYPE(enum) pname , DYNAMIC_GL_TYPE(int) param),(pname , param))
DYNAMIC_GL_FUNCTION_V(PointParameterx,(DYNAMIC_GL_TYPE(enum) pname , DYNAMIC_GL_TYPE(fixed) param),(pname , param))
DYNAMIC_GL_FUNCTION_V(PointParameterxv,(DYNAMIC_GL_TYPE(enum) pname , const DYNAMIC_GL_TYPE(fixed) * params),(pname , params))
DYNAMIC_GL_FUNCTION_V(PointSizex,(DYNAMIC_GL_TYPE(fixed) size),(size))
DYNAMIC_GL_FUNCTION_V(PolygonOffsetx,(DYNAMIC_GL_TYPE(fixed) factor , DYNAMIC_GL_TYPE(fixed) units),(factor , units))
DYNAMIC_GL_FUNCTION_V(PopMatrix,(),())
DYNAMIC_GL_FUNCTION_V(PushMatrix,(),())
DYNAMIC_GL_FUNCTION_V(ReadPixels,(DYNAMIC_GL_TYPE(int) x , DYNAMIC_GL_TYPE(int) y , DYNAMIC_GL_TYPE(sizei) width , DYNAMIC_GL_TYPE(sizei) height , DYNAMIC_GL_TYPE(enum) format , DYNAMIC_GL_TYPE(enum) type , DYNAMIC_GL_TYPE(void) * pixels),(x , y , width , height , format , type , pixels))
DYNAMIC_GL_FUNCTION_V(Rotatex,(DYNAMIC_GL_TYPE(fixed) angle , DYNAMIC_GL_TYPE(fixed) x , DYNAMIC_GL_TYPE(fixed) y , DYNAMIC_GL_TYPE(fixed) z),(angle , x , y , z))
DYNAMIC_GL_FUNCTION_V(SampleCoverage,(DYNAMIC_GL_TYPE(clampf) value , DYNAMIC_GL_TYPE(boolean) invert),(value , invert))
DYNAMIC_GL_FUNCTION_V(SampleCoveragex,(DYNAMIC_GL_TYPE(clampx) value , DYNAMIC_GL_TYPE(boolean) invert),(value , invert))
DYNAMIC_GL_FUNCTION_V(Scalex,(DYNAMIC_GL_TYPE(fixed) x , DYNAMIC_GL_TYPE(fixed) y , DYNAMIC_GL_TYPE(fixed) z),(x , y , z))
DYNAMIC_GL_FUNCTION_V(Scissor,(DYNAMIC_GL_TYPE(int) x , DYNAMIC_GL_TYPE(int) y , DYNAMIC_GL_TYPE(sizei) width , DYNAMIC_GL_TYPE(sizei) height),(x , y , width , height))
DYNAMIC_GL_FUNCTION_V(ShadeModel,(DYNAMIC_GL_TYPE(enum) mode),(mode))
DYNAMIC_GL_FUNCTION_V(StencilFunc,(DYNAMIC_GL_TYPE(enum) func , DYNAMIC_GL_TYPE(int) ref , DYNAMIC_GL_TYPE(uint) mask),(func , ref , mask))
DYNAMIC_GL_FUNCTION_V(StencilMask,(DYNAMIC_GL_TYPE(uint) mask),(mask))
DYNAMIC_GL_FUNCTION_V(StencilOp,(DYNAMIC_GL_TYPE(enum) fail , DYNAMIC_GL_TYPE(enum) zfail , DYNAMIC_GL_TYPE(enum) zpass),(fail , zfail , zpass))
DYNAMIC_GL_FUNCTION_V(TexCoordPointer,(DYNAMIC_GL_TYPE(int) size , DYNAMIC_GL_TYPE(enum) type , DYNAMIC_GL_TYPE(sizei) stride , const DYNAMIC_GL_TYPE(void) * pointer),(size , type , stride , pointer))
DYNAMIC_GL_FUNCTION_V(TexEnvi,(DYNAMIC_GL_TYPE(enum) target , DYNAMIC_GL_TYPE(enum) pname , DYNAMIC_GL_TYPE(int) param),(target , pname , param))
DYNAMIC_GL_FUNCTION_V(TexEnvx,(DYNAMIC_GL_TYPE(enum) target , DYNAMIC_GL_TYPE(enum) pname , DYNAMIC_GL_TYPE(fixed) param),(target , pname , param))
DYNAMIC_GL_FUNCTION_V(TexEnviv,(DYNAMIC_GL_TYPE(enum) target , DYNAMIC_GL_TYPE(enum) pname , const DYNAMIC_GL_TYPE(int) * params),(target , pname , params))
DYNAMIC_GL_FUNCTION_V(TexEnvxv,(DYNAMIC_GL_TYPE(enum) target , DYNAMIC_GL_TYPE(enum) pname , const DYNAMIC_GL_TYPE(fixed) * params),(target , pname , params))
DYNAMIC_GL_FUNCTION_V(TexImage2D,(DYNAMIC_GL_TYPE(enum) target , DYNAMIC_GL_TYPE(int) level , DYNAMIC_GL_TYPE(int) internalformat , DYNAMIC_GL_TYPE(sizei) width , DYNAMIC_GL_TYPE(sizei) height , DYNAMIC_GL_TYPE(int) border , DYNAMIC_GL_TYPE(enum) format , DYNAMIC_GL_TYPE(enum) type , const DYNAMIC_GL_TYPE(void) * pixels),(target , level , internalformat , width , height , border , format , type , pixels))
DYNAMIC_GL_FUNCTION_V(TexParameteri,(DYNAMIC_GL_TYPE(enum) target , DYNAMIC_GL_TYPE(enum) pname , DYNAMIC_GL_TYPE(int) param),(target , pname , param))
DYNAMIC_GL_FUNCTION_V(TexParameterx,(DYNAMIC_GL_TYPE(enum) target , DYNAMIC_GL_TYPE(enum) pname , DYNAMIC_GL_TYPE(fixed) param),(target , pname , param))
DYNAMIC_GL_FUNCTION_V(TexParameteriv,(DYNAMIC_GL_TYPE(enum) target , DYNAMIC_GL_TYPE(enum) pname , const DYNAMIC_GL_TYPE(int) * params),(target , pname , params))
DYNAMIC_GL_FUNCTION_V(TexParameterxv,(DYNAMIC_GL_TYPE(enum) target , DYNAMIC_GL_TYPE(enum) pname , const DYNAMIC_GL_TYPE(fixed) * params),(target , pname , params))
DYNAMIC_GL_FUNCTION_V(TexSubImage2D,(DYNAMIC_GL_TYPE(enum) target , DYNAMIC_GL_TYPE(int) level , DYNAMIC_GL_TYPE(int) xoffset , DYNAMIC_GL_TYPE(int) yoffset , DYNAMIC_GL_TYPE(sizei) width , DYNAMIC_GL_TYPE(sizei) height , DYNAMIC_GL_TYPE(enum) format , DYNAMIC_GL_TYPE(enum) type , const DYNAMIC_GL_TYPE(void) * pixels),(target , level , xoffset , yoffset , width , height , format , type , pixels))
DYNAMIC_GL_FUNCTION_V(Translatex,(DYNAMIC_GL_TYPE(fixed) x , DYNAMIC_GL_TYPE(fixed) y , DYNAMIC_GL_TYPE(fixed) z),(x , y , z))
DYNAMIC_GL_FUNCTION_V(VertexPointer,(DYNAMIC_GL_TYPE(int) size , DYNAMIC_GL_TYPE(enum) type , DYNAMIC_GL_TYPE(sizei) stride , const DYNAMIC_GL_TYPE(void) * pointer),(size , type , stride , pointer))
DYNAMIC_GL_FUNCTION_V(Viewport,(DYNAMIC_GL_TYPE(int) x , DYNAMIC_GL_TYPE(int) y , DYNAMIC_GL_TYPE(sizei) width , DYNAMIC_GL_TYPE(sizei) height),(x , y , width , height))
#endif /*USE_DYNAMIC_GL_CORE*/

/*OES_query_matrix*/
#ifdef USE_DYNAMIC_GL_OES_query_matrix
DYNAMIC_GL_FEATURE(OES_query_matrix)
#endif /*USE_DYNAMIC_GL_OES_query_matrix*/

/*APIENTRYP*/
#ifdef USE_DYNAMIC_GL_APIENTRYP
DYNAMIC_GL_FEATURE(APIENTRYP)
#endif /*USE_DYNAMIC_GL_APIENTRYP*/

/*OES_stencil_wrap*/
#ifdef USE_DYNAMIC_GL_OES_stencil_wrap
DYNAMIC_GL_FEATURE(OES_stencil_wrap)
DYNAMIC_GL_CONSTANT(INCR_WRAP_OES,0x8507)
DYNAMIC_GL_CONSTANT(DECR_WRAP_OES,0x8508)
#endif /*USE_DYNAMIC_GL_OES_stencil_wrap*/

/*EXT_texture_format_BGRA8888*/
#ifdef USE_DYNAMIC_GL_EXT_texture_format_BGRA8888
DYNAMIC_GL_FEATURE(EXT_texture_format_BGRA8888)
DYNAMIC_GL_CONSTANT(BGRA_EXT,0x80E1)
#endif /*USE_DYNAMIC_GL_EXT_texture_format_BGRA8888*/

/*OES_fbo_render_mipmap*/
#ifdef USE_DYNAMIC_GL_OES_fbo_render_mipmap
DYNAMIC_GL_FEATURE(OES_fbo_render_mipmap)
#endif /*USE_DYNAMIC_GL_OES_fbo_render_mipmap*/

/*IMG_multisampled_render_to_texture*/
#ifdef USE_DYNAMIC_GL_IMG_multisampled_render_to_texture
DYNAMIC_GL_FEATURE(IMG_multisampled_render_to_texture)
DYNAMIC_GL_CONSTANT(RENDERBUFFER_SAMPLES_IMG,0x9133)
DYNAMIC_GL_CONSTANT(FRAMEBUFFER_INCOMPLETE_MULTISAMPLE_IMG,0x9134)
DYNAMIC_GL_CONSTANT(MAX_SAMPLES_IMG,0x9135)
DYNAMIC_GL_CONSTANT(TEXTURE_SAMPLES_IMG,0x9136)
DYNAMIC_GL_FUNCTION_V(RenderbufferStorageMultisampleIMG,(DYNAMIC_GL_TYPE(enum) target , DYNAMIC_GL_TYPE(sizei) samples , DYNAMIC_GL_TYPE(enum) internalformat , DYNAMIC_GL_TYPE(sizei) width , DYNAMIC_GL_TYPE(sizei) height),(target , samples , internalformat , width , height))
DYNAMIC_GL_FUNCTION_V(FramebufferTexture2DMultisampleIMG,(DYNAMIC_GL_TYPE(enum) target , DYNAMIC_GL_TYPE(enum) attachment , DYNAMIC_GL_TYPE(enum) textarget , DYNAMIC_GL_TYPE(uint) texture , DYNAMIC_GL_TYPE(int) level , DYNAMIC_GL_TYPE(sizei) samples),(target , attachment , textarget , texture , level , samples))
#endif /*USE_DYNAMIC_GL_IMG_multisampled_render_to_texture*/

/*EXT_map_buffer_range*/
#ifdef USE_DYNAMIC_GL_EXT_map_buffer_range
DYNAMIC_GL_FEATURE(EXT_map_buffer_range)
DYNAMIC_GL_CONSTANT(MAP_READ_BIT_EXT,0x0001)
DYNAMIC_GL_CONSTANT(MAP_WRITE_BIT_EXT,0x0002)
DYNAMIC_GL_CONSTANT(MAP_INVALIDATE_RANGE_BIT_EXT,0x0004)
DYNAMIC_GL_CONSTANT(MAP_INVALIDATE_BUFFER_BIT_EXT,0x0008)
DYNAMIC_GL_CONSTANT(MAP_FLUSH_EXPLICIT_BIT_EXT,0x0010)
DYNAMIC_GL_CONSTANT(MAP_UNSYNCHRONIZED_BIT_EXT,0x0020)
DYNAMIC_GL_FUNCTION_V(FlushMappedBufferRangeEXT,(DYNAMIC_GL_TYPE(enum) target , DYNAMIC_GL_TYPE(intptr) offset , DYNAMIC_GL_TYPE(sizeiptr) length),(target , offset , length))
#endif /*USE_DYNAMIC_GL_EXT_map_buffer_range*/

/*EXT_texture_lod_bias*/
#ifdef USE_DYNAMIC_GL_EXT_texture_lod_bias
DYNAMIC_GL_FEATURE(EXT_texture_lod_bias)
DYNAMIC_GL_CONSTANT(MAX_TEXTURE_LOD_BIAS_EXT,0x84FD)
DYNAMIC_GL_CONSTANT(TEXTURE_FILTER_CONTROL_EXT,0x8500)
DYNAMIC_GL_CONSTANT(TEXTURE_LOD_BIAS_EXT,0x8501)
#endif /*USE_DYNAMIC_GL_EXT_texture_lod_bias*/

/*EXT_texture_compression_dxt1*/
#ifdef USE_DYNAMIC_GL_EXT_texture_compression_dxt1
DYNAMIC_GL_FEATURE(EXT_texture_compression_dxt1)
DYNAMIC_GL_CONSTANT(COMPRESSED_RGB_S3TC_DXT1_EXT,0x83F0)
DYNAMIC_GL_CONSTANT(COMPRESSED_RGBA_S3TC_DXT1_EXT,0x83F1)
#endif /*USE_DYNAMIC_GL_EXT_texture_compression_dxt1*/

/*OES_blend_equation_separate*/
#ifdef USE_DYNAMIC_GL_OES_blend_equation_separate
DYNAMIC_GL_FEATURE(OES_blend_equation_separate)
DYNAMIC_GL_CONSTANT(BLEND_EQUATION_RGB_OES,0x8009)
DYNAMIC_GL_CONSTANT(BLEND_EQUATION_ALPHA_OES,0x883D)
DYNAMIC_GL_FUNCTION_V(BlendEquationSeparateOES,(DYNAMIC_GL_TYPE(enum) modeRGB , DYNAMIC_GL_TYPE(enum) modeAlpha),(modeRGB , modeAlpha))
#endif /*USE_DYNAMIC_GL_OES_blend_equation_separate*/

/*OES_texture_mirrored_repeat*/
#ifdef USE_DYNAMIC_GL_OES_texture_mirrored_repeat
DYNAMIC_GL_FEATURE(OES_texture_mirrored_repeat)
DYNAMIC_GL_CONSTANT(MIRRORED_REPEAT_OES,0x8370)
#endif /*USE_DYNAMIC_GL_OES_texture_mirrored_repeat*/

/*OES_framebuffer_object*/
#ifdef USE_DYNAMIC_GL_OES_framebuffer_object
DYNAMIC_GL_FEATURE(OES_framebuffer_object)
DYNAMIC_GL_CONSTANT(FRAMEBUFFER_OES,0x8D40)
DYNAMIC_GL_CONSTANT(RENDERBUFFER_OES,0x8D41)
DYNAMIC_GL_CONSTANT(RGBA4_OES,0x8056)
DYNAMIC_GL_CONSTANT(RGB5_A1_OES,0x8057)
DYNAMIC_GL_CONSTANT(RGB565_OES,0x8D62)
DYNAMIC_GL_CONSTANT(DEPTH_COMPONENT16_OES,0x81A5)
DYNAMIC_GL_CONSTANT(RENDERBUFFER_WIDTH_OES,0x8D42)
DYNAMIC_GL_CONSTANT(RENDERBUFFER_HEIGHT_OES,0x8D43)
DYNAMIC_GL_CONSTANT(RENDERBUFFER_INTERNAL_FORMAT_OES,0x8D44)
DYNAMIC_GL_CONSTANT(RENDERBUFFER_RED_SIZE_OES,0x8D50)
DYNAMIC_GL_CONSTANT(RENDERBUFFER_GREEN_SIZE_OES,0x8D51)
DYNAMIC_GL_CONSTANT(RENDERBUFFER_BLUE_SIZE_OES,0x8D52)
DYNAMIC_GL_CONSTANT(RENDERBUFFER_ALPHA_SIZE_OES,0x8D53)
DYNAMIC_GL_CONSTANT(RENDERBUFFER_DEPTH_SIZE_OES,0x8D54)
DYNAMIC_GL_CONSTANT(RENDERBUFFER_STENCIL_SIZE_OES,0x8D55)
DYNAMIC_GL_CONSTANT(FRAMEBUFFER_ATTACHMENT_OBJECT_TYPE_OES,0x8CD0)
DYNAMIC_GL_CONSTANT(FRAMEBUFFER_ATTACHMENT_OBJECT_NAME_OES,0x8CD1)
DYNAMIC_GL_CONSTANT(FRAMEBUFFER_ATTACHMENT_TEXTURE_LEVEL_OES,0x8CD2)
DYNAMIC_GL_CONSTANT(FRAMEBUFFER_ATTACHMENT_TEXTURE_CUBE_MAP_FACE_OES,0x8CD3)
DYNAMIC_GL_CONSTANT(COLOR_ATTACHMENT0_OES,0x8CE0)
DYNAMIC_GL_CONSTANT(DEPTH_ATTACHMENT_OES,0x8D00)
DYNAMIC_GL_CONSTANT(STENCIL_ATTACHMENT_OES,0x8D20)
DYNAMIC_GL_CONSTANT(FRAMEBUFFER_COMPLETE_OES,0x8CD5)
DYNAMIC_GL_CONSTANT(FRAMEBUFFER_INCOMPLETE_ATTACHMENT_OES,0x8CD6)
DYNAMIC_GL_CONSTANT(FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT_OES,0x8CD7)
DYNAMIC_GL_CONSTANT(FRAMEBUFFER_INCOMPLETE_DIMENSIONS_OES,0x8CD9)
DYNAMIC_GL_CONSTANT(FRAMEBUFFER_INCOMPLETE_FORMATS_OES,0x8CDA)
DYNAMIC_GL_CONSTANT(FRAMEBUFFER_UNSUPPORTED_OES,0x8CDD)
DYNAMIC_GL_CONSTANT(FRAMEBUFFER_BINDING_OES,0x8CA6)
DYNAMIC_GL_CONSTANT(RENDERBUFFER_BINDING_OES,0x8CA7)
DYNAMIC_GL_CONSTANT(MAX_RENDERBUFFER_SIZE_OES,0x84E8)
DYNAMIC_GL_CONSTANT(INVALID_FRAMEBUFFER_OPERATION_OES,0x0506)
DYNAMIC_GL_FUNCTION(DYNAMIC_GL_TYPE(boolean),IsRenderbufferOES,(DYNAMIC_GL_TYPE(uint) renderbuffer),(renderbuffer))
DYNAMIC_GL_FUNCTION_V(BindRenderbufferOES,(DYNAMIC_GL_TYPE(enum) target , DYNAMIC_GL_TYPE(uint) renderbuffer),(target , renderbuffer))
DYNAMIC_GL_FUNCTION_V(DeleteRenderbuffersOES,(DYNAMIC_GL_TYPE(sizei) n , const DYNAMIC_GL_TYPE(uint) * renderbuffers),(n , renderbuffers))
DYNAMIC_GL_FUNCTION_V(GenRenderbuffersOES,(DYNAMIC_GL_TYPE(sizei) n , DYNAMIC_GL_TYPE(uint) * renderbuffers),(n , renderbuffers))
DYNAMIC_GL_FUNCTION_V(RenderbufferStorageOES,(DYNAMIC_GL_TYPE(enum) target , DYNAMIC_GL_TYPE(enum) internalformat , DYNAMIC_GL_TYPE(sizei) width , DYNAMIC_GL_TYPE(sizei) height),(target , internalformat , width , height))
DYNAMIC_GL_FUNCTION_V(GetRenderbufferParameterivOES,(DYNAMIC_GL_TYPE(enum) target , DYNAMIC_GL_TYPE(enum) pname , DYNAMIC_GL_TYPE(int) * params),(target , pname , params))
DYNAMIC_GL_FUNCTION(DYNAMIC_GL_TYPE(boolean),IsFramebufferOES,(DYNAMIC_GL_TYPE(uint) framebuffer),(framebuffer))
DYNAMIC_GL_FUNCTION_V(BindFramebufferOES,(DYNAMIC_GL_TYPE(enum) target , DYNAMIC_GL_TYPE(uint) framebuffer),(target , framebuffer))
DYNAMIC_GL_FUNCTION_V(DeleteFramebuffersOES,(DYNAMIC_GL_TYPE(sizei) n , const DYNAMIC_GL_TYPE(uint) * framebuffers),(n , framebuffers))
DYNAMIC_GL_FUNCTION_V(GenFramebuffersOES,(DYNAMIC_GL_TYPE(sizei) n , DYNAMIC_GL_TYPE(uint) * framebuffers),(n , framebuffers))
DYNAMIC_GL_FUNCTION(DYNAMIC_GL_TYPE(enum),CheckFramebufferStatusOES,(DYNAMIC_GL_TYPE(enum) target),(target))
DYNAMIC_GL_FUNCTION_V(FramebufferRenderbufferOES,(DYNAMIC_GL_TYPE(enum) target , DYNAMIC_GL_TYPE(enum) attachment , DYNAMIC_GL_TYPE(enum) renderbuffertarget , DYNAMIC_GL_TYPE(uint) renderbuffer),(target , attachment , renderbuffertarget , renderbuffer))
DYNAMIC_GL_FUNCTION_V(FramebufferTexture2DOES,(DYNAMIC_GL_TYPE(enum) target , DYNAMIC_GL_TYPE(enum) attachment , DYNAMIC_GL_TYPE(enum) textarget , DYNAMIC_GL_TYPE(uint) texture , DYNAMIC_GL_TYPE(int) level),(target , attachment , textarget , texture , level))
DYNAMIC_GL_FUNCTION_V(GetFramebufferAttachmentParameterivOES,(DYNAMIC_GL_TYPE(enum) target , DYNAMIC_GL_TYPE(enum) attachment , DYNAMIC_GL_TYPE(enum) pname , DYNAMIC_GL_TYPE(int) * params),(target , attachment , pname , params))
DYNAMIC_GL_FUNCTION_V(GenerateMipmapOES,(DYNAMIC_GL_TYPE(enum) target),(target))
#endif /*USE_DYNAMIC_GL_OES_framebuffer_object*/

/*APPLE_copy_texture_levels*/
#ifdef USE_DYNAMIC_GL_APPLE_copy_texture_levels
DYNAMIC_GL_FEATURE(APPLE_copy_texture_levels)
DYNAMIC_GL_FUNCTION_V(CopyTextureLevelsAPPLE,(DYNAMIC_GL_TYPE(uint) destinationTexture , DYNAMIC_GL_TYPE(uint) sourceTexture , DYNAMIC_GL_TYPE(int) sourceBaseLevel , DYNAMIC_GL_TYPE(sizei) sourceLevelCount),(destinationTexture , sourceTexture , sourceBaseLevel , sourceLevelCount))
#endif /*USE_DYNAMIC_GL_APPLE_copy_texture_levels*/

/*AMD_compressed_3DC_texture*/
#ifdef USE_DYNAMIC_GL_AMD_compressed_3DC_texture
DYNAMIC_GL_FEATURE(AMD_compressed_3DC_texture)
DYNAMIC_GL_CONSTANT(_3DC_X_AMD,0x87F9)
DYNAMIC_GL_CONSTANT(_3DC_XY_AMD,0x87FA)
#endif /*USE_DYNAMIC_GL_AMD_compressed_3DC_texture*/

/*IMG_read_format*/
#ifdef USE_DYNAMIC_GL_IMG_read_format
DYNAMIC_GL_FEATURE(IMG_read_format)
DYNAMIC_GL_CONSTANT(BGRA_IMG,0x80E1)
DYNAMIC_GL_CONSTANT(UNSIGNED_SHORT_4_4_4_4_REV_IMG,0x8365)
#endif /*USE_DYNAMIC_GL_IMG_read_format*/

/*OES_EGL_image_external*/
#ifdef USE_DYNAMIC_GL_OES_EGL_image_external
DYNAMIC_GL_FEATURE(OES_EGL_image_external)
DYNAMIC_GL_CONSTANT(TEXTURE_EXTERNAL_OES,0x8D65)
DYNAMIC_GL_CONSTANT(TEXTURE_BINDING_EXTERNAL_OES,0x8D67)
DYNAMIC_GL_CONSTANT(REQUIRED_TEXTURE_IMAGE_UNITS_OES,0x8D68)
#endif /*USE_DYNAMIC_GL_OES_EGL_image_external*/

/*OES_compressed_ETC1_RGB8_texture*/
#ifdef USE_DYNAMIC_GL_OES_compressed_ETC1_RGB8_texture
DYNAMIC_GL_FEATURE(OES_compressed_ETC1_RGB8_texture)
DYNAMIC_GL_CONSTANT(ETC1_RGB8_OES,0x8D64)
#endif /*USE_DYNAMIC_GL_OES_compressed_ETC1_RGB8_texture*/

/*OES_depth24*/
#ifdef USE_DYNAMIC_GL_OES_depth24
DYNAMIC_GL_FEATURE(OES_depth24)
DYNAMIC_GL_CONSTANT(DEPTH_COMPONENT24_OES,0x81A6)
#endif /*USE_DYNAMIC_GL_OES_depth24*/

/*IMG_texture_env_enhanced_fixed_function*/
#ifdef USE_DYNAMIC_GL_IMG_texture_env_enhanced_fixed_function
DYNAMIC_GL_FEATURE(IMG_texture_env_enhanced_fixed_function)
DYNAMIC_GL_CONSTANT(MODULATE_COLOR_IMG,0x8C04)
DYNAMIC_GL_CONSTANT(RECIP_ADD_SIGNED_ALPHA_IMG,0x8C05)
DYNAMIC_GL_CONSTANT(TEXTURE_ALPHA_MODULATE_IMG,0x8C06)
DYNAMIC_GL_CONSTANT(FACTOR_ALPHA_MODULATE_IMG,0x8C07)
DYNAMIC_GL_CONSTANT(FRAGMENT_ALPHA_MODULATE_IMG,0x8C08)
DYNAMIC_GL_CONSTANT(ADD_BLEND_IMG,0x8C09)
DYNAMIC_GL_CONSTANT(DOT3_RGBA_IMG,0x86AF)
#endif /*USE_DYNAMIC_GL_IMG_texture_env_enhanced_fixed_function*/

/*OES_element_index_uint*/
#ifdef USE_DYNAMIC_GL_OES_element_index_uint
DYNAMIC_GL_FEATURE(OES_element_index_uint)
DYNAMIC_GL_CONSTANT(UNSIGNED_INT,0x1405)
#endif /*USE_DYNAMIC_GL_OES_element_index_uint*/

/*QCOM_writeonly_rendering*/
#ifdef USE_DYNAMIC_GL_QCOM_writeonly_rendering
DYNAMIC_GL_FEATURE(QCOM_writeonly_rendering)
DYNAMIC_GL_CONSTANT(WRITEONLY_RENDERING_QCOM,0x8823)
#endif /*USE_DYNAMIC_GL_QCOM_writeonly_rendering*/

/*ARM_rgba8*/
#ifdef USE_DYNAMIC_GL_ARM_rgba8
DYNAMIC_GL_FEATURE(ARM_rgba8)
#endif /*USE_DYNAMIC_GL_ARM_rgba8*/

/*QCOM_tiled_rendering*/
#ifdef USE_DYNAMIC_GL_QCOM_tiled_rendering
DYNAMIC_GL_FEATURE(QCOM_tiled_rendering)
DYNAMIC_GL_CONSTANT(COLOR_BUFFER_BIT0_QCOM,0x00000001)
DYNAMIC_GL_CONSTANT(COLOR_BUFFER_BIT1_QCOM,0x00000002)
DYNAMIC_GL_CONSTANT(COLOR_BUFFER_BIT2_QCOM,0x00000004)
DYNAMIC_GL_CONSTANT(COLOR_BUFFER_BIT3_QCOM,0x00000008)
DYNAMIC_GL_CONSTANT(COLOR_BUFFER_BIT4_QCOM,0x00000010)
DYNAMIC_GL_CONSTANT(COLOR_BUFFER_BIT5_QCOM,0x00000020)
DYNAMIC_GL_CONSTANT(COLOR_BUFFER_BIT6_QCOM,0x00000040)
DYNAMIC_GL_CONSTANT(COLOR_BUFFER_BIT7_QCOM,0x00000080)
DYNAMIC_GL_CONSTANT(DEPTH_BUFFER_BIT0_QCOM,0x00000100)
DYNAMIC_GL_CONSTANT(DEPTH_BUFFER_BIT1_QCOM,0x00000200)
DYNAMIC_GL_CONSTANT(DEPTH_BUFFER_BIT2_QCOM,0x00000400)
DYNAMIC_GL_CONSTANT(DEPTH_BUFFER_BIT3_QCOM,0x00000800)
DYNAMIC_GL_CONSTANT(DEPTH_BUFFER_BIT4_QCOM,0x00001000)
DYNAMIC_GL_CONSTANT(DEPTH_BUFFER_BIT5_QCOM,0x00002000)
DYNAMIC_GL_CONSTANT(DEPTH_BUFFER_BIT6_QCOM,0x00004000)
DYNAMIC_GL_CONSTANT(DEPTH_BUFFER_BIT7_QCOM,0x00008000)
DYNAMIC_GL_CONSTANT(STENCIL_BUFFER_BIT0_QCOM,0x00010000)
DYNAMIC_GL_CONSTANT(STENCIL_BUFFER_BIT1_QCOM,0x00020000)
DYNAMIC_GL_CONSTANT(STENCIL_BUFFER_BIT2_QCOM,0x00040000)
DYNAMIC_GL_CONSTANT(STENCIL_BUFFER_BIT3_QCOM,0x00080000)
DYNAMIC_GL_CONSTANT(STENCIL_BUFFER_BIT4_QCOM,0x00100000)
DYNAMIC_GL_CONSTANT(STENCIL_BUFFER_BIT5_QCOM,0x00200000)
DYNAMIC_GL_CONSTANT(STENCIL_BUFFER_BIT6_QCOM,0x00400000)
DYNAMIC_GL_CONSTANT(STENCIL_BUFFER_BIT7_QCOM,0x00800000)
DYNAMIC_GL_CONSTANT(MULTISAMPLE_BUFFER_BIT0_QCOM,0x01000000)
DYNAMIC_GL_CONSTANT(MULTISAMPLE_BUFFER_BIT1_QCOM,0x02000000)
DYNAMIC_GL_CONSTANT(MULTISAMPLE_BUFFER_BIT2_QCOM,0x04000000)
DYNAMIC_GL_CONSTANT(MULTISAMPLE_BUFFER_BIT3_QCOM,0x08000000)
DYNAMIC_GL_CONSTANT(MULTISAMPLE_BUFFER_BIT4_QCOM,0x10000000)
DYNAMIC_GL_CONSTANT(MULTISAMPLE_BUFFER_BIT5_QCOM,0x20000000)
DYNAMIC_GL_CONSTANT(MULTISAMPLE_BUFFER_BIT6_QCOM,0x40000000)
DYNAMIC_GL_CONSTANT(MULTISAMPLE_BUFFER_BIT7_QCOM,0x80000000)
DYNAMIC_GL_FUNCTION_V(StartTilingQCOM,(DYNAMIC_GL_TYPE(uint) x , DYNAMIC_GL_TYPE(uint) y , DYNAMIC_GL_TYPE(uint) width , DYNAMIC_GL_TYPE(uint) height , DYNAMIC_GL_TYPE(bitfield) preserveMask),(x , y , width , height , preserveMask))
DYNAMIC_GL_FUNCTION_V(EndTilingQCOM,(DYNAMIC_GL_TYPE(bitfield) preserveMask),(preserveMask))
#endif /*USE_DYNAMIC_GL_QCOM_tiled_rendering*/

/*OES_rgb8_rgba8*/
#ifdef USE_DYNAMIC_GL_OES_rgb8_rgba8
DYNAMIC_GL_FEATURE(OES_rgb8_rgba8)
DYNAMIC_GL_CONSTANT(RGB8_OES,0x8051)
DYNAMIC_GL_CONSTANT(RGBA8_OES,0x8058)
#endif /*USE_DYNAMIC_GL_OES_rgb8_rgba8*/

/*OES_texture_cube_map*/
#ifdef USE_DYNAMIC_GL_OES_texture_cube_map
DYNAMIC_GL_FEATURE(OES_texture_cube_map)
DYNAMIC_GL_CONSTANT(NORMAL_MAP_OES,0x8511)
DYNAMIC_GL_CONSTANT(REFLECTION_MAP_OES,0x8512)
DYNAMIC_GL_CONSTANT(TEXTURE_CUBE_MAP_OES,0x8513)
DYNAMIC_GL_CONSTANT(TEXTURE_BINDING_CUBE_MAP_OES,0x8514)
DYNAMIC_GL_CONSTANT(TEXTURE_CUBE_MAP_POSITIVE_X_OES,0x8515)
DYNAMIC_GL_CONSTANT(TEXTURE_CUBE_MAP_NEGATIVE_X_OES,0x8516)
DYNAMIC_GL_CONSTANT(TEXTURE_CUBE_MAP_POSITIVE_Y_OES,0x8517)
DYNAMIC_GL_CONSTANT(TEXTURE_CUBE_MAP_NEGATIVE_Y_OES,0x8518)
DYNAMIC_GL_CONSTANT(TEXTURE_CUBE_MAP_POSITIVE_Z_OES,0x8519)
DYNAMIC_GL_CONSTANT(TEXTURE_CUBE_MAP_NEGATIVE_Z_OES,0x851A)
DYNAMIC_GL_CONSTANT(MAX_CUBE_MAP_TEXTURE_SIZE_OES,0x851C)
DYNAMIC_GL_CONSTANT(TEXTURE_GEN_MODE_OES,0x2500)
DYNAMIC_GL_CONSTANT(TEXTURE_GEN_STR_OES,0x8D60)
DYNAMIC_GL_FUNCTION_V(TexGenfOES,(DYNAMIC_GL_TYPE(enum) coord , DYNAMIC_GL_TYPE(enum) pname , DYNAMIC_GL_TYPE(float) param),(coord , pname , param))
DYNAMIC_GL_FUNCTION_V(TexGenfvOES,(DYNAMIC_GL_TYPE(enum) coord , DYNAMIC_GL_TYPE(enum) pname , const DYNAMIC_GL_TYPE(float) * params),(coord , pname , params))
DYNAMIC_GL_FUNCTION_V(TexGeniOES,(DYNAMIC_GL_TYPE(enum) coord , DYNAMIC_GL_TYPE(enum) pname , DYNAMIC_GL_TYPE(int) param),(coord , pname , param))
DYNAMIC_GL_FUNCTION_V(TexGenivOES,(DYNAMIC_GL_TYPE(enum) coord , DYNAMIC_GL_TYPE(enum) pname , const DYNAMIC_GL_TYPE(int) * params),(coord , pname , params))
DYNAMIC_GL_FUNCTION_V(TexGenxOES,(DYNAMIC_GL_TYPE(enum) coord , DYNAMIC_GL_TYPE(enum) pname , DYNAMIC_GL_TYPE(fixed) param),(coord , pname , param))
DYNAMIC_GL_FUNCTION_V(TexGenxvOES,(DYNAMIC_GL_TYPE(enum) coord , DYNAMIC_GL_TYPE(enum) pname , const DYNAMIC_GL_TYPE(fixed) * params),(coord , pname , params))
DYNAMIC_GL_FUNCTION_V(GetTexGenfvOES,(DYNAMIC_GL_TYPE(enum) coord , DYNAMIC_GL_TYPE(enum) pname , DYNAMIC_GL_TYPE(float) * params),(coord , pname , params))
DYNAMIC_GL_FUNCTION_V(GetTexGenivOES,(DYNAMIC_GL_TYPE(enum) coord , DYNAMIC_GL_TYPE(enum) pname , DYNAMIC_GL_TYPE(int) * params),(coord , pname , params))
DYNAMIC_GL_FUNCTION_V(GetTexGenxvOES,(DYNAMIC_GL_TYPE(enum) coord , DYNAMIC_GL_TYPE(enum) pname , DYNAMIC_GL_TYPE(fixed) * params),(coord , pname , params))
#endif /*USE_DYNAMIC_GL_OES_texture_cube_map*/

/*AMD_compressed_ATC_texture*/
#ifdef USE_DYNAMIC_GL_AMD_compressed_ATC_texture
DYNAMIC_GL_FEATURE(AMD_compressed_ATC_texture)
DYNAMIC_GL_CONSTANT(ATC_RGB_AMD,0x8C92)
DYNAMIC_GL_CONSTANT(ATC_RGBA_EXPLICIT_ALPHA_AMD,0x8C93)
DYNAMIC_GL_CONSTANT(ATC_RGBA_INTERPOLATED_ALPHA_AMD,0x87EE)
#endif /*USE_DYNAMIC_GL_AMD_compressed_ATC_texture*/

/*OES_blend_func_separate*/
#ifdef USE_DYNAMIC_GL_OES_blend_func_separate
DYNAMIC_GL_FEATURE(OES_blend_func_separate)
DYNAMIC_GL_CONSTANT(BLEND_DST_RGB_OES,0x80C8)
DYNAMIC_GL_CONSTANT(BLEND_SRC_RGB_OES,0x80C9)
DYNAMIC_GL_CONSTANT(BLEND_DST_ALPHA_OES,0x80CA)
DYNAMIC_GL_CONSTANT(BLEND_SRC_ALPHA_OES,0x80CB)
DYNAMIC_GL_FUNCTION_V(BlendFuncSeparateOES,(DYNAMIC_GL_TYPE(enum) srcRGB , DYNAMIC_GL_TYPE(enum) dstRGB , DYNAMIC_GL_TYPE(enum) srcAlpha , DYNAMIC_GL_TYPE(enum) dstAlpha),(srcRGB , dstRGB , srcAlpha , dstAlpha))
#endif /*USE_DYNAMIC_GL_OES_blend_func_separate*/

/*QCOM_driver_control*/
#ifdef USE_DYNAMIC_GL_QCOM_driver_control
DYNAMIC_GL_FEATURE(QCOM_driver_control)
DYNAMIC_GL_FUNCTION_V(GetDriverControlsQCOM,(DYNAMIC_GL_TYPE(int) * num , DYNAMIC_GL_TYPE(sizei) size , DYNAMIC_GL_TYPE(uint) * driverControls),(num , size , driverControls))
DYNAMIC_GL_FUNCTION_V(GetDriverControlStringQCOM,(DYNAMIC_GL_TYPE(uint) driverControl , DYNAMIC_GL_TYPE(sizei) bufSize , DYNAMIC_GL_TYPE(sizei) * length , DYNAMIC_GL_TYPE(char) * driverControlString),(driverControl , bufSize , length , driverControlString))
DYNAMIC_GL_FUNCTION_V(EnableDriverControlQCOM,(DYNAMIC_GL_TYPE(uint) driverControl),(driverControl))
DYNAMIC_GL_FUNCTION_V(DisableDriverControlQCOM,(DYNAMIC_GL_TYPE(uint) driverControl),(driverControl))
#endif /*USE_DYNAMIC_GL_QCOM_driver_control*/

/*EXT_multisampled_render_to_texture*/
#ifdef USE_DYNAMIC_GL_EXT_multisampled_render_to_texture
DYNAMIC_GL_FEATURE(EXT_multisampled_render_to_texture)
DYNAMIC_GL_CONSTANT(FRAMEBUFFER_ATTACHMENT_TEXTURE_SAMPLES_EXT,0x8D6C)
DYNAMIC_GL_CONSTANT(RENDERBUFFER_SAMPLES_EXT,0x8CAB)
DYNAMIC_GL_CONSTANT(FRAMEBUFFER_INCOMPLETE_MULTISAMPLE_EXT,0x8D56)
DYNAMIC_GL_CONSTANT(MAX_SAMPLES_EXT,0x8D57)
DYNAMIC_GL_FUNCTION_V(RenderbufferStorageMultisampleEXT,(DYNAMIC_GL_TYPE(enum) target , DYNAMIC_GL_TYPE(sizei) samples , DYNAMIC_GL_TYPE(enum) internalformat , DYNAMIC_GL_TYPE(sizei) width , DYNAMIC_GL_TYPE(sizei) height),(target , samples , internalformat , width , height))
DYNAMIC_GL_FUNCTION_V(FramebufferTexture2DMultisampleEXT,(DYNAMIC_GL_TYPE(enum) target , DYNAMIC_GL_TYPE(enum) attachment , DYNAMIC_GL_TYPE(enum) textarget , DYNAMIC_GL_TYPE(uint) texture , DYNAMIC_GL_TYPE(int) level , DYNAMIC_GL_TYPE(sizei) samples),(target , attachment , textarget , texture , level , samples))
#endif /*USE_DYNAMIC_GL_EXT_multisampled_render_to_texture*/

/*EXT_texture_storage*/
#ifdef USE_DYNAMIC_GL_EXT_texture_storage
DYNAMIC_GL_FEATURE(EXT_texture_storage)
DYNAMIC_GL_CONSTANT(TEXTURE_IMMUTABLE_FORMAT_EXT,0x912F)
DYNAMIC_GL_CONSTANT(ALPHA8_EXT,0x803C)
DYNAMIC_GL_CONSTANT(LUMINANCE8_EXT,0x8040)
DYNAMIC_GL_CONSTANT(LUMINANCE8_ALPHA8_EXT,0x8045)
DYNAMIC_GL_CONSTANT(RGBA32F_EXT,0x8814)
DYNAMIC_GL_CONSTANT(RGB32F_EXT,0x8815)
DYNAMIC_GL_CONSTANT(ALPHA32F_EXT,0x8816)
DYNAMIC_GL_CONSTANT(LUMINANCE32F_EXT,0x8818)
DYNAMIC_GL_CONSTANT(LUMINANCE_ALPHA32F_EXT,0x8819)
DYNAMIC_GL_CONSTANT(RGB16F_EXT,0x881B)
DYNAMIC_GL_CONSTANT(ALPHA16F_EXT,0x881C)
DYNAMIC_GL_CONSTANT(LUMINANCE16F_EXT,0x881E)
DYNAMIC_GL_CONSTANT(LUMINANCE_ALPHA16F_EXT,0x881F)
DYNAMIC_GL_CONSTANT(RGB10_A2_EXT,0x8059)
DYNAMIC_GL_CONSTANT(RGB10_EXT,0x8052)
DYNAMIC_GL_CONSTANT(BGRA8_EXT,0x93A1)
DYNAMIC_GL_FUNCTION_V(TexStorage1DEXT,(DYNAMIC_GL_TYPE(enum) target , DYNAMIC_GL_TYPE(sizei) levels , DYNAMIC_GL_TYPE(enum) internalformat , DYNAMIC_GL_TYPE(sizei) width),(target , levels , internalformat , width))
DYNAMIC_GL_FUNCTION_V(TexStorage2DEXT,(DYNAMIC_GL_TYPE(enum) target , DYNAMIC_GL_TYPE(sizei) levels , DYNAMIC_GL_TYPE(enum) internalformat , DYNAMIC_GL_TYPE(sizei) width , DYNAMIC_GL_TYPE(sizei) height),(target , levels , internalformat , width , height))
DYNAMIC_GL_FUNCTION_V(TexStorage3DEXT,(DYNAMIC_GL_TYPE(enum) target , DYNAMIC_GL_TYPE(sizei) levels , DYNAMIC_GL_TYPE(enum) internalformat , DYNAMIC_GL_TYPE(sizei) width , DYNAMIC_GL_TYPE(sizei) height , DYNAMIC_GL_TYPE(sizei) depth),(target , levels , internalformat , width , height , depth))
DYNAMIC_GL_FUNCTION_V(TextureStorage1DEXT,(DYNAMIC_GL_TYPE(uint) texture , DYNAMIC_GL_TYPE(enum) target , DYNAMIC_GL_TYPE(sizei) levels , DYNAMIC_GL_TYPE(enum) internalformat , DYNAMIC_GL_TYPE(sizei) width),(texture , target , levels , internalformat , width))
DYNAMIC_GL_FUNCTION_V(TextureStorage2DEXT,(DYNAMIC_GL_TYPE(uint) texture , DYNAMIC_GL_TYPE(enum) target , DYNAMIC_GL_TYPE(sizei) levels , DYNAMIC_GL_TYPE(enum) internalformat , DYNAMIC_GL_TYPE(sizei) width , DYNAMIC_GL_TYPE(sizei) height),(texture , target , levels , internalformat , width , height))
DYNAMIC_GL_FUNCTION_V(TextureStorage3DEXT,(DYNAMIC_GL_TYPE(uint) texture , DYNAMIC_GL_TYPE(enum) target , DYNAMIC_GL_TYPE(sizei) levels , DYNAMIC_GL_TYPE(enum) internalformat , DYNAMIC_GL_TYPE(sizei) width , DYNAMIC_GL_TYPE(sizei) height , DYNAMIC_GL_TYPE(sizei) depth),(texture , target , levels , internalformat , width , height , depth))
#endif /*USE_DYNAMIC_GL_EXT_texture_storage*/

/*OES_stencil8*/
#ifdef USE_DYNAMIC_GL_OES_stencil8
DYNAMIC_GL_FEATURE(OES_stencil8)
DYNAMIC_GL_CONSTANT(STENCIL_INDEX8_OES,0x8D48)
#endif /*USE_DYNAMIC_GL_OES_stencil8*/

/*APPLE_framebuffer_multisample*/
#ifdef USE_DYNAMIC_GL_APPLE_framebuffer_multisample
DYNAMIC_GL_FEATURE(APPLE_framebuffer_multisample)
DYNAMIC_GL_CONSTANT(RENDERBUFFER_SAMPLES_APPLE,0x8CAB)
DYNAMIC_GL_CONSTANT(FRAMEBUFFER_INCOMPLETE_MULTISAMPLE_APPLE,0x8D56)
DYNAMIC_GL_CONSTANT(MAX_SAMPLES_APPLE,0x8D57)
DYNAMIC_GL_CONSTANT(READ_FRAMEBUFFER_APPLE,0x8CA8)
DYNAMIC_GL_CONSTANT(DRAW_FRAMEBUFFER_APPLE,0x8CA9)
DYNAMIC_GL_CONSTANT(DRAW_FRAMEBUFFER_BINDING_APPLE,0x8CA6)
DYNAMIC_GL_CONSTANT(READ_FRAMEBUFFER_BINDING_APPLE,0x8CAA)
DYNAMIC_GL_FUNCTION_V(RenderbufferStorageMultisampleAPPLE,(DYNAMIC_GL_TYPE(enum) target , DYNAMIC_GL_TYPE(sizei) samples , DYNAMIC_GL_TYPE(enum) internalformat , DYNAMIC_GL_TYPE(sizei) width , DYNAMIC_GL_TYPE(sizei) height),(target , samples , internalformat , width , height))
DYNAMIC_GL_FUNCTION_V(ResolveMultisampleFramebufferAPPLE,(),())
#endif /*USE_DYNAMIC_GL_APPLE_framebuffer_multisample*/

/*OES_extended_matrix_palette*/
#ifdef USE_DYNAMIC_GL_OES_extended_matrix_palette
DYNAMIC_GL_FEATURE(OES_extended_matrix_palette)
#endif /*USE_DYNAMIC_GL_OES_extended_matrix_palette*/

/*APPLE_texture_format_BGRA8888*/
#ifdef USE_DYNAMIC_GL_APPLE_texture_format_BGRA8888
DYNAMIC_GL_FEATURE(APPLE_texture_format_BGRA8888)
DYNAMIC_GL_CONSTANT(BGRA_EXT,0x80E1)
#endif /*USE_DYNAMIC_GL_APPLE_texture_format_BGRA8888*/

/*IMG_user_clip_plane*/
#ifdef USE_DYNAMIC_GL_IMG_user_clip_plane
DYNAMIC_GL_FEATURE(IMG_user_clip_plane)
DYNAMIC_GL_CONSTANT(CLIP_PLANE0_IMG,0x3000)
DYNAMIC_GL_CONSTANT(CLIP_PLANE1_IMG,0x3001)
DYNAMIC_GL_CONSTANT(CLIP_PLANE2_IMG,0x3002)
DYNAMIC_GL_CONSTANT(CLIP_PLANE3_IMG,0x3003)
DYNAMIC_GL_CONSTANT(CLIP_PLANE4_IMG,0x3004)
DYNAMIC_GL_CONSTANT(CLIP_PLANE5_IMG,0x3005)
DYNAMIC_GL_CONSTANT(MAX_CLIP_PLANES_IMG,0x0D32)
DYNAMIC_GL_FUNCTION_V(ClipPlanefIMG,(DYNAMIC_GL_TYPE(enum) p , const DYNAMIC_GL_TYPE(float) * eqn),(p , eqn))
DYNAMIC_GL_FUNCTION_V(ClipPlanexIMG,(DYNAMIC_GL_TYPE(enum) p , const DYNAMIC_GL_TYPE(fixed) * eqn),(p , eqn))
#endif /*USE_DYNAMIC_GL_IMG_user_clip_plane*/

/*QCOM_perfmon_global_mode*/
#ifdef USE_DYNAMIC_GL_QCOM_perfmon_global_mode
DYNAMIC_GL_FEATURE(QCOM_perfmon_global_mode)
DYNAMIC_GL_CONSTANT(PERFMON_GLOBAL_MODE_QCOM,0x8FA0)
#endif /*USE_DYNAMIC_GL_QCOM_perfmon_global_mode*/

/*APPLE_texture_2D_limited_npot*/
#ifdef USE_DYNAMIC_GL_APPLE_texture_2D_limited_npot
DYNAMIC_GL_FEATURE(APPLE_texture_2D_limited_npot)
#endif /*USE_DYNAMIC_GL_APPLE_texture_2D_limited_npot*/

/*OES_depth32*/
#ifdef USE_DYNAMIC_GL_OES_depth32
DYNAMIC_GL_FEATURE(OES_depth32)
DYNAMIC_GL_CONSTANT(DEPTH_COMPONENT32_OES,0x81A7)
#endif /*USE_DYNAMIC_GL_OES_depth32*/

/*IMG_texture_compression_pvrtc*/
#ifdef USE_DYNAMIC_GL_IMG_texture_compression_pvrtc
DYNAMIC_GL_FEATURE(IMG_texture_compression_pvrtc)
DYNAMIC_GL_CONSTANT(COMPRESSED_RGB_PVRTC_4BPPV1_IMG,0x8C00)
DYNAMIC_GL_CONSTANT(COMPRESSED_RGB_PVRTC_2BPPV1_IMG,0x8C01)
DYNAMIC_GL_CONSTANT(COMPRESSED_RGBA_PVRTC_4BPPV1_IMG,0x8C02)
DYNAMIC_GL_CONSTANT(COMPRESSED_RGBA_PVRTC_2BPPV1_IMG,0x8C03)
#endif /*USE_DYNAMIC_GL_IMG_texture_compression_pvrtc*/

/*OES_single_precision*/
#ifdef USE_DYNAMIC_GL_OES_single_precision
DYNAMIC_GL_FEATURE(OES_single_precision)
DYNAMIC_GL_FUNCTION_V(DepthRangefOES,(DYNAMIC_GL_TYPE(clampf) zNear , DYNAMIC_GL_TYPE(clampf) zFar),(zNear , zFar))
DYNAMIC_GL_FUNCTION_V(FrustumfOES,(DYNAMIC_GL_TYPE(float) left , DYNAMIC_GL_TYPE(float) right , DYNAMIC_GL_TYPE(float) bottom , DYNAMIC_GL_TYPE(float) top , DYNAMIC_GL_TYPE(float) zNear , DYNAMIC_GL_TYPE(float) zFar),(left , right , bottom , top , zNear , zFar))
DYNAMIC_GL_FUNCTION_V(OrthofOES,(DYNAMIC_GL_TYPE(float) left , DYNAMIC_GL_TYPE(float) right , DYNAMIC_GL_TYPE(float) bottom , DYNAMIC_GL_TYPE(float) top , DYNAMIC_GL_TYPE(float) zNear , DYNAMIC_GL_TYPE(float) zFar),(left , right , bottom , top , zNear , zFar))
DYNAMIC_GL_FUNCTION_V(ClipPlanefOES,(DYNAMIC_GL_TYPE(enum) plane , const DYNAMIC_GL_TYPE(float) * equation),(plane , equation))
DYNAMIC_GL_FUNCTION_V(ClearDepthfOES,(DYNAMIC_GL_TYPE(clampf) depth),(depth))
#endif /*USE_DYNAMIC_GL_OES_single_precision*/

/*OES_packed_depth_stencil*/
#ifdef USE_DYNAMIC_GL_OES_packed_depth_stencil
DYNAMIC_GL_FEATURE(OES_packed_depth_stencil)
DYNAMIC_GL_CONSTANT(DEPTH_STENCIL_OES,0x84F9)
DYNAMIC_GL_CONSTANT(UNSIGNED_INT_24_8_OES,0x84FA)
DYNAMIC_GL_CONSTANT(DEPTH24_STENCIL8_OES,0x88F0)
#endif /*USE_DYNAMIC_GL_OES_packed_depth_stencil*/

/*EXT_discard_framebuffer*/
#ifdef USE_DYNAMIC_GL_EXT_discard_framebuffer
DYNAMIC_GL_FEATURE(EXT_discard_framebuffer)
DYNAMIC_GL_CONSTANT(COLOR_EXT,0x1800)
DYNAMIC_GL_CONSTANT(DEPTH_EXT,0x1801)
DYNAMIC_GL_CONSTANT(STENCIL_EXT,0x1802)
DYNAMIC_GL_FUNCTION_V(DiscardFramebufferEXT,(DYNAMIC_GL_TYPE(enum) target , DYNAMIC_GL_TYPE(sizei) numAttachments , const DYNAMIC_GL_TYPE(enum) * attachments),(target , numAttachments , attachments))
#endif /*USE_DYNAMIC_GL_EXT_discard_framebuffer*/

/*OES_EGL_image*/
#ifdef USE_DYNAMIC_GL_OES_EGL_image
DYNAMIC_GL_FEATURE(OES_EGL_image)
DYNAMIC_GL_FUNCTION_V(EGLImageTargetTexture2DOES,(DYNAMIC_GL_TYPE(enum) target , DYNAMIC_GL_TYPE(eglImageOES) image),(target , image))
DYNAMIC_GL_FUNCTION_V(EGLImageTargetRenderbufferStorageOES,(DYNAMIC_GL_TYPE(enum) target , DYNAMIC_GL_TYPE(eglImageOES) image),(target , image))
#endif /*USE_DYNAMIC_GL_OES_EGL_image*/

/*APPLE_sync*/
#ifdef USE_DYNAMIC_GL_APPLE_sync
DYNAMIC_GL_FEATURE(APPLE_sync)
DYNAMIC_GL_TYPEDEF(khronos_int64_t,int64)
DYNAMIC_GL_TYPEDEF(khronos_uint64_t,uint64)
DYNAMIC_GL_CONSTANT(SYNC_OBJECT_APPLE,0x8A53)
DYNAMIC_GL_CONSTANT(MAX_SERVER_WAIT_TIMEOUT_APPLE,0x9111)
DYNAMIC_GL_CONSTANT(OBJECT_TYPE_APPLE,0x9112)
DYNAMIC_GL_CONSTANT(SYNC_CONDITION_APPLE,0x9113)
DYNAMIC_GL_CONSTANT(SYNC_STATUS_APPLE,0x9114)
DYNAMIC_GL_CONSTANT(SYNC_FLAGS_APPLE,0x9115)
DYNAMIC_GL_CONSTANT(SYNC_FENCE_APPLE,0x9116)
DYNAMIC_GL_CONSTANT(SYNC_GPU_COMMANDS_COMPLETE_APPLE,0x9117)
DYNAMIC_GL_CONSTANT(UNSIGNALED_APPLE,0x9118)
DYNAMIC_GL_CONSTANT(SIGNALED_APPLE,0x9119)
DYNAMIC_GL_CONSTANT(ALREADY_SIGNALED_APPLE,0x911A)
DYNAMIC_GL_CONSTANT(TIMEOUT_EXPIRED_APPLE,0x911B)
DYNAMIC_GL_CONSTANT(CONDITION_SATISFIED_APPLE,0x911C)
DYNAMIC_GL_CONSTANT(WAIT_FAILED_APPLE,0x911D)
DYNAMIC_GL_CONSTANT(SYNC_FLUSH_COMMANDS_BIT_APPLE,0x00000001)
DYNAMIC_GL_CONSTANT(TIMEOUT_IGNORED_APPLE,0xFFFFFFFFFFFFFFFF)
DYNAMIC_GL_FUNCTION(DYNAMIC_GL_TYPE(sync),FenceSyncAPPLE,(DYNAMIC_GL_TYPE(enum) condition , DYNAMIC_GL_TYPE(bitfield) flags),(condition , flags))
DYNAMIC_GL_FUNCTION(DYNAMIC_GL_TYPE(boolean),IsSyncAPPLE,(DYNAMIC_GL_TYPE(sync) sync),(sync))
DYNAMIC_GL_FUNCTION_V(DeleteSyncAPPLE,(DYNAMIC_GL_TYPE(sync) sync),(sync))
DYNAMIC_GL_FUNCTION(DYNAMIC_GL_TYPE(enum),ClientWaitSyncAPPLE,(DYNAMIC_GL_TYPE(sync) sync , DYNAMIC_GL_TYPE(bitfield) flags , DYNAMIC_GL_TYPE(uint64) timeout),(sync , flags , timeout))
DYNAMIC_GL_FUNCTION_V(WaitSyncAPPLE,(DYNAMIC_GL_TYPE(sync) sync , DYNAMIC_GL_TYPE(bitfield) flags , DYNAMIC_GL_TYPE(uint64) timeout),(sync , flags , timeout))
DYNAMIC_GL_FUNCTION_V(GetInteger64vAPPLE,(DYNAMIC_GL_TYPE(enum) pname , DYNAMIC_GL_TYPE(int64) * params),(pname , params))
DYNAMIC_GL_FUNCTION_V(GetSyncivAPPLE,(DYNAMIC_GL_TYPE(sync) sync , DYNAMIC_GL_TYPE(enum) pname , DYNAMIC_GL_TYPE(sizei) bufSize , DYNAMIC_GL_TYPE(sizei) * length , DYNAMIC_GL_TYPE(int) * values),(sync , pname , bufSize , length , values))
#endif /*USE_DYNAMIC_GL_APPLE_sync*/

/*EXT_sRGB*/
#ifdef USE_DYNAMIC_GL_EXT_sRGB
DYNAMIC_GL_FEATURE(EXT_sRGB)
DYNAMIC_GL_CONSTANT(SRGB_EXT,0x8C40)
DYNAMIC_GL_CONSTANT(SRGB_ALPHA_EXT,0x8C42)
DYNAMIC_GL_CONSTANT(SRGB8_ALPHA8_EXT,0x8C43)
DYNAMIC_GL_CONSTANT(FRAMEBUFFER_ATTACHMENT_COLOR_ENCODING_EXT,0x8210)
#endif /*USE_DYNAMIC_GL_EXT_sRGB*/

/*EXT_texture_filter_anisotropic*/
#ifdef USE_DYNAMIC_GL_EXT_texture_filter_anisotropic
DYNAMIC_GL_FEATURE(EXT_texture_filter_anisotropic)
DYNAMIC_GL_CONSTANT(TEXTURE_MAX_ANISOTROPY_EXT,0x84FE)
DYNAMIC_GL_CONSTANT(MAX_TEXTURE_MAX_ANISOTROPY_EXT,0x84FF)
#endif /*USE_DYNAMIC_GL_EXT_texture_filter_anisotropic*/

/*NV_fence*/
#ifdef USE_DYNAMIC_GL_NV_fence
DYNAMIC_GL_FEATURE(NV_fence)
DYNAMIC_GL_CONSTANT(ALL_COMPLETED_NV,0x84F2)
DYNAMIC_GL_CONSTANT(FENCE_STATUS_NV,0x84F3)
DYNAMIC_GL_CONSTANT(FENCE_CONDITION_NV,0x84F4)
DYNAMIC_GL_FUNCTION_V(DeleteFencesNV,(DYNAMIC_GL_TYPE(sizei) n , const DYNAMIC_GL_TYPE(uint) * fences),(n , fences))
DYNAMIC_GL_FUNCTION_V(GenFencesNV,(DYNAMIC_GL_TYPE(sizei) n , DYNAMIC_GL_TYPE(uint) * fences),(n , fences))
DYNAMIC_GL_FUNCTION(DYNAMIC_GL_TYPE(boolean),IsFenceNV,(DYNAMIC_GL_TYPE(uint) fence),(fence))
DYNAMIC_GL_FUNCTION(DYNAMIC_GL_TYPE(boolean),TestFenceNV,(DYNAMIC_GL_TYPE(uint) fence),(fence))
DYNAMIC_GL_FUNCTION_V(GetFenceivNV,(DYNAMIC_GL_TYPE(uint) fence , DYNAMIC_GL_TYPE(enum) pname , DYNAMIC_GL_TYPE(int) * params),(fence , pname , params))
DYNAMIC_GL_FUNCTION_V(FinishFenceNV,(DYNAMIC_GL_TYPE(uint) fence),(fence))
DYNAMIC_GL_FUNCTION_V(SetFenceNV,(DYNAMIC_GL_TYPE(uint) fence , DYNAMIC_GL_TYPE(enum) condition),(fence , condition))
#endif /*USE_DYNAMIC_GL_NV_fence*/

/*OES_matrix_get*/
#ifdef USE_DYNAMIC_GL_OES_matrix_get
DYNAMIC_GL_FEATURE(OES_matrix_get)
DYNAMIC_GL_CONSTANT(MODELVIEW_MATRIX_FLOAT_AS_INT_BITS_OES,0x898D)
DYNAMIC_GL_CONSTANT(PROJECTION_MATRIX_FLOAT_AS_INT_BITS_OES,0x898E)
DYNAMIC_GL_CONSTANT(TEXTURE_MATRIX_FLOAT_AS_INT_BITS_OES,0x898F)
#endif /*USE_DYNAMIC_GL_OES_matrix_get*/

/*OES_draw_texture*/
#ifdef USE_DYNAMIC_GL_OES_draw_texture
DYNAMIC_GL_FEATURE(OES_draw_texture)
DYNAMIC_GL_CONSTANT(TEXTURE_CROP_RECT_OES,0x8B9D)
DYNAMIC_GL_FUNCTION_V(DrawTexsOES,(DYNAMIC_GL_TYPE(short) x , DYNAMIC_GL_TYPE(short) y , DYNAMIC_GL_TYPE(short) z , DYNAMIC_GL_TYPE(short) width , DYNAMIC_GL_TYPE(short) height),(x , y , z , width , height))
DYNAMIC_GL_FUNCTION_V(DrawTexiOES,(DYNAMIC_GL_TYPE(int) x , DYNAMIC_GL_TYPE(int) y , DYNAMIC_GL_TYPE(int) z , DYNAMIC_GL_TYPE(int) width , DYNAMIC_GL_TYPE(int) height),(x , y , z , width , height))
DYNAMIC_GL_FUNCTION_V(DrawTexxOES,(DYNAMIC_GL_TYPE(fixed) x , DYNAMIC_GL_TYPE(fixed) y , DYNAMIC_GL_TYPE(fixed) z , DYNAMIC_GL_TYPE(fixed) width , DYNAMIC_GL_TYPE(fixed) height),(x , y , z , width , height))
DYNAMIC_GL_FUNCTION_V(DrawTexsvOES,(const DYNAMIC_GL_TYPE(short) * coords),(coords))
DYNAMIC_GL_FUNCTION_V(DrawTexivOES,(const DYNAMIC_GL_TYPE(int) * coords),(coords))
DYNAMIC_GL_FUNCTION_V(DrawTexxvOES,(const DYNAMIC_GL_TYPE(fixed) * coords),(coords))
DYNAMIC_GL_FUNCTION_V(DrawTexfOES,(DYNAMIC_GL_TYPE(float) x , DYNAMIC_GL_TYPE(float) y , DYNAMIC_GL_TYPE(float) z , DYNAMIC_GL_TYPE(float) width , DYNAMIC_GL_TYPE(float) height),(x , y , z , width , height))
DYNAMIC_GL_FUNCTION_V(DrawTexfvOES,(const DYNAMIC_GL_TYPE(float) * coords),(coords))
#endif /*USE_DYNAMIC_GL_OES_draw_texture*/

/*EXT_robustness*/
#ifdef USE_DYNAMIC_GL_EXT_robustness
DYNAMIC_GL_FEATURE(EXT_robustness)
DYNAMIC_GL_CONSTANT(GUILTY_CONTEXT_RESET_EXT,0x8253)
DYNAMIC_GL_CONSTANT(INNOCENT_CONTEXT_RESET_EXT,0x8254)
DYNAMIC_GL_CONSTANT(UNKNOWN_CONTEXT_RESET_EXT,0x8255)
DYNAMIC_GL_CONSTANT(CONTEXT_ROBUST_ACCESS_EXT,0x90F3)
DYNAMIC_GL_CONSTANT(RESET_NOTIFICATION_STRATEGY_EXT,0x8256)
DYNAMIC_GL_CONSTANT(LOSE_CONTEXT_ON_RESET_EXT,0x8252)
DYNAMIC_GL_CONSTANT(NO_RESET_NOTIFICATION_EXT,0x8261)
DYNAMIC_GL_FUNCTION(DYNAMIC_GL_TYPE(enum),GetGraphicsResetStatusEXT,(),())
DYNAMIC_GL_FUNCTION_V(ReadnPixelsEXT,(DYNAMIC_GL_TYPE(int) x , DYNAMIC_GL_TYPE(int) y , DYNAMIC_GL_TYPE(sizei) width , DYNAMIC_GL_TYPE(sizei) height , DYNAMIC_GL_TYPE(enum) format , DYNAMIC_GL_TYPE(enum) type , DYNAMIC_GL_TYPE(sizei) bufSize , DYNAMIC_GL_TYPE(void) * data),(x , y , width , height , format , type , bufSize , data))
DYNAMIC_GL_FUNCTION_V(GetnUniformfvEXT,(DYNAMIC_GL_TYPE(uint) program , DYNAMIC_GL_TYPE(int) location , DYNAMIC_GL_TYPE(sizei) bufSize , DYNAMIC_GL_TYPE(float) * params),(program , location , bufSize , params))
DYNAMIC_GL_FUNCTION_V(GetnUniformivEXT,(DYNAMIC_GL_TYPE(uint) program , DYNAMIC_GL_TYPE(int) location , DYNAMIC_GL_TYPE(sizei) bufSize , DYNAMIC_GL_TYPE(int) * params),(program , location , bufSize , params))
#endif /*USE_DYNAMIC_GL_EXT_robustness*/

/*OES_byte_coordinates*/
#ifdef USE_DYNAMIC_GL_OES_byte_coordinates
DYNAMIC_GL_FEATURE(OES_byte_coordinates)
#endif /*USE_DYNAMIC_GL_OES_byte_coordinates*/

/*QCOM_extended_get2*/
#ifdef USE_DYNAMIC_GL_QCOM_extended_get2
DYNAMIC_GL_FEATURE(QCOM_extended_get2)
DYNAMIC_GL_FUNCTION_V(ExtGetShadersQCOM,(DYNAMIC_GL_TYPE(uint) * shaders , DYNAMIC_GL_TYPE(int) maxShaders , DYNAMIC_GL_TYPE(int) * numShaders),(shaders , maxShaders , numShaders))
DYNAMIC_GL_FUNCTION_V(ExtGetProgramsQCOM,(DYNAMIC_GL_TYPE(uint) * programs , DYNAMIC_GL_TYPE(int) maxPrograms , DYNAMIC_GL_TYPE(int) * numPrograms),(programs , maxPrograms , numPrograms))
DYNAMIC_GL_FUNCTION(DYNAMIC_GL_TYPE(boolean),ExtIsProgramBinaryQCOM,(DYNAMIC_GL_TYPE(uint) program),(program))
DYNAMIC_GL_FUNCTION_V(ExtGetProgramBinarySourceQCOM,(DYNAMIC_GL_TYPE(uint) program , DYNAMIC_GL_TYPE(enum) shadertype , DYNAMIC_GL_TYPE(char) * source , DYNAMIC_GL_TYPE(int) * length),(program , shadertype , source , length))
#endif /*USE_DYNAMIC_GL_QCOM_extended_get2*/

/*OES_stencil4*/
#ifdef USE_DYNAMIC_GL_OES_stencil4
DYNAMIC_GL_FEATURE(OES_stencil4)
DYNAMIC_GL_CONSTANT(STENCIL_INDEX4_OES,0x8D47)
#endif /*USE_DYNAMIC_GL_OES_stencil4*/

/*OES_matrix_palette*/
#ifdef USE_DYNAMIC_GL_OES_matrix_palette
DYNAMIC_GL_FEATURE(OES_matrix_palette)
DYNAMIC_GL_CONSTANT(MAX_VERTEX_UNITS_OES,0x86A4)
DYNAMIC_GL_CONSTANT(MAX_PALETTE_MATRICES_OES,0x8842)
DYNAMIC_GL_CONSTANT(MATRIX_PALETTE_OES,0x8840)
DYNAMIC_GL_CONSTANT(MATRIX_INDEX_ARRAY_OES,0x8844)
DYNAMIC_GL_CONSTANT(WEIGHT_ARRAY_OES,0x86AD)
DYNAMIC_GL_CONSTANT(CURRENT_PALETTE_MATRIX_OES,0x8843)
DYNAMIC_GL_CONSTANT(MATRIX_INDEX_ARRAY_SIZE_OES,0x8846)
DYNAMIC_GL_CONSTANT(MATRIX_INDEX_ARRAY_TYPE_OES,0x8847)
DYNAMIC_GL_CONSTANT(MATRIX_INDEX_ARRAY_STRIDE_OES,0x8848)
DYNAMIC_GL_CONSTANT(MATRIX_INDEX_ARRAY_POINTER_OES,0x8849)
DYNAMIC_GL_CONSTANT(MATRIX_INDEX_ARRAY_BUFFER_BINDING_OES,0x8B9E)
DYNAMIC_GL_CONSTANT(WEIGHT_ARRAY_SIZE_OES,0x86AB)
DYNAMIC_GL_CONSTANT(WEIGHT_ARRAY_TYPE_OES,0x86A9)
DYNAMIC_GL_CONSTANT(WEIGHT_ARRAY_STRIDE_OES,0x86AA)
DYNAMIC_GL_CONSTANT(WEIGHT_ARRAY_POINTER_OES,0x86AC)
DYNAMIC_GL_CONSTANT(WEIGHT_ARRAY_BUFFER_BINDING_OES,0x889E)
DYNAMIC_GL_FUNCTION_V(CurrentPaletteMatrixOES,(DYNAMIC_GL_TYPE(uint) matrixpaletteindex),(matrixpaletteindex))
DYNAMIC_GL_FUNCTION_V(LoadPaletteFromModelViewMatrixOES,(),())
DYNAMIC_GL_FUNCTION_V(MatrixIndexPointerOES,(DYNAMIC_GL_TYPE(int) size , DYNAMIC_GL_TYPE(enum) type , DYNAMIC_GL_TYPE(sizei) stride , const DYNAMIC_GL_TYPE(void) * pointer),(size , type , stride , pointer))
DYNAMIC_GL_FUNCTION_V(WeightPointerOES,(DYNAMIC_GL_TYPE(int) size , DYNAMIC_GL_TYPE(enum) type , DYNAMIC_GL_TYPE(sizei) stride , const DYNAMIC_GL_TYPE(void) * pointer),(size , type , stride , pointer))
#endif /*USE_DYNAMIC_GL_OES_matrix_palette*/

/*QCOM_extended_get*/
#ifdef USE_DYNAMIC_GL_QCOM_extended_get
DYNAMIC_GL_FEATURE(QCOM_extended_get)
DYNAMIC_GL_CONSTANT(TEXTURE_WIDTH_QCOM,0x8BD2)
DYNAMIC_GL_CONSTANT(TEXTURE_HEIGHT_QCOM,0x8BD3)
DYNAMIC_GL_CONSTANT(TEXTURE_DEPTH_QCOM,0x8BD4)
DYNAMIC_GL_CONSTANT(TEXTURE_INTERNAL_FORMAT_QCOM,0x8BD5)
DYNAMIC_GL_CONSTANT(TEXTURE_FORMAT_QCOM,0x8BD6)
DYNAMIC_GL_CONSTANT(TEXTURE_TYPE_QCOM,0x8BD7)
DYNAMIC_GL_CONSTANT(TEXTURE_IMAGE_VALID_QCOM,0x8BD8)
DYNAMIC_GL_CONSTANT(TEXTURE_NUM_LEVELS_QCOM,0x8BD9)
DYNAMIC_GL_CONSTANT(TEXTURE_TARGET_QCOM,0x8BDA)
DYNAMIC_GL_CONSTANT(TEXTURE_OBJECT_VALID_QCOM,0x8BDB)
DYNAMIC_GL_CONSTANT(STATE_RESTORE,0x8BDC)
DYNAMIC_GL_FUNCTION_V(ExtGetTexturesQCOM,(DYNAMIC_GL_TYPE(uint) * textures , DYNAMIC_GL_TYPE(int) maxTextures , DYNAMIC_GL_TYPE(int) * numTextures),(textures , maxTextures , numTextures))
DYNAMIC_GL_FUNCTION_V(ExtGetBuffersQCOM,(DYNAMIC_GL_TYPE(uint) * buffers , DYNAMIC_GL_TYPE(int) maxBuffers , DYNAMIC_GL_TYPE(int) * numBuffers),(buffers , maxBuffers , numBuffers))
DYNAMIC_GL_FUNCTION_V(ExtGetRenderbuffersQCOM,(DYNAMIC_GL_TYPE(uint) * renderbuffers , DYNAMIC_GL_TYPE(int) maxRenderbuffers , DYNAMIC_GL_TYPE(int) * numRenderbuffers),(renderbuffers , maxRenderbuffers , numRenderbuffers))
DYNAMIC_GL_FUNCTION_V(ExtGetFramebuffersQCOM,(DYNAMIC_GL_TYPE(uint) * framebuffers , DYNAMIC_GL_TYPE(int) maxFramebuffers , DYNAMIC_GL_TYPE(int) * numFramebuffers),(framebuffers , maxFramebuffers , numFramebuffers))
DYNAMIC_GL_FUNCTION_V(ExtGetTexLevelParameterivQCOM,(DYNAMIC_GL_TYPE(uint) texture , DYNAMIC_GL_TYPE(enum) face , DYNAMIC_GL_TYPE(int) level , DYNAMIC_GL_TYPE(enum) pname , DYNAMIC_GL_TYPE(int) * params),(texture , face , level , pname , params))
DYNAMIC_GL_FUNCTION_V(ExtTexObjectStateOverrideiQCOM,(DYNAMIC_GL_TYPE(enum) target , DYNAMIC_GL_TYPE(enum) pname , DYNAMIC_GL_TYPE(int) param),(target , pname , param))
DYNAMIC_GL_FUNCTION_V(ExtGetTexSubImageQCOM,(DYNAMIC_GL_TYPE(enum) target , DYNAMIC_GL_TYPE(int) level , DYNAMIC_GL_TYPE(int) xoffset , DYNAMIC_GL_TYPE(int) yoffset , DYNAMIC_GL_TYPE(int) zoffset , DYNAMIC_GL_TYPE(sizei) width , DYNAMIC_GL_TYPE(sizei) height , DYNAMIC_GL_TYPE(sizei) depth , DYNAMIC_GL_TYPE(enum) format , DYNAMIC_GL_TYPE(enum) type , DYNAMIC_GL_TYPE(void) * texels),(target , level , xoffset , yoffset , zoffset , width , height , depth , format , type , texels))
DYNAMIC_GL_FUNCTION_V(ExtGetBufferPointervQCOM,(DYNAMIC_GL_TYPE(enum) target , DYNAMIC_GL_TYPE(void) * p1),(target , p1))
#endif /*USE_DYNAMIC_GL_QCOM_extended_get*/

/*OES_vertex_array_object*/
#ifdef USE_DYNAMIC_GL_OES_vertex_array_object
DYNAMIC_GL_FEATURE(OES_vertex_array_object)
DYNAMIC_GL_CONSTANT(VERTEX_ARRAY_BINDING_OES,0x85B5)
DYNAMIC_GL_FUNCTION_V(BindVertexArrayOES,(DYNAMIC_GL_TYPE(uint) array),(array))
DYNAMIC_GL_FUNCTION_V(DeleteVertexArraysOES,(DYNAMIC_GL_TYPE(sizei) n , const DYNAMIC_GL_TYPE(uint) * arrays),(n , arrays))
DYNAMIC_GL_FUNCTION_V(GenVertexArraysOES,(DYNAMIC_GL_TYPE(sizei) n , DYNAMIC_GL_TYPE(uint) * arrays),(n , arrays))
DYNAMIC_GL_FUNCTION(DYNAMIC_GL_TYPE(boolean),IsVertexArrayOES,(DYNAMIC_GL_TYPE(uint) array),(array))
#endif /*USE_DYNAMIC_GL_OES_vertex_array_object*/

/*OES_blend_subtract*/
#ifdef USE_DYNAMIC_GL_OES_blend_subtract
DYNAMIC_GL_FEATURE(OES_blend_subtract)
DYNAMIC_GL_CONSTANT(BLEND_EQUATION_OES,0x8009)
DYNAMIC_GL_CONSTANT(FUNC_ADD_OES,0x8006)
DYNAMIC_GL_CONSTANT(FUNC_SUBTRACT_OES,0x800A)
DYNAMIC_GL_CONSTANT(FUNC_REVERSE_SUBTRACT_OES,0x800B)
DYNAMIC_GL_FUNCTION_V(BlendEquationOES,(DYNAMIC_GL_TYPE(enum) mode),(mode))
#endif /*USE_DYNAMIC_GL_OES_blend_subtract*/

/*APPLE_texture_max_level*/
#ifdef USE_DYNAMIC_GL_APPLE_texture_max_level
DYNAMIC_GL_FEATURE(APPLE_texture_max_level)
DYNAMIC_GL_CONSTANT(TEXTURE_MAX_LEVEL_APPLE,0x813D)
#endif /*USE_DYNAMIC_GL_APPLE_texture_max_level*/

/*OES_texture_env_crossbar*/
#ifdef USE_DYNAMIC_GL_OES_texture_env_crossbar
DYNAMIC_GL_FEATURE(OES_texture_env_crossbar)
#endif /*USE_DYNAMIC_GL_OES_texture_env_crossbar*/

/*OES_required_internalformat*/
#ifdef USE_DYNAMIC_GL_OES_required_internalformat
DYNAMIC_GL_FEATURE(OES_required_internalformat)
#endif /*USE_DYNAMIC_GL_OES_required_internalformat*/

/*OES_stencil1*/
#ifdef USE_DYNAMIC_GL_OES_stencil1
DYNAMIC_GL_FEATURE(OES_stencil1)
DYNAMIC_GL_CONSTANT(STENCIL_INDEX1_OES,0x8D46)
#endif /*USE_DYNAMIC_GL_OES_stencil1*/

/*EXT_read_format_bgra*/
#ifdef USE_DYNAMIC_GL_EXT_read_format_bgra
DYNAMIC_GL_FEATURE(EXT_read_format_bgra)
DYNAMIC_GL_CONSTANT(BGRA_EXT,0x80E1)
DYNAMIC_GL_CONSTANT(UNSIGNED_SHORT_4_4_4_4_REV_EXT,0x8365)
DYNAMIC_GL_CONSTANT(UNSIGNED_SHORT_1_5_5_5_REV_EXT,0x8366)
#endif /*USE_DYNAMIC_GL_EXT_read_format_bgra*/

/*EXT_blend_minmax*/
#ifdef USE_DYNAMIC_GL_EXT_blend_minmax
DYNAMIC_GL_FEATURE(EXT_blend_minmax)
DYNAMIC_GL_CONSTANT(MIN_EXT,0x8007)
DYNAMIC_GL_CONSTANT(MAX_EXT,0x8008)
#endif /*USE_DYNAMIC_GL_EXT_blend_minmax*/

/*OES_mapbuffer*/
#ifdef USE_DYNAMIC_GL_OES_mapbuffer
DYNAMIC_GL_FEATURE(OES_mapbuffer)
DYNAMIC_GL_CONSTANT(WRITE_ONLY_OES,0x88B9)
DYNAMIC_GL_CONSTANT(BUFFER_ACCESS_OES,0x88BB)
DYNAMIC_GL_CONSTANT(BUFFER_MAPPED_OES,0x88BC)
DYNAMIC_GL_CONSTANT(BUFFER_MAP_POINTER_OES,0x88BD)
DYNAMIC_GL_FUNCTION(DYNAMIC_GL_TYPE(boolean),UnmapBufferOES,(DYNAMIC_GL_TYPE(enum) target),(target))
DYNAMIC_GL_FUNCTION_V(GetBufferPointervOES,(DYNAMIC_GL_TYPE(enum) target , DYNAMIC_GL_TYPE(enum) pname , DYNAMIC_GL_TYPE(void) * p1),(target , pname , p1))
#endif /*USE_DYNAMIC_GL_OES_mapbuffer*/

/*OES_fixed_point*/
#ifdef USE_DYNAMIC_GL_OES_fixed_point
DYNAMIC_GL_FEATURE(OES_fixed_point)
DYNAMIC_GL_CONSTANT(FIXED_OES,0x140C)
DYNAMIC_GL_FUNCTION_V(AlphaFuncxOES,(DYNAMIC_GL_TYPE(enum) func , DYNAMIC_GL_TYPE(clampx) ref),(func , ref))
DYNAMIC_GL_FUNCTION_V(ClearColorxOES,(DYNAMIC_GL_TYPE(clampx) red , DYNAMIC_GL_TYPE(clampx) green , DYNAMIC_GL_TYPE(clampx) blue , DYNAMIC_GL_TYPE(clampx) alpha),(red , green , blue , alpha))
DYNAMIC_GL_FUNCTION_V(ClearDepthxOES,(DYNAMIC_GL_TYPE(clampx) depth),(depth))
DYNAMIC_GL_FUNCTION_V(ClipPlanexOES,(DYNAMIC_GL_TYPE(enum) plane , const DYNAMIC_GL_TYPE(fixed) * equation),(plane , equation))
DYNAMIC_GL_FUNCTION_V(Color4xOES,(DYNAMIC_GL_TYPE(fixed) red , DYNAMIC_GL_TYPE(fixed) green , DYNAMIC_GL_TYPE(fixed) blue , DYNAMIC_GL_TYPE(fixed) alpha),(red , green , blue , alpha))
DYNAMIC_GL_FUNCTION_V(DepthRangexOES,(DYNAMIC_GL_TYPE(clampx) zNear , DYNAMIC_GL_TYPE(clampx) zFar),(zNear , zFar))
DYNAMIC_GL_FUNCTION_V(FogxOES,(DYNAMIC_GL_TYPE(enum) pname , DYNAMIC_GL_TYPE(fixed) param),(pname , param))
DYNAMIC_GL_FUNCTION_V(FogxvOES,(DYNAMIC_GL_TYPE(enum) pname , const DYNAMIC_GL_TYPE(fixed) * params),(pname , params))
DYNAMIC_GL_FUNCTION_V(FrustumxOES,(DYNAMIC_GL_TYPE(fixed) left , DYNAMIC_GL_TYPE(fixed) right , DYNAMIC_GL_TYPE(fixed) bottom , DYNAMIC_GL_TYPE(fixed) top , DYNAMIC_GL_TYPE(fixed) zNear , DYNAMIC_GL_TYPE(fixed) zFar),(left , right , bottom , top , zNear , zFar))
DYNAMIC_GL_FUNCTION_V(GetFixedvOES,(DYNAMIC_GL_TYPE(enum) pname , DYNAMIC_GL_TYPE(fixed) * params),(pname , params))
DYNAMIC_GL_FUNCTION_V(GetLightxvOES,(DYNAMIC_GL_TYPE(enum) light , DYNAMIC_GL_TYPE(enum) pname , DYNAMIC_GL_TYPE(fixed) * params),(light , pname , params))
DYNAMIC_GL_FUNCTION_V(GetMaterialxvOES,(DYNAMIC_GL_TYPE(enum) face , DYNAMIC_GL_TYPE(enum) pname , DYNAMIC_GL_TYPE(fixed) * params),(face , pname , params))
DYNAMIC_GL_FUNCTION_V(GetTexEnvxvOES,(DYNAMIC_GL_TYPE(enum) env , DYNAMIC_GL_TYPE(enum) pname , DYNAMIC_GL_TYPE(fixed) * params),(env , pname , params))
DYNAMIC_GL_FUNCTION_V(GetTexParameterxvOES,(DYNAMIC_GL_TYPE(enum) target , DYNAMIC_GL_TYPE(enum) pname , DYNAMIC_GL_TYPE(fixed) * params),(target , pname , params))
DYNAMIC_GL_FUNCTION_V(LightModelxOES,(DYNAMIC_GL_TYPE(enum) pname , DYNAMIC_GL_TYPE(fixed) param),(pname , param))
DYNAMIC_GL_FUNCTION_V(LightModelxvOES,(DYNAMIC_GL_TYPE(enum) pname , const DYNAMIC_GL_TYPE(fixed) * params),(pname , params))
DYNAMIC_GL_FUNCTION_V(LightxOES,(DYNAMIC_GL_TYPE(enum) light , DYNAMIC_GL_TYPE(enum) pname , DYNAMIC_GL_TYPE(fixed) param),(light , pname , param))
DYNAMIC_GL_FUNCTION_V(LightxvOES,(DYNAMIC_GL_TYPE(enum) light , DYNAMIC_GL_TYPE(enum) pname , const DYNAMIC_GL_TYPE(fixed) * params),(light , pname , params))
DYNAMIC_GL_FUNCTION_V(LineWidthxOES,(DYNAMIC_GL_TYPE(fixed) width),(width))
DYNAMIC_GL_FUNCTION_V(LoadMatrixxOES,(const DYNAMIC_GL_TYPE(fixed) * m),(m))
DYNAMIC_GL_FUNCTION_V(MaterialxOES,(DYNAMIC_GL_TYPE(enum) face , DYNAMIC_GL_TYPE(enum) pname , DYNAMIC_GL_TYPE(fixed) param),(face , pname , param))
DYNAMIC_GL_FUNCTION_V(MaterialxvOES,(DYNAMIC_GL_TYPE(enum) face , DYNAMIC_GL_TYPE(enum) pname , const DYNAMIC_GL_TYPE(fixed) * params),(face , pname , params))
DYNAMIC_GL_FUNCTION_V(MultMatrixxOES,(const DYNAMIC_GL_TYPE(fixed) * m),(m))
DYNAMIC_GL_FUNCTION_V(MultiTexCoord4xOES,(DYNAMIC_GL_TYPE(enum) target , DYNAMIC_GL_TYPE(fixed) s , DYNAMIC_GL_TYPE(fixed) t , DYNAMIC_GL_TYPE(fixed) r , DYNAMIC_GL_TYPE(fixed) q),(target , s , t , r , q))
DYNAMIC_GL_FUNCTION_V(Normal3xOES,(DYNAMIC_GL_TYPE(fixed) nx , DYNAMIC_GL_TYPE(fixed) ny , DYNAMIC_GL_TYPE(fixed) nz),(nx , ny , nz))
DYNAMIC_GL_FUNCTION_V(OrthoxOES,(DYNAMIC_GL_TYPE(fixed) left , DYNAMIC_GL_TYPE(fixed) right , DYNAMIC_GL_TYPE(fixed) bottom , DYNAMIC_GL_TYPE(fixed) top , DYNAMIC_GL_TYPE(fixed) zNear , DYNAMIC_GL_TYPE(fixed) zFar),(left , right , bottom , top , zNear , zFar))
DYNAMIC_GL_FUNCTION_V(PointParameterxOES,(DYNAMIC_GL_TYPE(enum) pname , DYNAMIC_GL_TYPE(fixed) param),(pname , param))
DYNAMIC_GL_FUNCTION_V(PointParameterxvOES,(DYNAMIC_GL_TYPE(enum) pname , const DYNAMIC_GL_TYPE(fixed) * params),(pname , params))
DYNAMIC_GL_FUNCTION_V(PointSizexOES,(DYNAMIC_GL_TYPE(fixed) size),(size))
DYNAMIC_GL_FUNCTION_V(PolygonOffsetxOES,(DYNAMIC_GL_TYPE(fixed) factor , DYNAMIC_GL_TYPE(fixed) units),(factor , units))
DYNAMIC_GL_FUNCTION_V(RotatexOES,(DYNAMIC_GL_TYPE(fixed) angle , DYNAMIC_GL_TYPE(fixed) x , DYNAMIC_GL_TYPE(fixed) y , DYNAMIC_GL_TYPE(fixed) z),(angle , x , y , z))
DYNAMIC_GL_FUNCTION_V(SampleCoveragexOES,(DYNAMIC_GL_TYPE(clampx) value , DYNAMIC_GL_TYPE(boolean) invert),(value , invert))
DYNAMIC_GL_FUNCTION_V(ScalexOES,(DYNAMIC_GL_TYPE(fixed) x , DYNAMIC_GL_TYPE(fixed) y , DYNAMIC_GL_TYPE(fixed) z),(x , y , z))
DYNAMIC_GL_FUNCTION_V(TexEnvxOES,(DYNAMIC_GL_TYPE(enum) target , DYNAMIC_GL_TYPE(enum) pname , DYNAMIC_GL_TYPE(fixed) param),(target , pname , param))
DYNAMIC_GL_FUNCTION_V(TexEnvxvOES,(DYNAMIC_GL_TYPE(enum) target , DYNAMIC_GL_TYPE(enum) pname , const DYNAMIC_GL_TYPE(fixed) * params),(target , pname , params))
DYNAMIC_GL_FUNCTION_V(TexParameterxOES,(DYNAMIC_GL_TYPE(enum) target , DYNAMIC_GL_TYPE(enum) pname , DYNAMIC_GL_TYPE(fixed) param),(target , pname , param))
DYNAMIC_GL_FUNCTION_V(TexParameterxvOES,(DYNAMIC_GL_TYPE(enum) target , DYNAMIC_GL_TYPE(enum) pname , const DYNAMIC_GL_TYPE(fixed) * params),(target , pname , params))
DYNAMIC_GL_FUNCTION_V(TranslatexOES,(DYNAMIC_GL_TYPE(fixed) x , DYNAMIC_GL_TYPE(fixed) y , DYNAMIC_GL_TYPE(fixed) z),(x , y , z))
#endif /*USE_DYNAMIC_GL_OES_fixed_point*/

/*EXT_multi_draw_arrays*/
#ifdef USE_DYNAMIC_GL_EXT_multi_draw_arrays
DYNAMIC_GL_FEATURE(EXT_multi_draw_arrays)
DYNAMIC_GL_FUNCTION_V(MultiDrawArraysEXT,(DYNAMIC_GL_TYPE(enum) mode , DYNAMIC_GL_TYPE(int) * first , DYNAMIC_GL_TYPE(sizei) * count , DYNAMIC_GL_TYPE(sizei) primcount),(mode , first , count , primcount))
DYNAMIC_GL_FUNCTION_V(MultiDrawElementsEXT,(DYNAMIC_GL_TYPE(enum) mode , const DYNAMIC_GL_TYPE(sizei) * count , DYNAMIC_GL_TYPE(enum) type , const DYNAMIC_GL_TYPE(void) * * indices , DYNAMIC_GL_TYPE(sizei) primcount),(mode , count , type , indices , primcount))
#endif /*USE_DYNAMIC_GL_EXT_multi_draw_arrays*/

